// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the Profile before create.
func (p *Profile) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the Profile before update.
func (p *Profile) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the Profile before delete.
func (p *Profile) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the Tier before create.
func (t *Tier) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the Tier before update.
func (t *Tier) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the Tier before delete.
func (t *Tier) beforeDelete(tx *gorm.DB) error {
	return nil
}
