// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the AttachedObjectReference before create.
func (a *AttachedObjectReference) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the AttachedObjectReference before update.
func (a *AttachedObjectReference) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the AttachedObjectReference before delete.
func (a *AttachedObjectReference) beforeDelete(tx *gorm.DB) error {
	return nil
}
