// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"gorm.io/gorm"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// beforeCreate runs before the AttachedObjectReference is created.
func (a *AttachedObjectReference) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the AttachedObjectReference is updated.
func (a *AttachedObjectReference) beforeUpdate(tx *gorm.DB) error {
	// Relationship is the lifecycle dial; silently widening or narrowing it
	// post-create would change blocking behavior of an existing reference
	if tx.Statement.Changed("Relationship") {
		return util.NewBadRequestError(
			"AttachedObjectReference.Relationship is immutable; recreate the reference to change it",
		)
	}
	return nil
}

// beforeDelete runs before the AttachedObjectReference is deleted.
func (a *AttachedObjectReference) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the AttachedObjectReference is created.
func (a *AttachedObjectReference) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the AttachedObjectReference is updated.
func (a *AttachedObjectReference) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the AttachedObjectReference is deleted.
func (a *AttachedObjectReference) afterDelete(tx *gorm.DB) error {
	return nil
}
