// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import gorm "gorm.io/gorm"

// BeforeCreate is the GORM create hook for AwsEksKubernetesRuntimeDefinition.
func (a *AwsEksKubernetesRuntimeDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := a.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, a)
}

// BeforeUpdate is the GORM update hook for AwsEksKubernetesRuntimeDefinition.
func (a *AwsEksKubernetesRuntimeDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := a.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, a)
}

// BeforeDelete is the GORM delete hook for AwsEksKubernetesRuntimeDefinition.
func (a *AwsEksKubernetesRuntimeDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := a.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, a)
}

// BeforeCreate is the GORM create hook for AwsEksKubernetesRuntimeInstance.
func (a *AwsEksKubernetesRuntimeInstance) BeforeCreate(tx *gorm.DB) error {
	if err := a.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, a)
}

// BeforeUpdate is the GORM update hook for AwsEksKubernetesRuntimeInstance.
func (a *AwsEksKubernetesRuntimeInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := a.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, a)
}

// BeforeDelete is the GORM delete hook for AwsEksKubernetesRuntimeInstance.
func (a *AwsEksKubernetesRuntimeInstance) BeforeDelete(tx *gorm.DB) error {
	if err := a.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, a)
}

// BeforeCreate is the GORM create hook for AwsProvider.
func (a *AwsProvider) BeforeCreate(tx *gorm.DB) error {
	if err := a.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, a)
}

// BeforeUpdate is the GORM update hook for AwsProvider.
func (a *AwsProvider) BeforeUpdate(tx *gorm.DB) error {
	if err := a.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, a)
}

// BeforeDelete is the GORM delete hook for AwsProvider.
func (a *AwsProvider) BeforeDelete(tx *gorm.DB) error {
	if err := a.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, a)
}
