// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on AwsEksKubernetesRuntimeDefinition.
func (a *AwsEksKubernetesRuntimeDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeDefinitionID",
		objectID:     a.KubernetesRuntimeDefinitionID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on AwsEksKubernetesRuntimeInstance.
func (a *AwsEksKubernetesRuntimeInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "AwsEksKubernetesRuntimeDefinitionID",
		objectID:     a.AwsEksKubernetesRuntimeDefinitionID,
		objectType:   util.ObjectTypeName(AwsEksKubernetesRuntimeDefinition{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "AwsProviderID",
		objectID:     a.AwsProviderID,
		objectType:   util.ObjectTypeName(AwsProvider{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     a.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}}
}
