// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	v0 "github.com/threeport/threeport/pkg/sdk/v0"
	v01 "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on AwsEksKubernetesRuntimeDefinition.
func (a *AwsEksKubernetesRuntimeDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeDefinition{}),
		value:        a.KubernetesRuntimeDefinitionID,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on AwsEksKubernetesRuntimeInstance.
func (a *AwsEksKubernetesRuntimeInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "AwsEksKubernetesRuntimeDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(AwsEksKubernetesRuntimeDefinition{}),
		value:        a.AwsEksKubernetesRuntimeDefinitionID,
	}, {
		fieldName:    "AwsProviderID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(AwsProvider{}),
		value:        a.AwsProviderID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        a.KubernetesRuntimeInstanceID,
	}}
}
