// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ControlPlaneInstance.
func (c *ControlPlaneInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "ControlPlaneDefinitionID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(ControlPlaneDefinition{}),
		value:        c.ControlPlaneDefinitionID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        c.KubernetesRuntimeInstanceID,
	}, {
		fieldName:    "ParentControlPlaneInstanceID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(ControlPlaneInstance{}),
		value:        c.ParentControlPlaneInstanceID,
	}}
}
