// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	v0 "github.com/threeport/threeport/pkg/sdk/v0"
	v01 "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ControlPlaneInstance.
func (c *ControlPlaneInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "ControlPlaneDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(ControlPlaneDefinition{}),
		value:        c.ControlPlaneDefinitionID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        c.KubernetesRuntimeInstanceID,
	}, {
		fieldName:    "ParentControlPlaneInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(ControlPlaneInstance{}),
		value:        c.ParentControlPlaneInstanceID,
	}}
}
