// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import gorm "gorm.io/gorm"

// BeforeCreate is the GORM create hook for ControlPlaneDefinition.
func (c *ControlPlaneDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := c.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, c)
}

// BeforeUpdate is the GORM update hook for ControlPlaneDefinition.
func (c *ControlPlaneDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := c.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, c)
}

// BeforeDelete is the GORM delete hook for ControlPlaneDefinition.
func (c *ControlPlaneDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := c.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, c)
}

// BeforeCreate is the GORM create hook for ControlPlaneInstance.
func (c *ControlPlaneInstance) BeforeCreate(tx *gorm.DB) error {
	if err := c.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, c)
}

// BeforeUpdate is the GORM update hook for ControlPlaneInstance.
func (c *ControlPlaneInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := c.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, c)
}

// BeforeDelete is the GORM delete hook for ControlPlaneInstance.
func (c *ControlPlaneInstance) BeforeDelete(tx *gorm.DB) error {
	if err := c.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, c)
}
