// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the ControlPlaneDefinition before create.
func (c *ControlPlaneDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the ControlPlaneDefinition before update.
func (c *ControlPlaneDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the ControlPlaneDefinition before delete.
func (c *ControlPlaneDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the ControlPlaneInstance before create.
func (c *ControlPlaneInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the ControlPlaneInstance before update.
func (c *ControlPlaneInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the ControlPlaneInstance before delete.
func (c *ControlPlaneInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}
