// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the Event before create.
func (e *Event) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the Event before update.
func (e *Event) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the Event before delete.
func (e *Event) beforeDelete(tx *gorm.DB) error {
	return nil
}
