// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	v0 "github.com/threeport/threeport/pkg/sdk/v0"
	v01 "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on DomainNameInstance.
func (d *DomainNameInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "DomainNameDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(DomainNameDefinition{}),
		value:        d.DomainNameDefinitionID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        d.KubernetesRuntimeInstanceID,
	}, {
		fieldName:    "WorkloadInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(WorkloadInstance{}),
		value:        d.WorkloadInstanceID,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on GatewayInstance.
func (g *GatewayInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "GatewayDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(GatewayDefinition{}),
		value:        g.GatewayDefinitionID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        g.KubernetesRuntimeInstanceID,
	}, {
		fieldName:    "WorkloadInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(WorkloadInstance{}),
		value:        g.WorkloadInstanceID,
	}}
}
