// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"

	"gorm.io/gorm"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// beforeCreate validates the GcpProvider before create.
func (g *GcpProvider) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpProvider before update.
func (g *GcpProvider) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpProvider before delete.
//
// Why: a GcpProvider may not be removed while any GKE runtime instance
// still references it. Returns 400 with the count of dependents.
func (g *GcpProvider) beforeDelete(tx *gorm.DB) error {
	var gcpGkeKubernetesRuntimeInstances []GcpGkeKubernetesRuntimeInstance
	if result := tx.Where(
		&GcpGkeKubernetesRuntimeInstance{GcpProviderID: g.ID},
	).Find(&gcpGkeKubernetesRuntimeInstances); result.Error != nil {
		return fmt.Errorf(
			"failed to query gcp gke kubernetes runtime instances for gcp provider %s",
			*g.Name,
		)
	}

	if len(gcpGkeKubernetesRuntimeInstances) > 0 {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"gcp provider %s has related gcp gke kubernetes runtime instances - cannot be deleted",
				*g.Name,
			),
		)
	}
	return nil
}

// beforeCreate validates the GcpGkeKubernetesRuntimeDefinition before create.
func (g *GcpGkeKubernetesRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpGkeKubernetesRuntimeDefinition before update.
func (g *GcpGkeKubernetesRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpGkeKubernetesRuntimeDefinition before delete.
func (g *GcpGkeKubernetesRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the GcpGkeKubernetesRuntimeInstance before create.
func (g *GcpGkeKubernetesRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpGkeKubernetesRuntimeInstance before update.
func (g *GcpGkeKubernetesRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpGkeKubernetesRuntimeInstance before delete.
func (g *GcpGkeKubernetesRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}
