// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	"net"

	"gorm.io/gorm"

	lib "github.com/threeport/threeport/pkg/api/lib/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// beforeCreate validates the GcpProvider before create.
func (g *GcpProvider) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpProvider before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx): values being written
//   - lib.IsFullReplace(tx): true on PUT (Save shape)
//   - lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (g *GcpProvider) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpProvider before delete.
//
// Why: a GcpProvider may not be removed while any GKE runtime instance
// still references it. Returns 400 with the count of dependents.
func (g *GcpProvider) beforeDelete(tx *gorm.DB) error {
	var gcpGkeKubernetesRuntimeInstances []GcpGkeKubernetesRuntimeInstance
	if result := tx.Where(
		&GcpGkeKubernetesRuntimeInstance{GcpProviderID: g.ID},
	).Find(&gcpGkeKubernetesRuntimeInstances); result.Error != nil {
		return fmt.Errorf(
			"failed to query gcp gke kubernetes runtime instances for gcp provider %s",
			*g.Name,
		)
	}

	if len(gcpGkeKubernetesRuntimeInstances) > 0 {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"gcp provider %s has related gcp gke kubernetes runtime instances - cannot be deleted",
				*g.Name,
			),
		)
	}
	return nil
}

// beforeCreate validates the GcpGkeKubernetesRuntimeDefinition before create.
func (g *GcpGkeKubernetesRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpGkeKubernetesRuntimeDefinition before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx): values being written
//   - lib.IsFullReplace(tx): true on PUT (Save shape)
//   - lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (g *GcpGkeKubernetesRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpGkeKubernetesRuntimeDefinition before delete.
func (g *GcpGkeKubernetesRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the GcpGkeKubernetesRuntimeInstance before create.
func (g *GcpGkeKubernetesRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpGkeKubernetesRuntimeInstance before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx): values being written
//   - lib.IsFullReplace(tx): true on PUT (Save shape)
//   - lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (g *GcpGkeKubernetesRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpGkeKubernetesRuntimeInstance before delete.
func (g *GcpGkeKubernetesRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the GcpGceMachineRuntimeDefinition before create.
func (g *GcpGceMachineRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the GcpGceMachineRuntimeDefinition before update.
func (g *GcpGceMachineRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the GcpGceMachineRuntimeDefinition before delete.
func (g *GcpGceMachineRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the GcpGceMachineRuntimeInstance before create.
func (g *GcpGceMachineRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate rejects changes to the immutable placement and association
// fields. It checks each through lib.IsFieldChanged so immutability is enforced
// under both PATCH and PUT; the region, zone, network, definition, and provider
// are fixed once the VM is provisioned, while the ssh source ranges and ssh
// user stay mutable so a pulumi up can apply them in place.
func (g *GcpGceMachineRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	immutableFields := []struct {
		column string
		name   string
	}{
		{"Region", "region"},
		{"Zone", "zone"},
		{"NetworkID", "network id"},
		{"GcpGceMachineRuntimeDefinitionID", "definition"},
		{"GcpProviderID", "provider"},
	}
	for _, field := range immutableFields {
		changed, err := lib.IsFieldChanged(tx, field.column)
		if err != nil {
			return fmt.Errorf("failed to check %s for changes: %w", field.name, err)
		}
		if changed {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"gcp gce machine runtime instance %s cannot be changed after creation",
					field.name,
				),
			)
		}
	}
	return nil
}

// beforeDelete validates the GcpGceMachineRuntimeInstance before delete.
func (g *GcpGceMachineRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the GcpProvider is created.
func (g *GcpProvider) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the GcpProvider is updated.
func (g *GcpProvider) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the GcpProvider is deleted.
func (g *GcpProvider) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the GcpGkeKubernetesRuntimeDefinition is created.
func (g *GcpGkeKubernetesRuntimeDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the GcpGkeKubernetesRuntimeDefinition is updated.
func (g *GcpGkeKubernetesRuntimeDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the GcpGkeKubernetesRuntimeDefinition is deleted.
func (g *GcpGkeKubernetesRuntimeDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the GcpGkeKubernetesRuntimeInstance is created.
func (g *GcpGkeKubernetesRuntimeInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the GcpGkeKubernetesRuntimeInstance is updated.
func (g *GcpGkeKubernetesRuntimeInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the GcpGkeKubernetesRuntimeInstance is deleted.
func (g *GcpGkeKubernetesRuntimeInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the GcpGceMachineRuntimeDefinition is created.
func (g *GcpGceMachineRuntimeDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the GcpGceMachineRuntimeDefinition is updated.
func (g *GcpGceMachineRuntimeDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the GcpGceMachineRuntimeDefinition is deleted.
func (g *GcpGceMachineRuntimeDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the GcpGceMachineRuntimeInstance is created.
func (g *GcpGceMachineRuntimeInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the GcpGceMachineRuntimeInstance is updated.
func (g *GcpGceMachineRuntimeInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the GcpGceMachineRuntimeInstance is deleted.
func (g *GcpGceMachineRuntimeInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the GcpNetwork before create by requiring both CIDRs
// and enforcing that the subnet CIDR is fully contained in the network CIDR.
// Catches misconfigured requests before a pulumi program is launched with an
// impossible network shape.
func (g *GcpNetwork) beforeCreate(tx *gorm.DB) error {
	if g.NetworkCIDR == nil || *g.NetworkCIDR == "" {
		return util.NewBadRequestError("gcp network requires NetworkCIDR")
	}
	if g.SubnetCIDR == nil || *g.SubnetCIDR == "" {
		return util.NewBadRequestError("gcp network requires SubnetCIDR")
	}
	contained, err := cidrContainsSubnet(*g.NetworkCIDR, *g.SubnetCIDR)
	if err != nil {
		return util.NewBadRequestError(fmt.Sprintf("failed to validate subnet containment: %s", err.Error()))
	}
	if !contained {
		return util.NewBadRequestError(fmt.Sprintf(
			"subnet CIDR %s is not contained in network CIDR %s",
			*g.SubnetCIDR,
			*g.NetworkCIDR,
		))
	}
	return nil
}

// beforeUpdate validates the GcpNetwork before update.
func (g *GcpNetwork) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete blocks deletion of a GcpNetwork while any
// GcpGceMachineRuntimeInstance still resolves to it (matches this network's
// GcpProviderID and Zone). Replaces the requires-AOR pattern with a live
// query so no FK is stored on the instance.
func (g *GcpNetwork) beforeDelete(tx *gorm.DB) error {
	if g.GcpProviderID == nil || g.Zone == nil {
		return nil
	}
	var count int64
	if err := tx.Model(&GcpGceMachineRuntimeInstance{}).
		Where("gcp_provider_id = ? AND zone = ?", *g.GcpProviderID, *g.Zone).
		Count(&count).Error; err != nil {
		return fmt.Errorf("failed to count referencing gce instances: %w", err)
	}
	if count > 0 {
		return util.NewBadRequestError(fmt.Sprintf(
			"cannot delete gcp network: %d gce machine runtime instances still resolve to it (provider=%d zone=%s)",
			count, *g.GcpProviderID, *g.Zone,
		))
	}
	return nil
}

// afterCreate runs after the GcpNetwork is created.
func (g *GcpNetwork) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the GcpNetwork is updated.
func (g *GcpNetwork) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the GcpNetwork is deleted.
func (g *GcpNetwork) afterDelete(tx *gorm.DB) error {
	return nil
}

// cidrContainsSubnet reports whether subnetCIDR is entirely contained within
// networkCIDR. Both arguments must parse as valid CIDR blocks.
func cidrContainsSubnet(networkCIDR, subnetCIDR string) (bool, error) {
	_, networkNet, err := net.ParseCIDR(networkCIDR)
	if err != nil {
		return false, fmt.Errorf("failed to parse network CIDR: %w", err)
	}
	subnetIP, subnetNet, err := net.ParseCIDR(subnetCIDR)
	if err != nil {
		return false, fmt.Errorf("failed to parse subnet CIDR: %w", err)
	}
	// containment: the subnet's network address sits inside the outer network
	// and the outer mask is no wider than the subnet's mask
	networkOnes, networkBits := networkNet.Mask.Size()
	subnetOnes, subnetBits := subnetNet.Mask.Size()
	if networkBits != subnetBits {
		return false, nil
	}
	if networkOnes > subnetOnes {
		return false, nil
	}
	return networkNet.Contains(subnetIP), nil
}
