// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on GcpGkeKubernetesRuntimeDefinition.
func (g *GcpGkeKubernetesRuntimeDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeDefinitionID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeDefinition{}),
		value:        g.KubernetesRuntimeDefinitionID,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on GcpGkeKubernetesRuntimeInstance.
func (g *GcpGkeKubernetesRuntimeInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "GcpGkeKubernetesRuntimeDefinitionID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(GcpGkeKubernetesRuntimeDefinition{}),
		value:        g.GcpGkeKubernetesRuntimeDefinitionID,
	}, {
		fieldName:    "GcpProviderID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(GcpProvider{}),
		value:        g.GcpProviderID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        g.KubernetesRuntimeInstanceID,
	}}
}
