// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on HelmWorkloadInstance.
func (h *HelmWorkloadInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "HelmWorkloadDefinitionID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(HelmWorkloadDefinition{}),
		value:        h.HelmWorkloadDefinitionID,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        h.KubernetesRuntimeInstanceID,
	}}
}
