// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the HelmWorkloadDefinition before create.
func (h *HelmWorkloadDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the HelmWorkloadDefinition before update.
func (h *HelmWorkloadDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the HelmWorkloadDefinition before delete.
func (h *HelmWorkloadDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the HelmWorkloadInstance before create.
func (h *HelmWorkloadInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the HelmWorkloadInstance before update.
func (h *HelmWorkloadInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the HelmWorkloadInstance before delete.
func (h *HelmWorkloadInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}
