// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the LogBackend before create.
func (l *LogBackend) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the LogBackend before update.
func (l *LogBackend) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the LogBackend before delete.
func (l *LogBackend) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the LogStorageDefinition before create.
func (l *LogStorageDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the LogStorageDefinition before update.
func (l *LogStorageDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the LogStorageDefinition before delete.
func (l *LogStorageDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the LogStorageInstance before create.
func (l *LogStorageInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the LogStorageInstance before update.
func (l *LogStorageInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the LogStorageInstance before delete.
func (l *LogStorageInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}
