// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on LogStorageInstance.
func (l *LogStorageInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "ClusterID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        l.ClusterID,
	}}
}
