// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate runs before the LogBackend is created.
func (l *LogBackend) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the LogBackend is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx, l): values being written
//   - lib.IsFullReplace(tx, l): true for PUT, false for PATCH
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (l *LogBackend) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the LogBackend is deleted.
func (l *LogBackend) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the LogBackend is created.
func (l *LogBackend) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the LogBackend is updated.
func (l *LogBackend) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the LogBackend is deleted.
func (l *LogBackend) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the LogStorageDefinition is created.
func (l *LogStorageDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the LogStorageDefinition is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx, l): values being written
//   - lib.IsFullReplace(tx, l): true for PUT, false for PATCH
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (l *LogStorageDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the LogStorageDefinition is deleted.
func (l *LogStorageDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the LogStorageDefinition is created.
func (l *LogStorageDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the LogStorageDefinition is updated.
func (l *LogStorageDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the LogStorageDefinition is deleted.
func (l *LogStorageDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the LogStorageInstance is created.
func (l *LogStorageInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the LogStorageInstance is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx, l): values being written
//   - lib.IsFullReplace(tx, l): true for PUT, false for PATCH
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (l *LogStorageInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the LogStorageInstance is deleted.
func (l *LogStorageInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the LogStorageInstance is created.
func (l *LogStorageInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the LogStorageInstance is updated.
func (l *LogStorageInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the LogStorageInstance is deleted.
func (l *LogStorageInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
