// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"

	"gorm.io/gorm"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// beforeCreate validates the MachineRuntimeDefinition before create.
func (m *MachineRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the MachineRuntimeDefinition before update.
func (m *MachineRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the MachineRuntimeDefinition before delete.
func (m *MachineRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the MachineRuntimeInstance before create.
//
// Why: at least one of SSHKey or SSHPassword must be provided so the
// reconciler has a credential to authenticate with the machine.  When an
// infra provider is set, a region is also required because no provider can
// provision a machine without one; imported machines leave both unset.
func (m *MachineRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	if m.SSHKey == nil && m.SSHPassword == nil {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"machine runtime instance %s must have at least one of SSHKey or SSHPassword",
				*m.Name,
			),
		)
	}
	if m.InfraProvider != nil && *m.InfraProvider != "" {
		if m.Region == nil || *m.Region == "" {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"machine runtime instance %s sets an infra provider and must also set a region",
					*m.Name,
				),
			)
		}
	}
	return nil
}

// beforeUpdate validates the MachineRuntimeInstance before update.
//
// The provisioning identity fields are immutable: they cannot be changed
// once the row exists with a value, and cannot be introduced post-create
// either.  Changing them after creation would orphan the provisioned
// resources, and introducing a provider on an existing machine belongs to
// a new instance, not an update.  Create is therefore the only place the
// provider/region pairing is validated.
func (m *MachineRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	immutableFields := []struct {
		column string
		name   string
	}{
		{"InfraProvider", "infra provider"},
		{"Region", "region"},
		{"MachineType", "machine type"},
		{"ImageID", "image id"},
		{"NetworkID", "network id"},
	}
	for _, field := range immutableFields {
		if tx.Statement.Changed(field.column) {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"machine runtime instance %s cannot be changed after creation",
					field.name,
				),
			)
		}
	}
	return nil
}

// beforeDelete is a no-op for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineRuntimeDefinition is created.
func (m *MachineRuntimeDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineRuntimeDefinition is updated.
func (m *MachineRuntimeDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineRuntimeDefinition is deleted.
func (m *MachineRuntimeDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineRuntimeInstance is created.
func (m *MachineRuntimeInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineRuntimeInstance is updated.
func (m *MachineRuntimeInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineRuntimeInstance is deleted.
func (m *MachineRuntimeInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
