// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"

	"gorm.io/gorm"

	lib "github.com/threeport/threeport/pkg/api/lib/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

const (
	// MachineRuntimeInfraProviderGCE selects Google Compute Engine as the
	// machine runtime provider.
	MachineRuntimeInfraProviderGCE = "gce"
)

// MachineRuntimeInfraProviderForCloudProvider maps a cloud provider name
// (util.GcpProvider, util.AwsProvider, util.OciProvider) to the concrete
// machine-runtime infra provider token this API server routes on. Cloud
// provider names are what users write in user-facing config (RouterMachine,
// Fleet, RouterMachineSet); the machine-runtime API keys its provisioning
// switch on the compute-service name because a cloud provider can host more
// than one compute service (GCP: GCE and GKE, AWS: EC2 and Fargate, etc.).
// Modules that carry a Provider field forward to threeport-core call this
// once at handoff so a mapping addition here reaches every module without
// per-module changes. Returns an error for an unknown or empty cloud
// provider so an accidental typo surfaces at the caller.
func MachineRuntimeInfraProviderForCloudProvider(cloudProvider string) (string, error) {
	switch cloudProvider {
	case util.GcpProvider:
		return MachineRuntimeInfraProviderGCE, nil
	case "":
		return "", fmt.Errorf("cloud provider is required")
	default:
		return "", fmt.Errorf("cloud provider %q is not supported for machine runtime provisioning", cloudProvider)
	}
}

// beforeCreate validates the MachineRuntimeDefinition before create.
func (m *MachineRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate rejects changes to the immutable provisioning template
// fields. It checks each through lib.IsFieldChanged so immutability is
// enforced under both PATCH and PUT; the infra provider, machine type, and
// image must stay fixed once instances derive from the definition.
func (m *MachineRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	immutableFields := []struct {
		column string
		name   string
	}{
		{"InfraProvider", "infra provider"},
		{"MachineType", "machine type"},
		{"ImageID", "image id"},
	}
	for _, field := range immutableFields {
		changed, err := lib.IsFieldChanged(tx, field.column)
		if err != nil {
			return fmt.Errorf("failed to check %s for changes: %w", field.name, err)
		}
		if changed {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"machine runtime definition %s cannot be changed after creation",
					field.name,
				),
			)
		}
	}
	return nil
}

// beforeDelete validates the MachineRuntimeDefinition before delete.
func (m *MachineRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the MachineRuntimeInstance before create.
//
// Two invariants are enforced:
//   - at least one of SSHKey or SSHPassword must be provided so the
//     reconciler has a credential to authenticate with the machine.
//   - when the referenced machine runtime definition has an infra provider
//     set, the instance must supply a location or a region so the provider
//     knows where to provision the machine. The controller maps a location to
//     a provider region and zone; a concrete region serves imported machines.
func (m *MachineRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	if m.SSHKey == nil && m.SSHPassword == nil {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"machine runtime instance %s must have at least one of SSHKey or SSHPassword",
				*m.Name,
			),
		)
	}

	if m.MachineRuntimeDefinitionID != nil {
		var def MachineRuntimeDefinition
		if err := tx.First(&def, *m.MachineRuntimeDefinitionID).Error; err != nil {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"machine runtime instance %s references machine runtime definition %d which does not exist",
					*m.Name,
					*m.MachineRuntimeDefinitionID,
				),
			)
		}
		if def.InfraProvider != nil && *def.InfraProvider != "" {
			locationEmpty := m.Location == nil || *m.Location == ""
			regionEmpty := m.Region == nil || *m.Region == ""
			if locationEmpty && regionEmpty {
				return util.NewBadRequestError(
					fmt.Sprintf(
						"machine runtime instance %s must have a location or region when the definition specifies an infra provider",
						*m.Name,
					),
				)
			}
		}
	}

	return nil
}

// beforeUpdate rejects changes to the immutable provisioning location
// fields. It checks each through lib.IsFieldChanged so immutability is
// enforced under both PATCH and PUT; changing them after creation would
// orphan the provisioned resources.
func (m *MachineRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	immutableFields := []struct {
		column string
		name   string
	}{
		{"Location", "location"},
		{"Region", "region"},
		{"NetworkID", "network id"},
	}
	for _, field := range immutableFields {
		changed, err := lib.IsFieldChanged(tx, field.column)
		if err != nil {
			return fmt.Errorf("failed to check %s for changes: %w", field.name, err)
		}
		if changed {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"machine runtime instance %s cannot be changed after creation",
					field.name,
				),
			)
		}
	}
	return nil
}

// beforeDelete is a no-op for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineRuntimeDefinition is created.
func (m *MachineRuntimeDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineRuntimeDefinition is updated.
func (m *MachineRuntimeDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineRuntimeDefinition is deleted.
func (m *MachineRuntimeDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineRuntimeInstance is created.
func (m *MachineRuntimeInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineRuntimeInstance is updated.
func (m *MachineRuntimeInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineRuntimeInstance is deleted.
func (m *MachineRuntimeInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
