// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	"regexp"
	"strings"

	"gorm.io/gorm"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// envKeyRegex matches a valid POSIX environment variable name.
var envKeyRegex = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)

// validateEnv checks that each entry in an Env slice is in KEY=VALUE format
// where KEY matches [a-zA-Z_][a-zA-Z0-9_]*. A nil pointer is treated as no
// env to validate.
func validateEnv(env *[]string) error {
	if env == nil {
		return nil
	}
	for _, entry := range *env {
		parts := strings.SplitN(entry, "=", 2)
		if len(parts) != 2 {
			return util.NewBadRequestError(
				fmt.Sprintf("invalid env entry %q: must be in KEY=VALUE format", entry),
			)
		}
		if !envKeyRegex.MatchString(parts[0]) {
			return util.NewBadRequestError(
				fmt.Sprintf(
					"invalid env key %q: must match [a-zA-Z_][a-zA-Z0-9_]*",
					parts[0],
				),
			)
		}
	}
	return nil
}

// beforeCreate validates the MachineWorkloadDefinition before create.
func (m *MachineWorkloadDefinition) beforeCreate(tx *gorm.DB) error {
	return validateEnv(m.Env)
}

// beforeUpdate validates the MachineWorkloadDefinition before update.
//
// Receiver is the loaded DB row. The new field values being written
// are in tx.Statement.Dest (cast to *MachineWorkloadDefinition).
// Use tx.Statement.Changed("FieldName") to detect field changes.
func (m *MachineWorkloadDefinition) beforeUpdate(tx *gorm.DB) error {
	if !tx.Statement.Changed("Env") {
		return nil
	}
	target := m
	if dest, ok := tx.Statement.Dest.(*MachineWorkloadDefinition); ok && dest != m {
		target = dest
	}
	return validateEnv(target.Env)
}

// beforeDelete validates the MachineWorkloadDefinition before delete.
func (m *MachineWorkloadDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the MachineWorkloadInstance before create.
func (m *MachineWorkloadInstance) beforeCreate(tx *gorm.DB) error {
	return validateEnv(m.Env)
}

// beforeUpdate validates the MachineWorkloadInstance before update.
//
// Receiver is the loaded DB row. The new field values being written
// are in tx.Statement.Dest (cast to *MachineWorkloadInstance).
// Use tx.Statement.Changed("FieldName") to detect field changes.
func (m *MachineWorkloadInstance) beforeUpdate(tx *gorm.DB) error {
	if !tx.Statement.Changed("Env") {
		return nil
	}
	target := m
	if dest, ok := tx.Statement.Dest.(*MachineWorkloadInstance); ok && dest != m {
		target = dest
	}
	return validateEnv(target.Env)
}

// beforeDelete validates the MachineWorkloadInstance before delete.
func (m *MachineWorkloadInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineWorkloadDefinition is created.
func (m *MachineWorkloadDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineWorkloadDefinition is updated.
func (m *MachineWorkloadDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineWorkloadDefinition is deleted.
func (m *MachineWorkloadDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineWorkloadInstance is created.
func (m *MachineWorkloadInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineWorkloadInstance is updated.
func (m *MachineWorkloadInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineWorkloadInstance is deleted.
func (m *MachineWorkloadInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
