// generated by 'threeport-sdk gen' - do not edit

package v0

import gorm "gorm.io/gorm"

// BeforeCreate is the GORM before-create hook for MachineWorkloadDefinition.
func (m *MachineWorkloadDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MachineWorkloadDefinition.
func (m *MachineWorkloadDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MachineWorkloadDefinition.
func (m *MachineWorkloadDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MachineWorkloadDefinition.
func (m *MachineWorkloadDefinition) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MachineWorkloadDefinition.
func (m *MachineWorkloadDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MachineWorkloadDefinition.
func (m *MachineWorkloadDefinition) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}

// BeforeCreate is the GORM before-create hook for MachineWorkloadInstance.
func (m *MachineWorkloadInstance) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MachineWorkloadInstance.
func (m *MachineWorkloadInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MachineWorkloadInstance.
func (m *MachineWorkloadInstance) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MachineWorkloadInstance.
func (m *MachineWorkloadInstance) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MachineWorkloadInstance.
func (m *MachineWorkloadInstance) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MachineWorkloadInstance.
func (m *MachineWorkloadInstance) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}
