// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"

	"gorm.io/gorm"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// beforeCreate validates the MachineRuntimeDefinition before create.
func (m *MachineRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the MachineRuntimeDefinition before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx): values being written
//   - lib.IsFullReplace(tx): true on PUT (Save shape)
//   - lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (m *MachineRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the MachineRuntimeDefinition before delete.
func (m *MachineRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the MachineRuntimeInstance before create.
//
// Why: at least one of SSHKey or SSHPassword must be provided so the
// reconciler has a credential to authenticate with the machine.
func (m *MachineRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	if m.SSHKey == nil && m.SSHPassword == nil {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"machine runtime instance %s must have at least one of SSHKey or SSHPassword",
				*m.Name,
			),
		)
	}
	return nil
}

// beforeUpdate validates the MachineRuntimeInstance before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx): values being written
//   - lib.IsFullReplace(tx): true on PUT (Save shape)
//   - lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (m *MachineRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete is a no-op for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineRuntimeDefinition is created.
func (m *MachineRuntimeDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineRuntimeDefinition is updated.
func (m *MachineRuntimeDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineRuntimeDefinition is deleted.
func (m *MachineRuntimeDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MachineRuntimeInstance is created.
func (m *MachineRuntimeInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MachineRuntimeInstance is updated.
func (m *MachineRuntimeInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MachineRuntimeInstance is deleted.
func (m *MachineRuntimeInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
