// generated by 'threeport-sdk gen' - do not edit

package v0

import gorm "gorm.io/gorm"

// BeforeCreate is the GORM before-create hook for MachineRuntimeDefinition.
func (m *MachineRuntimeDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MachineRuntimeDefinition.
func (m *MachineRuntimeDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MachineRuntimeDefinition.
func (m *MachineRuntimeDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MachineRuntimeDefinition.
func (m *MachineRuntimeDefinition) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MachineRuntimeDefinition.
func (m *MachineRuntimeDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MachineRuntimeDefinition.
func (m *MachineRuntimeDefinition) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}

// BeforeCreate is the GORM before-create hook for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MachineRuntimeInstance.
func (m *MachineRuntimeInstance) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}
