// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ModuleApiRoute.
func (m *ModuleApiRoute) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "ModuleApiID",
		objectID:     m.ModuleApiID,
		objectType:   util.ObjectTypeName(ModuleApi{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ModuleController.
func (m *ModuleController) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "ModuleApiID",
		objectID:     m.ModuleApiID,
		objectType:   util.ObjectTypeName(ModuleApi{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ModuleObject.
func (m *ModuleObject) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "ModuleApiID",
		objectID:     m.ModuleApiID,
		objectType:   util.ObjectTypeName(ModuleApi{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "ModuleControllerID",
		objectID:     m.ModuleControllerID,
		objectType:   util.ObjectTypeName(ModuleController{}),
		relationship: sdk.RelationshipRequires,
	}}
}
