// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on LoggingDefinition.
func (l *LoggingDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "LokiHelmWorkloadDefinitionID",
		objectID:     l.LokiHelmWorkloadDefinitionID,
		objectType:   util.ObjectTypeName(HelmWorkloadDefinition{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "PromtailHelmWorkloadDefinitionID",
		objectID:     l.PromtailHelmWorkloadDefinitionID,
		objectType:   util.ObjectTypeName(HelmWorkloadDefinition{}),
		relationship: sdk.RelationshipOwns,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on LoggingInstance.
func (l *LoggingInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     l.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "LoggingDefinitionID",
		objectID:     l.LoggingDefinitionID,
		objectType:   util.ObjectTypeName(LoggingDefinition{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "LokiHelmWorkloadInstanceID",
		objectID:     l.LokiHelmWorkloadInstanceID,
		objectType:   util.ObjectTypeName(HelmWorkloadInstance{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "PromtailHelmWorkloadInstanceID",
		objectID:     l.PromtailHelmWorkloadInstanceID,
		objectType:   util.ObjectTypeName(HelmWorkloadInstance{}),
		relationship: sdk.RelationshipOwns,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on MetricsDefinition.
func (m *MetricsDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubePrometheusStackHelmWorkloadDefinitionID",
		objectID:     m.KubePrometheusStackHelmWorkloadDefinitionID,
		objectType:   util.ObjectTypeName(HelmWorkloadDefinition{}),
		relationship: sdk.RelationshipOwns,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on MetricsInstance.
func (m *MetricsInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubePrometheusStackHelmWorkloadInstanceID",
		objectID:     m.KubePrometheusStackHelmWorkloadInstanceID,
		objectType:   util.ObjectTypeName(HelmWorkloadInstance{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     m.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "MetricsDefinitionID",
		objectID:     m.MetricsDefinitionID,
		objectType:   util.ObjectTypeName(MetricsDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "GrafanaHelmWorkloadDefinitionID",
		objectID:     o.GrafanaHelmWorkloadDefinitionID,
		objectType:   util.ObjectTypeName(HelmWorkloadDefinition{}),
		relationship: sdk.RelationshipOwns,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "GrafanaHelmWorkloadInstanceID",
		objectID:     o.GrafanaHelmWorkloadInstanceID,
		objectType:   util.ObjectTypeName(HelmWorkloadInstance{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     o.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "ObservabilityDashboardDefinitionID",
		objectID:     o.ObservabilityDashboardDefinitionID,
		objectType:   util.ObjectTypeName(ObservabilityDashboardDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "LoggingDefinitionID",
		objectID:     o.LoggingDefinitionID,
		objectType:   util.ObjectTypeName(LoggingDefinition{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "MetricsDefinitionID",
		objectID:     o.MetricsDefinitionID,
		objectType:   util.ObjectTypeName(MetricsDefinition{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "ObservabilityDashboardDefinitionID",
		objectID:     o.ObservabilityDashboardDefinitionID,
		objectType:   util.ObjectTypeName(ObservabilityDashboardDefinition{}),
		relationship: sdk.RelationshipOwns,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on ObservabilityStackInstance.
func (o *ObservabilityStackInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     o.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "LoggingInstanceID",
		objectID:     o.LoggingInstanceID,
		objectType:   util.ObjectTypeName(LoggingInstance{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "MetricsInstanceID",
		objectID:     o.MetricsInstanceID,
		objectType:   util.ObjectTypeName(MetricsInstance{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "ObservabilityDashboardInstanceID",
		objectID:     o.ObservabilityDashboardInstanceID,
		objectType:   util.ObjectTypeName(ObservabilityDashboardInstance{}),
		relationship: sdk.RelationshipOwns,
	}, {
		fieldName:    "ObservabilityStackDefinitionID",
		objectID:     o.ObservabilityStackDefinitionID,
		objectType:   util.ObjectTypeName(ObservabilityStackDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}
