// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate validates the LoggingDefinition before create.
func (l *LoggingDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the LoggingDefinition before update.
func (l *LoggingDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the LoggingDefinition before delete.
func (l *LoggingDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the LoggingInstance before create.
func (l *LoggingInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the LoggingInstance before update.
func (l *LoggingInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the LoggingInstance before delete.
func (l *LoggingInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the MetricsDefinition before create.
func (m *MetricsDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the MetricsDefinition before update.
func (m *MetricsDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the MetricsDefinition before delete.
func (m *MetricsDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the MetricsInstance before create.
func (m *MetricsInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the MetricsInstance before update.
func (m *MetricsInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the MetricsInstance before delete.
func (m *MetricsInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the ObservabilityDashboardDefinition before create.
func (o *ObservabilityDashboardDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the ObservabilityDashboardDefinition before update.
func (o *ObservabilityDashboardDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the ObservabilityDashboardDefinition before delete.
func (o *ObservabilityDashboardDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the ObservabilityDashboardInstance before create.
func (o *ObservabilityDashboardInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the ObservabilityDashboardInstance before update.
func (o *ObservabilityDashboardInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the ObservabilityDashboardInstance before delete.
func (o *ObservabilityDashboardInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the ObservabilityStackDefinition before create.
func (o *ObservabilityStackDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the ObservabilityStackDefinition before update.
func (o *ObservabilityStackDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the ObservabilityStackDefinition before delete.
func (o *ObservabilityStackDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the ObservabilityStackInstance before create.
func (o *ObservabilityStackInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the ObservabilityStackInstance before update.
func (o *ObservabilityStackInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the ObservabilityStackInstance before delete.
func (o *ObservabilityStackInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}
