// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	v0 "github.com/threeport/threeport/pkg/sdk/v0"
	v01 "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on OciOkeKubernetesRuntimeDefinition.
func (o *OciOkeKubernetesRuntimeDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeDefinition{}),
		value:        o.KubernetesRuntimeDefinitionID,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on OciOkeKubernetesRuntimeInstance.
func (o *OciOkeKubernetesRuntimeInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        o.KubernetesRuntimeInstanceID,
	}, {
		fieldName:    "OciOkeKubernetesRuntimeDefinitionID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(OciOkeKubernetesRuntimeDefinition{}),
		value:        o.OciOkeKubernetesRuntimeDefinitionID,
	}, {
		fieldName:    "OciProviderID",
		relationship: v0.RelationshipRequires,
		targetType:   v01.ObjectTypeName(OciProvider{}),
		value:        o.OciProviderID,
	}}
}
