// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on OciOkeKubernetesRuntimeDefinition.
func (o *OciOkeKubernetesRuntimeDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeDefinitionID",
		objectID:     o.KubernetesRuntimeDefinitionID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on OciOkeKubernetesRuntimeInstance.
func (o *OciOkeKubernetesRuntimeInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     o.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "OciOkeKubernetesRuntimeDefinitionID",
		objectID:     o.OciOkeKubernetesRuntimeDefinitionID,
		objectType:   util.ObjectTypeName(OciOkeKubernetesRuntimeDefinition{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "OciProviderID",
		objectID:     o.OciProviderID,
		objectType:   util.ObjectTypeName(OciProvider{}),
		relationship: sdk.RelationshipRequires,
	}}
}
