// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on OciOkeKubernetesRuntimeDefinition.
func (o *OciOkeKubernetesRuntimeDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeDefinitionID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeDefinition{}),
		value:        o.KubernetesRuntimeDefinitionID,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on OciOkeKubernetesRuntimeInstance.
func (o *OciOkeKubernetesRuntimeInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeInstanceID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		value:        o.KubernetesRuntimeInstanceID,
	}, {
		fieldName:    "OciOkeKubernetesRuntimeDefinitionID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(OciOkeKubernetesRuntimeDefinition{}),
		value:        o.OciOkeKubernetesRuntimeDefinitionID,
	}, {
		fieldName:    "OciProviderID",
		relationship: sdk.RelationshipRequires,
		targetType:   util.ObjectTypeName(OciProvider{}),
		value:        o.OciProviderID,
	}}
}
