package v0

import (
	"fmt"

	"gorm.io/gorm"

	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// relationshipForeignKey describes one *uint <Target>ID field on an API
// object that is tagged `relationship:"owns"` or `relationship:"requires"`.
type relationshipForeignKey struct {
	fieldName    string
	objectType   string // e.g. "WorkloadInstance"
	relationship string // sdk.RelationshipOwns or sdk.RelationshipRequires
	objectID     *uint
}

// relationshipForeignKeyProvider is implemented by every API type with at least one
// relationship-tagged foreign key. The method is generated by the SDK so the
// runtime hooks do not reflect over struct tags on every write.
type relationshipForeignKeyProvider interface {
	RelationshipForeignKeys() []relationshipForeignKey
}

// foreignKeysFor returns the relationship foreign keys of obj, or nil if obj has none.
func foreignKeysFor(obj interface{}) []relationshipForeignKey {
	p, ok := obj.(relationshipForeignKeyProvider)
	if !ok {
		return nil
	}
	return p.RelationshipForeignKeys()
}

// insertAttachedObjectReference creates an attached object reference for foreignKey.
// Both `owns` and `requires` edges are immutable once set, so this only ever
// runs on fresh edges.
func insertAttachedObjectReference(tx *gorm.DB, foreignKey relationshipForeignKey, attachedID *uint, attachedType string) error {
	objectType := util.TargetTypeName(attachedType, foreignKey.objectType)
	relationship := foreignKey.relationship
	if err := tx.Create(&AttachedObjectReference{
		ObjectID:           foreignKey.objectID,
		ObjectType:         &objectType,
		AttachedObjectID:   attachedID,
		AttachedObjectType: &attachedType,
		Relationship:       &relationship,
	}).Error; err != nil {
		return fmt.Errorf(
			"failed to create attached object reference for %s.%s: %w",
			attachedType, foreignKey.fieldName, err,
		)
	}
	return nil
}

// processRelationshipTaggedFieldsAfterCreate inserts attached object
// references for each relationship-tagged foreign key with a non-nil value.
func processRelationshipTaggedFieldsAfterCreate(tx *gorm.DB, obj interface{}) error {
	foreignKeys := foreignKeysFor(obj)
	if len(foreignKeys) == 0 {
		return nil
	}
	objType := util.ObjectTypeName(obj)
	objID := util.ObjectID(obj)
	if objID == nil {
		return fmt.Errorf(
			"cannot create attached object reference for %s: ID is nil after create",
			objType,
		)
	}
	for _, foreignKey := range foreignKeys {
		if foreignKey.objectID == nil {
			continue
		}
		if err := insertAttachedObjectReference(tx, foreignKey, objID, objType); err != nil {
			return err
		}
	}
	return nil
}

// processRelationshipTaggedFieldsBeforeUpdate rejects updates that would
// mutate a non-nil relationship-tagged foreign key on the row, and rejects updates to
// any row that is owned by another object via an incoming `owns` reference.
func processRelationshipTaggedFieldsBeforeUpdate(tx *gorm.DB, obj interface{}) error {
	for _, foreignKey := range foreignKeysFor(obj) {
		if foreignKey.objectID == nil {
			continue
		}
		if !tx.Statement.Changed(foreignKey.fieldName) {
			continue
		}
		return util.NewBadRequestError(fmt.Sprintf(
			"%s is immutable; tear down and recreate the holder to undo this relationship",
			foreignKey.fieldName,
		))
	}

	objType := util.ObjectTypeName(obj)
	objID := util.ObjectID(obj)
	if objID == nil {
		return nil
	}
	var ownedRefs []AttachedObjectReference
	if err := tx.
		Where("object_type = ? AND object_id = ? AND relationship = ?", objType, objID, sdk.RelationshipOwns).
		Find(&ownedRefs).Error; err != nil {
		return fmt.Errorf(
			"failed to look up owning attached object references for %s/%d: %w",
			objType, *objID, err,
		)
	}
	if len(ownedRefs) > 0 {
		owner := "another object"
		if ownedRefs[0].AttachedObjectType != nil && ownedRefs[0].AttachedObjectID != nil {
			owner = fmt.Sprintf("%s/%d", *ownedRefs[0].AttachedObjectType, *ownedRefs[0].AttachedObjectID)
		}
		return util.NewBadRequestError(fmt.Sprintf(
			"object is owned by %s and cannot be updated externally; tear down the owner first",
			owner,
		))
	}
	return nil
}

// processRelationshipTaggedFieldsAfterUpdate inserts attached object
// references for each relationship-tagged foreign key that just transitioned
// from nil to a value. Other transitions are blocked by BeforeUpdate.
func processRelationshipTaggedFieldsAfterUpdate(tx *gorm.DB, obj interface{}) error {
	foreignKeys := foreignKeysFor(obj)
	if len(foreignKeys) == 0 {
		return nil
	}
	objType := util.ObjectTypeName(obj)
	objID := util.ObjectID(obj)
	if objID == nil {
		return nil
	}
	for _, foreignKey := range foreignKeys {
		if foreignKey.objectID == nil {
			continue
		}
		if !tx.Statement.Changed(foreignKey.fieldName) {
			continue
		}
		if err := insertAttachedObjectReference(tx, foreignKey, objID, objType); err != nil {
			return err
		}
	}
	return nil
}

// processRelationshipTaggedFieldsBeforeDelete blocks deletion when any
// blocking attached object reference targets this row, then cascade-deletes
// outgoing references where this row is the attached object.
func processRelationshipTaggedFieldsBeforeDelete(tx *gorm.DB, obj interface{}) error {
	objType := util.ObjectTypeName(obj)
	objID := util.ObjectID(obj)
	if objID == nil {
		return nil
	}

	blockingRefs, err := FindBlockingAttachedObjectReferences(tx, objType, objID)
	if err != nil {
		return err
	}
	if len(blockingRefs) > 0 {
		return util.NewConflictError(
			FormatBlockingAttachedObjectReferencesError(blockingRefs).Error(),
		)
	}

	if err := tx.
		Where("attached_object_type = ? AND attached_object_id = ?", objType, objID).
		Delete(&AttachedObjectReference{}).Error; err != nil {
		return fmt.Errorf(
			"failed to clean up outgoing attached object references for %s/%d: %w",
			objType, *objID, err,
		)
	}
	return nil
}
