// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"encoding/json"
	"fmt"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"time"
)

const (
	ObjectTypeSecretDefinition string = "SecretDefinition"
	ObjectTypeSecretInstance   string = "SecretInstance"

	PathSecretDefinitionVersions = "/secret-definitions/versions"
	PathSecretDefinitions        = "/v0/secret-definitions"
	PathSecretInstanceVersions   = "/secret-instances/versions"
	PathSecretInstances          = "/v0/secret-instances"
)

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (sd *SecretDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        sd,
		ObjectVersion: sd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", sd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (sd *SecretDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &sd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (sd *SecretDefinition) GetId() uint {
	return *sd.ID
}

// GetType returns the object type.
func (sd *SecretDefinition) GetType() string {
	return "SecretDefinition"
}

// GetVersion returns the version of the API object.
func (sd *SecretDefinition) GetVersion() string {
	return "v0"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (sd *SecretDefinition) ScheduledForDeletion() *time.Time {
	return sd.DeletionScheduled
}

// ForeignKeys returns the relationship-tagged foreign keys on SecretDefinition.
func (s *SecretDefinition) ForeignKeys() []ForeignKey {
	return []ForeignKey{{
		FieldName:    "AwsProviderID",
		ObjectID:     s.AwsProviderID,
		ObjectType:   util.ObjectTypeName(AwsProvider{}),
		Relationship: RelationshipRequires,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (si *SecretInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        si,
		ObjectVersion: si.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", si, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (si *SecretInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &si); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (si *SecretInstance) GetId() uint {
	return *si.ID
}

// GetType returns the object type.
func (si *SecretInstance) GetType() string {
	return "SecretInstance"
}

// GetVersion returns the version of the API object.
func (si *SecretInstance) GetVersion() string {
	return "v0"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (si *SecretInstance) ScheduledForDeletion() *time.Time {
	return si.DeletionScheduled
}

// ForeignKeys returns the relationship-tagged foreign keys on SecretInstance.
func (s *SecretInstance) ForeignKeys() []ForeignKey {
	return []ForeignKey{{
		FieldName:    "HelmWorkloadInstanceID",
		ObjectID:     s.HelmWorkloadInstanceID,
		ObjectType:   util.ObjectTypeName(HelmWorkloadInstance{}),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     s.KubernetesRuntimeInstanceID,
		ObjectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "SecretDefinitionID",
		ObjectID:     s.SecretDefinitionID,
		ObjectType:   util.ObjectTypeName(SecretDefinition{}),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "WorkloadInstanceID",
		ObjectID:     s.WorkloadInstanceID,
		ObjectType:   util.ObjectTypeName(WorkloadInstance{}),
		Relationship: RelationshipRequires,
	}}
}
