// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on TerraformInstance.
func (t *TerraformInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "AwsProviderID",
		objectID:     t.AwsProviderID,
		objectType:   util.ObjectTypeName(AwsProvider{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "TerraformDefinitionID",
		objectID:     t.TerraformDefinitionID,
		objectType:   util.ObjectTypeName(TerraformDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}
