// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"gorm.io/gorm"
)

// beforeCreate validates the TerraformDefinition before create.
func (t *TerraformDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the TerraformDefinition before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName") — works under both PATCH
//     and PUT; handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx, t) — values being written
//   - lib.IsFullReplace(tx, t) — true for PUT, false for PATCH
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (t *TerraformDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the TerraformDefinition before delete.
func (t *TerraformDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the TerraformInstance before create.
func (t *TerraformInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate validates the TerraformInstance before update.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - lib.IsFieldChanged(tx, "FieldName") — works under both PATCH
//     and PUT; handles the DB load internally
// Lower-level helpers, useful when IsFieldChanged doesn't fit:
//   - lib.IncomingValues(tx, t) — values being written
//   - lib.IsFullReplace(tx, t) — true for PUT, false for PATCH
// Import:
//   lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (t *TerraformInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete validates the TerraformInstance before delete.
func (t *TerraformInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the TerraformDefinition is created.
func (t *TerraformDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the TerraformDefinition is updated.
func (t *TerraformDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the TerraformDefinition is deleted.
func (t *TerraformDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the TerraformInstance is created.
func (t *TerraformInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the TerraformInstance is updated.
func (t *TerraformInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the TerraformInstance is deleted.
func (t *TerraformInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
