// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

func init() {
	RegisterTypeFactory("v0.AttachedObjectReference", func() interface{} {
		return &AttachedObjectReference{}
	})
	RegisterTypeFactory("v0.AwsEksKubernetesRuntimeDefinition", func() interface{} {
		return &AwsEksKubernetesRuntimeDefinition{}
	})
	RegisterTypeFactory("v0.AwsEksKubernetesRuntimeInstance", func() interface{} {
		return &AwsEksKubernetesRuntimeInstance{}
	})
	RegisterTypeFactory("v0.AwsProvider", func() interface{} {
		return &AwsProvider{}
	})
	RegisterTypeFactory("v0.ControlPlaneComponent", func() interface{} {
		return &ControlPlaneComponent{}
	})
	RegisterTypeFactory("v0.KubernetesRuntimeDefinition", func() interface{} {
		return &KubernetesRuntimeDefinition{}
	})
	RegisterTypeFactory("v0.KubernetesRuntimeInstance", func() interface{} {
		return &KubernetesRuntimeInstance{}
	})
	RegisterTypeFactory("v0.Definition", func() interface{} {
		return &Definition{}
	})
	RegisterTypeFactory("v0.DomainNameDefinition", func() interface{} {
		return &DomainNameDefinition{}
	})
	RegisterTypeFactory("v0.DomainNameInstance", func() interface{} {
		return &DomainNameInstance{}
	})
	RegisterTypeFactory("v0.Event", func() interface{} {
		return &Event{}
	})
	RegisterTypeFactory("v0.GatewayDefinition", func() interface{} {
		return &GatewayDefinition{}
	})
	RegisterTypeFactory("v0.GatewayHttpPort", func() interface{} {
		return &GatewayHttpPort{}
	})
	RegisterTypeFactory("v0.GatewayInstance", func() interface{} {
		return &GatewayInstance{}
	})
	RegisterTypeFactory("v0.GatewayTcpPort", func() interface{} {
		return &GatewayTcpPort{}
	})
	RegisterTypeFactory("v0.GcpGkeKubernetesRuntimeDefinition", func() interface{} {
		return &GcpGkeKubernetesRuntimeDefinition{}
	})
	RegisterTypeFactory("v0.GcpGkeKubernetesRuntimeInstance", func() interface{} {
		return &GcpGkeKubernetesRuntimeInstance{}
	})
	RegisterTypeFactory("v0.GcpProvider", func() interface{} {
		return &GcpProvider{}
	})
	RegisterTypeFactory("v0.HelmWorkloadDefinition", func() interface{} {
		return &HelmWorkloadDefinition{}
	})
	RegisterTypeFactory("v0.HelmWorkloadInstance", func() interface{} {
		return &HelmWorkloadInstance{}
	})
	RegisterTypeFactory("v0.Instance", func() interface{} {
		return &Instance{}
	})
	RegisterTypeFactory("v0.ControlPlaneDefinition", func() interface{} {
		return &ControlPlaneDefinition{}
	})
	RegisterTypeFactory("v0.ControlPlaneInstance", func() interface{} {
		return &ControlPlaneInstance{}
	})
	RegisterTypeFactory("v0.LogBackend", func() interface{} {
		return &LogBackend{}
	})
	RegisterTypeFactory("v0.LogStorageDefinition", func() interface{} {
		return &LogStorageDefinition{}
	})
	RegisterTypeFactory("v0.LogStorageInstance", func() interface{} {
		return &LogStorageInstance{}
	})
	RegisterTypeFactory("v0.LoggingDefinition", func() interface{} {
		return &LoggingDefinition{}
	})
	RegisterTypeFactory("v0.LoggingInstance", func() interface{} {
		return &LoggingInstance{}
	})
	RegisterTypeFactory("v0.MetricsDefinition", func() interface{} {
		return &MetricsDefinition{}
	})
	RegisterTypeFactory("v0.MetricsInstance", func() interface{} {
		return &MetricsInstance{}
	})
	RegisterTypeFactory("v0.ModuleApi", func() interface{} {
		return &ModuleApi{}
	})
	RegisterTypeFactory("v0.ModuleApiRoute", func() interface{} {
		return &ModuleApiRoute{}
	})
	RegisterTypeFactory("v0.ModuleController", func() interface{} {
		return &ModuleController{}
	})
	RegisterTypeFactory("v0.ModuleObject", func() interface{} {
		return &ModuleObject{}
	})
	RegisterTypeFactory("v0.ObservabilityDashboardDefinition", func() interface{} {
		return &ObservabilityDashboardDefinition{}
	})
	RegisterTypeFactory("v0.ObservabilityDashboardInstance", func() interface{} {
		return &ObservabilityDashboardInstance{}
	})
	RegisterTypeFactory("v0.ObservabilityStackDefinition", func() interface{} {
		return &ObservabilityStackDefinition{}
	})
	RegisterTypeFactory("v0.ObservabilityStackInstance", func() interface{} {
		return &ObservabilityStackInstance{}
	})
	RegisterTypeFactory("v0.OciOkeKubernetesRuntimeDefinition", func() interface{} {
		return &OciOkeKubernetesRuntimeDefinition{}
	})
	RegisterTypeFactory("v0.OciOkeKubernetesRuntimeInstance", func() interface{} {
		return &OciOkeKubernetesRuntimeInstance{}
	})
	RegisterTypeFactory("v0.OciProvider", func() interface{} {
		return &OciProvider{}
	})
	RegisterTypeFactory("v0.Profile", func() interface{} {
		return &Profile{}
	})
	RegisterTypeFactory("v0.SecretDefinition", func() interface{} {
		return &SecretDefinition{}
	})
	RegisterTypeFactory("v0.SecretInstance", func() interface{} {
		return &SecretInstance{}
	})
	RegisterTypeFactory("v0.TerraformDefinition", func() interface{} {
		return &TerraformDefinition{}
	})
	RegisterTypeFactory("v0.TerraformInstance", func() interface{} {
		return &TerraformInstance{}
	})
	RegisterTypeFactory("v0.Tier", func() interface{} {
		return &Tier{}
	})
	RegisterTypeFactory("v0.WorkloadDefinition", func() interface{} {
		return &WorkloadDefinition{}
	})
	RegisterTypeFactory("v0.WorkloadEvent", func() interface{} {
		return &WorkloadEvent{}
	})
	RegisterTypeFactory("v0.WorkloadInstance", func() interface{} {
		return &WorkloadInstance{}
	})
	RegisterTypeFactory("v0.WorkloadResourceDefinition", func() interface{} {
		return &WorkloadResourceDefinition{}
	})
	RegisterTypeFactory("v0.WorkloadResourceInstance", func() interface{} {
		return &WorkloadResourceInstance{}
	})
}
