// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// RelationshipForeignKeys returns the relationship-tagged foreign keys on WorkloadInstance.
func (w *WorkloadInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "KubernetesRuntimeInstanceID",
		objectID:     w.KubernetesRuntimeInstanceID,
		objectType:   util.ObjectTypeName(KubernetesRuntimeInstance{}),
		relationship: sdk.RelationshipRequires,
	}, {
		fieldName:    "WorkloadDefinitionID",
		objectID:     w.WorkloadDefinitionID,
		objectType:   util.ObjectTypeName(WorkloadDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on WorkloadResourceDefinition.
func (w *WorkloadResourceDefinition) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "WorkloadDefinitionID",
		objectID:     w.WorkloadDefinitionID,
		objectType:   util.ObjectTypeName(WorkloadDefinition{}),
		relationship: sdk.RelationshipRequires,
	}}
}

// RelationshipForeignKeys returns the relationship-tagged foreign keys on WorkloadResourceInstance.
func (w *WorkloadResourceInstance) RelationshipForeignKeys() []relationshipForeignKey {
	return []relationshipForeignKey{{
		fieldName:    "WorkloadInstanceID",
		objectID:     w.WorkloadInstanceID,
		objectType:   util.ObjectTypeName(WorkloadInstance{}),
		relationship: sdk.RelationshipRequires,
	}}
}
