// boilerplate generated by 'threeport-sdk gen' - do not edit

<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
package machineworkload
========
package kubernetesworkload
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go

import (
	"errors"
	"fmt"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
// MachineWorkloadInstanceReconciler reconciles system state when a MachineWorkloadInstance
// is created, updated or deleted.
func MachineWorkloadInstanceReconciler(r *controller.Reconciler) {
========
// KubernetesWorkloadInstanceReconciler reconciles system state when a KubernetesWorkloadInstance
// is created, updated or deleted.
func KubernetesWorkloadInstanceReconciler(r *controller.Reconciler) {
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
	r.ShutdownWait.Add(1)
	reconcilerLog := r.Log.WithValues("reconcilerName", r.Name)
	reconcilerLog.Info("reconciler started")
	shutdown := false

	// create a channel to receive OS signals
	osSignals := make(chan os.Signal, 1)
	lockReleased := make(chan bool, 1)

	// register the os signals channel to receive SIGINT and SIGTERM signals
	signal.Notify(osSignals, syscall.SIGINT, syscall.SIGTERM)

	for {
		// create a fresh log object per reconciliation loop so we don't
		// accumulate values across multiple loops
		log := r.Log.WithValues("reconcilerName", r.Name)

		if shutdown {
			break
		}

		// check for shutdown instruction
		select {
		case <-r.Shutdown:
			shutdown = true
		default:
			// pull message off queue
			msg := r.PullMessage()
			if msg == nil {
				continue
			}

			// consume message data to capture notification from API
			notif, err := notifications.ConsumeMessage(msg.Data)
			if err != nil {
				log.Error(
					err, "failed to consume message data from NATS",
					"msgData", string(msg.Data),
				)
				r.RequeueRaw(msg)
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				log.V(1).Info("machine workload instance reconciliation requeued with identical payload and fixed delay")
========
				log.V(1).Info("kubernetes workload instance reconciliation requeued with identical payload and fixed delay")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				continue
			}

			// determine the correct object version from the notification
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
			var machineWorkloadInstance tpapi_lib.ReconciledThreeportApiObject
			switch notif.ObjectVersion {
			case "v0":
				machineWorkloadInstance = &api_v0.MachineWorkloadInstance{}
			default:
				log.Error(errors.New("received unrecognized version of machine workload instance object"), "")
				r.RequeueRaw(msg)
				log.V(1).Info("machine workload instance reconciliation requeued with identical payload and fixed delay")
========
			var kubernetesWorkloadInstance tpapi_lib.ReconciledThreeportApiObject
			switch notif.ObjectVersion {
			case "v0":
				kubernetesWorkloadInstance = &api_v0.KubernetesWorkloadInstance{}
			default:
				log.Error(errors.New("received unrecognized version of kubernetes workload instance object"), "")
				r.RequeueRaw(msg)
				log.V(1).Info("kubernetes workload instance reconciliation requeued with identical payload and fixed delay")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				continue
			}

			// decode the object that was sent in the notification
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
			if err := machineWorkloadInstance.DecodeNotifObject(notif.Object); err != nil {
				log.Error(err, "failed to marshal object map from consumed notification message")
				r.RequeueRaw(msg)
				log.V(1).Info("machine workload instance reconciliation requeued with identical payload and fixed delay")
				continue
			}
			log = log.WithValues("machineWorkloadInstanceID", machineWorkloadInstance.GetId())
========
			if err := kubernetesWorkloadInstance.DecodeNotifObject(notif.Object); err != nil {
				log.Error(err, "failed to marshal object map from consumed notification message")
				r.RequeueRaw(msg)
				log.V(1).Info("kubernetes workload instance reconciliation requeued with identical payload and fixed delay")
				continue
			}
			log = log.WithValues("kubernetesWorkloadInstanceID", kubernetesWorkloadInstance.GetId())
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go

			// back off the requeue delay as needed
			requeueDelay := controller.SetRequeueDelay(
				notif.CreationTime,
			)

			// check for lock on object
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
			locked, ok := r.CheckLock(machineWorkloadInstance)
			if locked || ok == false {
				r.Requeue(machineWorkloadInstance, requeueDelay, msg)
				log.V(1).Info("machine workload instance reconciliation requeued")
========
			locked, ok := r.CheckLock(kubernetesWorkloadInstance)
			if locked || ok == false {
				r.Requeue(kubernetesWorkloadInstance, requeueDelay, msg)
				log.V(1).Info("kubernetes workload instance reconciliation requeued")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				continue
			}

			// set up handler to unlock and requeue on termination signal
			go func() {
				select {
				case <-osSignals:
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
					log.V(1).Info("received termination signal, performing unlock and requeue of machine workload instance")
					r.UnlockAndRequeue(machineWorkloadInstance, requeueDelay, lockReleased, msg)
				case <-lockReleased:
					log.V(1).Info("reached end of reconcile loop for machine workload instance, closing out signal handler")
========
					log.V(1).Info("received termination signal, performing unlock and requeue of kubernetes workload instance")
					r.UnlockAndRequeue(kubernetesWorkloadInstance, requeueDelay, lockReleased, msg)
				case <-lockReleased:
					log.V(1).Info("reached end of reconcile loop for kubernetes workload instance, closing out signal handler")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				}
			}()

			// put a lock on the reconciliation of the created object
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
			if ok := r.Lock(machineWorkloadInstance); !ok {
				r.Requeue(machineWorkloadInstance, requeueDelay, msg)
				log.V(1).Info("machine workload instance reconciliation requeued")
========
			if ok := r.Lock(kubernetesWorkloadInstance); !ok {
				r.Requeue(kubernetesWorkloadInstance, requeueDelay, msg)
				log.V(1).Info("kubernetes workload instance reconciliation requeued")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				continue
			}

			// retrieve latest version of object
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
			var latestMachineWorkloadInstance tpapi_lib.ReconciledThreeportApiObject
			var getLatestErr error
			switch notif.ObjectVersion {
			case "v0":
				latestObject, err := client_v0.GetMachineWorkloadInstanceByID(
					r.APIClient,
					r.APIServer,
					machineWorkloadInstance.GetId(),
				)
				latestMachineWorkloadInstance = latestObject
				getLatestErr = err
			default:
				getLatestErr = errors.New("received unrecognized version of machine workload instance object")
========
			var latestKubernetesWorkloadInstance tpapi_lib.ReconciledThreeportApiObject
			var getLatestErr error
			switch notif.ObjectVersion {
			case "v0":
				latestObject, err := client_v0.GetKubernetesWorkloadInstanceByID(
					r.APIClient,
					r.APIServer,
					kubernetesWorkloadInstance.GetId(),
				)
				latestKubernetesWorkloadInstance = latestObject
				getLatestErr = err
			default:
				getLatestErr = errors.New("received unrecognized version of kubernetes workload instance object")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
			}

			// check if error is 404 - if object no longer exists, no need to requeue
			if errors.Is(getLatestErr, tpclient_lib.ErrObjectNotFound) {
				log.Info("object no longer exists - halting reconciliation")
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				r.ReleaseLock(machineWorkloadInstance, lockReleased, msg, true)
				continue
			}
			if getLatestErr != nil {
				log.Error(getLatestErr, "failed to get machine workload instance by ID from API")
				r.UnlockAndRequeue(machineWorkloadInstance, requeueDelay, lockReleased, msg)
				continue
			}
			machineWorkloadInstance = latestMachineWorkloadInstance
========
				r.ReleaseLock(kubernetesWorkloadInstance, lockReleased, msg, true)
				continue
			}
			if getLatestErr != nil {
				log.Error(getLatestErr, "failed to get kubernetes workload instance by ID from API")
				r.UnlockAndRequeue(kubernetesWorkloadInstance, requeueDelay, lockReleased, msg)
				continue
			}
			kubernetesWorkloadInstance = latestKubernetesWorkloadInstance
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go

			// determine which operation and act accordingly
			switch notif.Operation {
			case notifications.NotificationOperationCreated:
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				if machineWorkloadInstance.ScheduledForDeletion() != nil {
					log.Info("machine workload instance scheduled for deletion - skipping create")
========
				if kubernetesWorkloadInstance.ScheduledForDeletion() != nil {
					log.Info("kubernetes workload instance scheduled for deletion - skipping create")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					break
				}
				var operationErr error
				var customRequeueDelay int64
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				switch machineWorkloadInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0MachineWorkloadInstanceCreated(
						r,
						machineWorkloadInstance.(*api_v0.MachineWorkloadInstance),
========
				switch kubernetesWorkloadInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0KubernetesWorkloadInstanceCreated(
						r,
						kubernetesWorkloadInstance.(*api_v0.KubernetesWorkloadInstance),
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
					operationErr = errors.New("unrecognized version of machine workload instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile created machine workload instance object"
========
					operationErr = errors.New("unrecognized version of kubernetes workload instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile created kubernetes workload instance object"
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&api_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedCreate),
							Type:   util.Ptr(event.TypeNormal),
						},
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance.GetId(),
						machineWorkloadInstance.GetFullyQualifiedType(),
========
						kubernetesWorkloadInstance.GetId(),
						kubernetesWorkloadInstance.GetFullyQualifiedType(),
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance,
========
						kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("create requeued for future reconciliation")
					r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance,
========
						kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationUpdated:
				var operationErr error
				var customRequeueDelay int64
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				switch machineWorkloadInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0MachineWorkloadInstanceUpdated(
						r,
						machineWorkloadInstance.(*api_v0.MachineWorkloadInstance),
========
				switch kubernetesWorkloadInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0KubernetesWorkloadInstanceUpdated(
						r,
						kubernetesWorkloadInstance.(*api_v0.KubernetesWorkloadInstance),
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
					operationErr = errors.New("unrecognized version of machine workload instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile updated machine workload instance object"
========
					operationErr = errors.New("unrecognized version of kubernetes workload instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile updated kubernetes workload instance object"
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&api_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedUpdate),
							Type:   util.Ptr(event.TypeNormal),
						},
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance.GetId(),
						machineWorkloadInstance.GetFullyQualifiedType(),
========
						kubernetesWorkloadInstance.GetId(),
						kubernetesWorkloadInstance.GetFullyQualifiedType(),
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance,
========
						kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("update requeued for future reconciliation")
					r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance,
========
						kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationDeleted:
				var operationErr error
				var customRequeueDelay int64
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				switch machineWorkloadInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0MachineWorkloadInstanceDeleted(
						r,
						machineWorkloadInstance.(*api_v0.MachineWorkloadInstance),
========
				switch kubernetesWorkloadInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0KubernetesWorkloadInstanceDeleted(
						r,
						kubernetesWorkloadInstance.(*api_v0.KubernetesWorkloadInstance),
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
					operationErr = errors.New("unrecognized version of machine workload instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile deleted machine workload instance object"
========
					operationErr = errors.New("unrecognized version of kubernetes workload instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile deleted kubernetes workload instance object"
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&api_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedDelete),
							Type:   util.Ptr(event.TypeNormal),
						},
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance.GetId(),
						machineWorkloadInstance.GetFullyQualifiedType(),
========
						kubernetesWorkloadInstance.GetId(),
						kubernetesWorkloadInstance.GetFullyQualifiedType(),
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance,
========
						kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("delete requeued for future reconciliation")
					r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
						machineWorkloadInstance,
========
						kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				deletionTimestamp := util.Ptr(time.Now().UTC())
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				deletedMachineWorkloadInstance := api_v0.MachineWorkloadInstance{
					Common: api_v0.Common{ID: util.Ptr(machineWorkloadInstance.GetId())},
========
				deletedKubernetesWorkloadInstance := api_v0.KubernetesWorkloadInstance{
					Common: api_v0.Common{ID: util.Ptr(kubernetesWorkloadInstance.GetId())},
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					Reconciliation: api_v0.Reconciliation{
						DeletionAcknowledged: deletionTimestamp,
						DeletionConfirmed:    deletionTimestamp,
						Reconciled:           util.Ptr(true),
					},
				}
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				_, err = client_v0.UpdateMachineWorkloadInstance(
					r.APIClient,
					r.APIServer,
					&deletedMachineWorkloadInstance,
				)
				if err != nil {
					log.Error(err, "failed to update machine workload instance to mark as deleted")
					r.UnlockAndRequeue(machineWorkloadInstance, requeueDelay, lockReleased, msg)
					continue
				}
				_, err = client_v0.DeleteMachineWorkloadInstance(
					r.APIClient,
					r.APIServer,
					machineWorkloadInstance.GetId(),
				)
				if err != nil {
					log.Error(err, "failed to delete machine workload instance")
					r.UnlockAndRequeue(machineWorkloadInstance, requeueDelay, lockReleased, msg)
========
				_, err = client_v0.UpdateKubernetesWorkloadInstance(
					r.APIClient,
					r.APIServer,
					&deletedKubernetesWorkloadInstance,
				)
				if err != nil {
					log.Error(err, "failed to update kubernetes workload instance to mark as deleted")
					r.UnlockAndRequeue(kubernetesWorkloadInstance, requeueDelay, lockReleased, msg)
					continue
				}
				_, err = client_v0.DeleteKubernetesWorkloadInstance(
					r.APIClient,
					r.APIServer,
					kubernetesWorkloadInstance.GetId(),
				)
				if err != nil {
					log.Error(err, "failed to delete kubernetes workload instance")
					r.UnlockAndRequeue(kubernetesWorkloadInstance, requeueDelay, lockReleased, msg)
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					continue
				}
			default:
				log.Error(
					errors.New("unrecognized notifcation operation"),
					"notification included an invalid operation",
				)
				r.UnlockAndRequeue(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
					machineWorkloadInstance,
========
					kubernetesWorkloadInstance,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
					requeueDelay,
					lockReleased,
					msg,
				)
				continue
			}

			// set the object's Reconciled field to true if not deleted
			if notif.Operation != notifications.NotificationOperationDeleted {
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				reconciledMachineWorkloadInstance := api_v0.MachineWorkloadInstance{
					Common:         api_v0.Common{ID: util.Ptr(machineWorkloadInstance.GetId())},
					Reconciliation: api_v0.Reconciliation{Reconciled: util.Ptr(true)},
				}
				updatedMachineWorkloadInstance, err := client_v0.UpdateMachineWorkloadInstance(
					r.APIClient,
					r.APIServer,
					&reconciledMachineWorkloadInstance,
				)
				if err != nil {
					log.Error(err, "failed to update machine workload instance to mark as reconciled")
					r.UnlockAndRequeue(machineWorkloadInstance, requeueDelay, lockReleased, msg)
					continue
				}
				log.V(1).Info(
					"machine workload instance marked as reconciled in API",
					"machine workload instanceName", updatedMachineWorkloadInstance.Name,
========
				reconciledKubernetesWorkloadInstance := api_v0.KubernetesWorkloadInstance{
					Common:         api_v0.Common{ID: util.Ptr(kubernetesWorkloadInstance.GetId())},
					Reconciliation: api_v0.Reconciliation{Reconciled: util.Ptr(true)},
				}
				updatedKubernetesWorkloadInstance, err := client_v0.UpdateKubernetesWorkloadInstance(
					r.APIClient,
					r.APIServer,
					&reconciledKubernetesWorkloadInstance,
				)
				if err != nil {
					log.Error(err, "failed to update kubernetes workload instance to mark as reconciled")
					r.UnlockAndRequeue(kubernetesWorkloadInstance, requeueDelay, lockReleased, msg)
					continue
				}
				log.V(1).Info(
					"kubernetes workload instance marked as reconciled in API",
					"kubernetes workload instanceName", updatedKubernetesWorkloadInstance.Name,
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				)
			}

			// release the lock on the reconciliation of the created object
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
			if ok := r.ReleaseLock(machineWorkloadInstance, lockReleased, msg, true); !ok {
				log.Error(errors.New("machine workload instance remains locked - will unlock when TTL expires"), "")
			} else {
				log.V(1).Info("machine workload instance unlocked")
========
			if ok := r.ReleaseLock(kubernetesWorkloadInstance, lockReleased, msg, true); !ok {
				log.Error(errors.New("kubernetes workload instance remains locked - will unlock when TTL expires"), "")
			} else {
				log.V(1).Info("kubernetes workload instance unlocked")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
			}

			// log and record event for successful reconciliation
			successMsg := fmt.Sprintf(
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				"machine workload instance successfully reconciled for %s operation",
========
				"kubernetes workload instance successfully reconciled for %s operation",
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
				strings.ToLower(string(notif.Operation)),
			)
			if err := r.EventsRecorder.RecordEvent(
				&api_v0.Event{
					Note:   util.Ptr(successMsg),
					Reason: util.Ptr(event.GetSuccessReasonForOperation(notif.Operation)),
					Type:   util.Ptr(event.TypeNormal),
				},
<<<<<<<< HEAD:internal/machine-workload/machine_workload_instance_reconciler_gen.go
				machineWorkloadInstance.GetId(),
				machineWorkloadInstance.GetFullyQualifiedType(),
			); err != nil {
				log.Error(err, "failed to record event for successful machine workload instance reconciliation")
========
				kubernetesWorkloadInstance.GetId(),
				kubernetesWorkloadInstance.GetFullyQualifiedType(),
			); err != nil {
				log.Error(err, "failed to record event for successful kubernetes workload instance reconciliation")
>>>>>>>> refactor-rename-workload-to-kubernetes-workload:internal/kubernetes-workload/kubernetes_workload_instance_reconciler_gen.go
			}
			log.Info(successMsg)
		}
	}

	r.Sub.Unsubscribe()
	reconcilerLog.Info("reconciler shutting down")
	r.ShutdownWait.Done()
}
