// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package machineworkload

import (
	"fmt"

	logr "github.com/go-logr/logr"

	status "github.com/threeport/threeport/internal/workload/status"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	client "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	machine "github.com/threeport/threeport/pkg/machine/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

const (
	// defaultShell is used when the MachineWorkloadDefinition does not specify a shell.
	defaultShell = "/bin/bash"

	// maxEventMessageChars caps the size of a WorkloadEvent message so we
	// don't write arbitrarily large rows to the DB when a script emits
	// megabytes of output.
	maxEventMessageChars = 32768
)

// v0MachineWorkloadInstanceCreated performs reconciliation when a v0
// MachineWorkloadInstance has been created.  It resolves the related machine
// runtime and workload definition, opens an SSH connection, executes the
// create script, and records events for the output.
func v0MachineWorkloadInstanceCreated(
	r *controller.Reconciler,
	machineWorkloadInstance *v0.MachineWorkloadInstance,
	log *logr.Logger,
) (int64, error) {
	// get related machine workload definition
	mwd, err := client.GetMachineWorkloadDefinitionByID(
		r.APIClient,
		r.APIServer,
		*machineWorkloadInstance.MachineWorkloadDefinitionID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to get machine workload definition: %w", err)
	}

	// get related machine runtime instance
	mri, err := client.GetMachineRuntimeInstanceByID(
		r.APIClient,
		r.APIServer,
		*machineWorkloadInstance.MachineRuntimeInstanceID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to get machine runtime instance: %w", err)
	}

	// wait for the runtime to be reconciled before running workloads against it
	if mri.Reconciled == nil || !*mri.Reconciled {
		return 30, nil
	}

	// run the create script and record results
	wlStatus := runScript(r, machineWorkloadInstance, mri, mwd, *mwd.CreateScript, "create", log)

	// update the instance with the final status
	if _, err := client.UpdateMachineWorkloadInstance(r.APIClient, r.APIServer, &v0.MachineWorkloadInstance{
		Common: v0.Common{ID: machineWorkloadInstance.ID},
		Status: util.Ptr(string(wlStatus)),
	}); err != nil {
		return 0, fmt.Errorf("failed to update machine workload instance with run result: %w", err)
	}

	// requeue on failure so the script is retried
	if wlStatus != status.WorkloadInstanceStatusHealthy {
		return 0, fmt.Errorf("create script failed with status %s", wlStatus)
	}

	return 0, nil
}

// v0MachineWorkloadInstanceUpdated performs reconciliation when a v0
// MachineWorkloadInstance has been updated.
func v0MachineWorkloadInstanceUpdated(
	r *controller.Reconciler,
	machineWorkloadInstance *v0.MachineWorkloadInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MachineWorkloadInstanceDeleted performs reconciliation when a v0
// MachineWorkloadInstance has been deleted.  It runs the delete script from the
// associated definition before the generated reconciler removes the instance
// from the database.
func v0MachineWorkloadInstanceDeleted(
	r *controller.Reconciler,
	machineWorkloadInstance *v0.MachineWorkloadInstance,
	log *logr.Logger,
) (int64, error) {
	// get related machine workload definition
	mwd, err := client.GetMachineWorkloadDefinitionByID(
		r.APIClient,
		r.APIServer,
		*machineWorkloadInstance.MachineWorkloadDefinitionID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to get machine workload definition: %w", err)
	}

	// get related machine runtime instance
	mri, err := client.GetMachineRuntimeInstanceByID(
		r.APIClient,
		r.APIServer,
		*machineWorkloadInstance.MachineRuntimeInstanceID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to get machine runtime instance: %w", err)
	}

	// run the delete script and record results
	wlStatus := runScript(r, machineWorkloadInstance, mri, mwd, *mwd.DeleteScript, "delete", log)

	// requeue on failure so the script is retried
	if wlStatus != status.WorkloadInstanceStatusHealthy {
		return 0, fmt.Errorf("delete script failed with status %s", wlStatus)
	}

	return 0, nil
}

// runScript establishes an SSH connection to the machine runtime, executes the
// given script, and records WorkloadEvent records for the captured output and
// exit status.  Returns the derived workload instance status.
func runScript(
	r *controller.Reconciler,
	mwi *v0.MachineWorkloadInstance,
	mri *v0.MachineRuntimeInstance,
	mwd *v0.MachineWorkloadDefinition,
	script string,
	scriptName string,
	log *logr.Logger,
) status.WorkloadInstanceStatus {
	// establish ssh connection to the runtime
	sshClient, _, err := machine.GetClient(mri, r.EncryptionKey)
	if err != nil {
		// ssh failure is user-visible — the machine isn't reachable
		if eventErr := r.EventsRecorder.RecordEvent(
			&v0.Event{
				Type:   util.Ptr(event.TypeWarning),
				Reason: util.Ptr("SSHConnectFailed"),
				Note:   util.Ptr(fmt.Sprintf("failed to connect to machine runtime instance: %s", err)),
			},
			*mwi.ID,
			"v0",
			util.TypeName(v0.MachineWorkloadInstance{}),
		); eventErr != nil {
			log.Error(eventErr, "failed to record event for ssh connect error")
		}
		return status.WorkloadInstanceStatusError
	}
	defer sshClient.Close()

	// decrypt env from definition and instance
	defEnv, err := machine.DecryptEnv(mwd.Env, r.EncryptionKey)
	if err != nil {
		log.Error(err, "failed to decrypt definition env")
		return status.WorkloadInstanceStatusError
	}
	instEnv, err := machine.DecryptEnv(mwi.Env, r.EncryptionKey)
	if err != nil {
		log.Error(err, "failed to decrypt instance env")
		return status.WorkloadInstanceStatusError
	}

	// merge env - instance env overrides definition env on duplicate keys
	effectiveEnv := machine.MergeEnv(defEnv, instEnv)

	// resolve shell and working dir defaults
	shell := util.DerefString(mwd.Shell)
	if shell == "" {
		shell = defaultShell
	}
	workDir := util.DerefString(mwd.WorkingDir)

	// run the script on the remote machine
	stdout, stderr, exitCode, timedOut, runErr := machine.RunScript(
		sshClient,
		script,
		shell,
		workDir,
		effectiveEnv,
		mwd.Timeout,
	)

	// derive status and record events based on execution result
	var wlStatus status.WorkloadInstanceStatus
	var reason, eventType, message string
	switch {
	case timedOut:
		wlStatus = status.WorkloadInstanceStatusDown
		reason = "ScriptTimedOut"
		eventType = event.TypeWarning
		message = fmt.Sprintf("%s script timed out (stderr: %s)", scriptName, truncateMessage(stderr))
	case runErr != nil:
		wlStatus = status.WorkloadInstanceStatusError
		reason = "ScriptFailed"
		eventType = event.TypeWarning
		message = fmt.Sprintf("%s script transport error: %s", scriptName, runErr.Error())
	case exitCode == 0:
		wlStatus = status.WorkloadInstanceStatusHealthy
		reason = "ScriptSucceeded"
		eventType = event.TypeNormal
		message = fmt.Sprintf("%s script completed successfully (stdout: %s)", scriptName, truncateMessage(stdout))
	default:
		wlStatus = status.WorkloadInstanceStatusUnhealthy
		reason = "ScriptFailed"
		eventType = event.TypeWarning
		message = fmt.Sprintf("%s script failed with exit code %d (stderr: %s)", scriptName, exitCode, truncateMessage(stderr))
	}
	if eventErr := r.EventsRecorder.RecordEvent(
		&v0.Event{
			Type:   util.Ptr(eventType),
			Reason: util.Ptr(reason),
			Note:   util.Ptr(truncateMessage(message)),
		},
		*mwi.ID,
		"v0",
		util.TypeName(v0.MachineWorkloadInstance{}),
	); eventErr != nil {
		log.Error(eventErr, "failed to record event")
	}

	return wlStatus
}

// truncateMessage caps a message at maxEventMessageChars characters, appending
// a marker when truncation occurs so readers know the original was longer.
func truncateMessage(msg string) string {
	runes := []rune(msg)
	if len(runes) <= maxEventMessageChars {
		return msg
	}
	return string(runes[:maxEventMessageChars]) + "\n...[truncated]"
}
