// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package machineworkload

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0MachineWorkloadInstanceCreated performs reconciliation when a v0 MachineWorkloadInstance
// has been created.
func v0MachineWorkloadInstanceCreated(
	r *controller.Reconciler,
	machineWorkloadInstance *v0.MachineWorkloadInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MachineWorkloadInstanceUpdated performs reconciliation when a v0 MachineWorkloadInstance
// has been updated.
func v0MachineWorkloadInstanceUpdated(
	r *controller.Reconciler,
	machineWorkloadInstance *v0.MachineWorkloadInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MachineWorkloadInstanceDeleted performs reconciliation when a v0 MachineWorkloadInstance
// has been deleted.
func v0MachineWorkloadInstanceDeleted(
	r *controller.Reconciler,
	machineWorkloadInstance *v0.MachineWorkloadInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
