// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package machineruntime

import (
	"errors"
	"fmt"

	logr "github.com/go-logr/logr"

	"github.com/threeport/threeport/internal/kubernetes-runtime/mapping"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	client_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	client "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	tp_errors "github.com/threeport/threeport/pkg/errors/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	machine "github.com/threeport/threeport/pkg/machine/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// sshRetryDelaySeconds is the requeue delay (in seconds) returned when an
// SSH connect or ping fails. Package-level so tests can override it.
var sshRetryDelaySeconds int64 = 30

// v0MachineRuntimeInstanceCreated performs reconciliation when a v0 MachineRuntimeInstance
// has been created.  It verifies the machine is reachable via SSH and records
// an event reflecting the result.
func v0MachineRuntimeInstanceCreated(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	// load the parent definition early so the emit can name the married kind
	// and the provider create path below can reuse it without a second lookup
	var parentDef *v0.MachineRuntimeDefinition
	if machineRuntimeInstance.MachineRuntimeDefinitionID != nil {
		def, err := client.GetMachineRuntimeDefinitionByID(
			r.APIClient,
			r.APIServer,
			*machineRuntimeInstance.MachineRuntimeDefinitionID,
		)
		if err != nil {
			return 0, fmt.Errorf("failed to get machine runtime definition by ID: %w", err)
		}
		parentDef = def
	}

	// emit a lifecycle marker so operators can see reconcile has begun;
	// dedup collapses repeated emits across requeues into a single row
	var createExtras []string
	if parentDef != nil && parentDef.InfraProvider != nil && *parentDef.InfraProvider != "" {
		if marriedKind := v0.MachineRuntimeMarriedKind(*parentDef.InfraProvider, "instance"); marriedKind != "" {
			createExtras = append(createExtras, marriedKind)
		}
	}
	if recordErr := r.EventsRecorder.RecordEvent(
		&v0.Event{
			Type:   util.Ptr(event.TypeNormal),
			Reason: util.Ptr(event.ReasonCreateInProgress),
			Note:   util.Ptr(event.CreateNote(machineRuntimeInstance, createExtras...)),
		},
		*machineRuntimeInstance.ID,
		machineRuntimeInstance.GetFullyQualifiedType(),
	); recordErr != nil {
		log.Error(recordErr, "failed to record CreateInProgress event")
	}

	// when the instance is provider-provisioned and has no hostname yet, create
	// the married provider instance and requeue so the ssh path below waits for
	// the provider reconciler to write back the hostname
	if parentDef != nil &&
		(machineRuntimeInstance.Hostname == nil || *machineRuntimeInstance.Hostname == "") {
		requeue, err := reconcileProviderInstance(r, machineRuntimeInstance, parentDef, log)
		if err != nil {
			return 0, err
		}
		if requeue != 0 {
			return requeue, nil
		}
	}

	// establish an ssh connection to the machine
	sshClient, capturedHostKey, err := machine.GetClient(machineRuntimeInstance, r.EncryptionKey)
	if err != nil {
		// always retry ssh client failures, since a misconfigured credential
		// or unreachable host may be fixed externally without any change
		// to this object, so reconciliation should keep trying;
		// return an ErrWithEvent so the wrapper substitutes the specific
		// reason for the generic FailedCreate event
		note := fmt.Sprintf("failed to connect to machine runtime instance via ssh: %s", err)
		return sshRetryDelaySeconds, &tp_errors.ErrWithEvent{
			Message: note,
			Event: v0.Event{
				Type:   util.Ptr(event.TypeWarning),
				Reason: util.Ptr("SSHConnectFailed"),
				Note:   util.Ptr(note),
			},
		}
	}
	defer sshClient.Close()

	// save captured host key if this is the first connection; set
	// Reconciled=true on the update so the resulting update
	// notification does not trigger another reconciliation pass
	if capturedHostKey != "" {
		if _, err := client.UpdateMachineRuntimeInstance(r.APIClient, r.APIServer, &v0.MachineRuntimeInstance{
			Common:         v0.Common{ID: machineRuntimeInstance.ID},
			Reconciliation: v0.Reconciliation{Reconciled: util.Ptr(true)},
			HostKey:        &capturedHostKey,
		}); err != nil {
			return controller.RetryOnNetworkErr(err, "failed to save captured host key")
		}
		log.Info(
			"captured ssh host key",
			"machineRuntimeInstance", *machineRuntimeInstance.Name,
			"id", *machineRuntimeInstance.ID,
		)
	}

	// verify the connection is usable
	if err := machine.Ping(sshClient); err != nil {
		// always retry, same reasoning as the GetClient path above;
		// return an ErrWithEvent so the wrapper substitutes the specific
		// reason for the generic FailedCreate event
		note := fmt.Sprintf("failed to ping machine runtime instance: %s", err)
		return sshRetryDelaySeconds, &tp_errors.ErrWithEvent{
			Message: note,
			Event: v0.Event{
				Type:   util.Ptr(event.TypeWarning),
				Reason: util.Ptr("SSHPingFailed"),
				Note:   util.Ptr(note),
			},
		}
	}

	// log successful reachability
	log.Info(
		"machine runtime instance is reachable via ssh",
		"machineRuntimeInstance", *machineRuntimeInstance.Name,
		"id", *machineRuntimeInstance.ID,
	)

	return controller.Done, nil
}

// reconcileProviderInstance creates the married provider machine runtime
// instance for a provider-provisioned machine. It returns a requeue delay once
// the married object exists so the caller waits for the provider reconciler to
// populate the hostname.
func reconcileProviderInstance(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	def *v0.MachineRuntimeDefinition,
	log *logr.Logger,
) (int64, error) {
	// an imported machine has no infra provider, so there is nothing to create
	if def.InfraProvider == nil || *def.InfraProvider == "" {
		return controller.Done, nil
	}

	switch *def.InfraProvider {
	case v0.MachineRuntimeInfraProviderGCE:
		// when the married provider instance already exists, wait for its
		// hostname instead of creating a second one
		existing, err := client.GetGcpGceMachineRuntimeInstancesByQueryString(
			r.APIClient,
			r.APIServer,
			fmt.Sprintf("machineruntimeinstanceid=%d", *machineRuntimeInstance.ID),
		)
		if err != nil {
			return 0, fmt.Errorf("failed to check for existing GCE machine runtime instance: %w", err)
		}
		if len(*existing) > 0 {
			return sshRetryDelaySeconds, nil
		}

		// look up the GCP provider by name or fall back to the default
		var gcpProvider v0.GcpProvider
		if def.InfraProviderAccountName != nil {
			provider, err := client.GetGcpProviderByName(r.APIClient, r.APIServer, *def.InfraProviderAccountName)
			if err != nil {
				return 0, fmt.Errorf("failed to get GCP provider by name: %w", err)
			}
			gcpProvider = *provider
		} else {
			provider, err := client.GetGcpProviderByDefaultProvider(r.APIClient, r.APIServer)
			if err != nil {
				return 0, fmt.Errorf("failed to get GCP provider by default: %w", err)
			}
			gcpProvider = *provider
		}

		// map the abstract location to a GCP region; a GCE VM is zonal, so
		// derive a zone within that region. the mapping keys on the cloud
		// provider token, not the machine runtime infra provider token
		region, err := mapping.GetProviderRegionForLocation(util.GcpProvider, *machineRuntimeInstance.Location)
		if err != nil {
			return 0, fmt.Errorf("failed to map threeport location to GCP region: %w", err)
		}
		zone := region + "-a"

		// fetch the married provider definition
		gcpGceMachineRuntimeDefinitions, err := client.GetGcpGceMachineRuntimeDefinitionsByQueryString(
			r.APIClient,
			r.APIServer,
			fmt.Sprintf("machineruntimedefinitionid=%d", *def.ID),
		)
		if err != nil {
			return 0, fmt.Errorf("failed to get GCE machine runtime definition by machine runtime definition ID: %w", err)
		}
		if len(*gcpGceMachineRuntimeDefinitions) < 1 {
			return 0, fmt.Errorf("no GCE machine runtime definition found for machine runtime definition %d", *def.ID)
		}
		gcpGceMachineRuntimeDefinition := (*gcpGceMachineRuntimeDefinitions)[0]

		// create the married provider instance; leave Reconciled unset so the
		// ssh path requeues until the provider reconciler writes back the host
		gcpGceMachineRuntimeInstance := v0.GcpGceMachineRuntimeInstance{
			Instance: v0.Instance{
				Name: machineRuntimeInstance.Name,
			},
			GcpProviderID:                    gcpProvider.ID,
			Region:                           &region,
			Zone:                             &zone,
			MachineRuntimeInstanceID:         machineRuntimeInstance.ID,
			GcpGceMachineRuntimeDefinitionID: gcpGceMachineRuntimeDefinition.ID,
		}

		// propagate ssh credentials from the abstract instance so the GCE
		// provisioner can authorize the user and inject the key; copy only
		// when present to leave the married columns null otherwise
		if machineRuntimeInstance.SSHUser != nil {
			gcpGceMachineRuntimeInstance.SSHUser = util.Ptr(*machineRuntimeInstance.SSHUser)
		}
		if machineRuntimeInstance.SSHKey != nil {
			gcpGceMachineRuntimeInstance.SSHKey = util.Ptr(*machineRuntimeInstance.SSHKey)
		}
		if _, err := client.CreateGcpGceMachineRuntimeInstance(
			r.APIClient,
			r.APIServer,
			&gcpGceMachineRuntimeInstance,
		); err != nil {
			return 0, fmt.Errorf("failed to create GCE machine runtime instance: %w", err)
		}

		return sshRetryDelaySeconds, nil
	default:
		return 0, fmt.Errorf("infra provider %s not supported", *def.InfraProvider)
	}
}

// v0MachineRuntimeInstanceUpdated performs reconciliation when a v0 MachineRuntimeInstance
// has been updated.
func v0MachineRuntimeInstanceUpdated(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	// emit a lifecycle marker so operators can see reconcile has begun;
	// dedup collapses repeated emits across requeues into a single row
	if recordErr := r.EventsRecorder.RecordEvent(
		&v0.Event{
			Type:   util.Ptr(event.TypeNormal),
			Reason: util.Ptr(event.ReasonUpdateInProgress),
			Note:   util.Ptr(event.UpdateNote()),
		},
		*machineRuntimeInstance.ID,
		machineRuntimeInstance.GetFullyQualifiedType(),
	); recordErr != nil {
		log.Error(recordErr, "failed to record UpdateInProgress event")
	}

	return controller.Done, nil
}

// marriedInstanceKind loads the instance's parent definition and returns the
// concrete married attached-object kind, or "" if the instance has no parent,
// the lookup fails, or the provider is unknown.
func marriedInstanceKind(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
) string {
	if machineRuntimeInstance.MachineRuntimeDefinitionID == nil {
		return ""
	}
	def, err := client.GetMachineRuntimeDefinitionByID(
		r.APIClient,
		r.APIServer,
		*machineRuntimeInstance.MachineRuntimeDefinitionID,
	)
	if err != nil {
		return ""
	}
	if def.InfraProvider == nil || *def.InfraProvider == "" {
		return ""
	}
	return v0.MachineRuntimeMarriedKind(*def.InfraProvider, "instance")
}

// v0MachineRuntimeInstanceDeleted performs reconciliation when a v0 MachineRuntimeInstance
// has been deleted.
func v0MachineRuntimeInstanceDeleted(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	// emit a lifecycle marker so operators can see reconcile has begun;
	// dedup collapses repeated emits across requeues into a single row
	var deleteExtras []string
	if marriedKind := marriedInstanceKind(r, machineRuntimeInstance); marriedKind != "" {
		deleteExtras = append(deleteExtras, marriedKind)
	}
	if recordErr := r.EventsRecorder.RecordEvent(
		&v0.Event{
			Type:   util.Ptr(event.TypeNormal),
			Reason: util.Ptr(event.ReasonDeleteInProgress),
			Note:   util.Ptr(event.DeleteNote(machineRuntimeInstance, deleteExtras...)),
		},
		*machineRuntimeInstance.ID,
		machineRuntimeInstance.GetFullyQualifiedType(),
	); recordErr != nil {
		log.Error(recordErr, "failed to record DeleteInProgress event")
	}

	// fetch married GCE machine runtime instance(s) owned by this MRI
	existing, err := client.GetGcpGceMachineRuntimeInstancesByQueryString(
		r.APIClient,
		r.APIServer,
		fmt.Sprintf("machineruntimeinstanceid=%d", *machineRuntimeInstance.ID),
	)
	if err != nil {
		return 0, fmt.Errorf("failed to list married GCE machine runtime instances: %w", err)
	}

	// nothing left; cascade is complete
	if len(*existing) == 0 {
		return controller.Done, nil
	}

	// issue delete for each; the GCE reconciler runs Pulumi destroy and removes
	// the row when done. skip rows already scheduled for deletion and tolerate
	// not-found so the loop stays idempotent across requeues.
	for _, gceInstance := range *existing {
		if gceInstance.DeletionScheduled != nil {
			continue
		}
		if _, err := client.DeleteGcpGceMachineRuntimeInstance(
			r.APIClient,
			r.APIServer,
			*gceInstance.ID,
		); err != nil && !errors.Is(err, client_lib.ErrObjectNotFound) {
			return 0, fmt.Errorf("failed to delete married GCE machine runtime instance %d: %w", *gceInstance.ID, err)
		}
	}

	// requeue until every married GCE instance has cleared
	return controller.Requeue30s, nil
}
