// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package machineruntime

import (
	"fmt"

	logr "github.com/go-logr/logr"

	v0 "github.com/threeport/threeport/pkg/api/v0"
	client "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	tp_errors "github.com/threeport/threeport/pkg/errors/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	machine "github.com/threeport/threeport/pkg/machine/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// v0MachineRuntimeInstanceCreated performs reconciliation when a v0 MachineRuntimeInstance
// has been created.  It verifies the machine is reachable via SSH and records
// an event reflecting the result.
func v0MachineRuntimeInstanceCreated(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	// establish an ssh connection to the machine
	sshClient, capturedHostKey, err := machine.GetClient(machineRuntimeInstance, r.EncryptionKey)
	if err != nil {
		// always retry ssh client failures, since a misconfigured credential
		// or unreachable host may be fixed externally without any change
		// to this object, so reconciliation should keep trying;
		// return an ErrWithEvent so the wrapper substitutes the specific
		// reason for the generic FailedCreate event
		note := fmt.Sprintf("failed to connect to machine runtime instance via ssh: %s", err)
		return 30, &tp_errors.ErrWithEvent{
			Message: note,
			Event: v0.Event{
				Type:   util.Ptr(event.TypeWarning),
				Reason: util.Ptr("SSHConnectFailed"),
				Note:   util.Ptr(note),
			},
		}
	}
	defer sshClient.Close()

	// save captured host key if this is the first connection; set
	// Reconciled=true on the update so the resulting update
	// notification does not trigger another reconciliation pass
	if capturedHostKey != "" {
		if _, err := client.UpdateMachineRuntimeInstance(r.APIClient, r.APIServer, &v0.MachineRuntimeInstance{
			Common:         v0.Common{ID: machineRuntimeInstance.ID},
			Reconciliation: v0.Reconciliation{Reconciled: util.Ptr(true)},
			HostKey:        &capturedHostKey,
		}); err != nil {
			return controller.RetryOnNetworkErr(err, "failed to save captured host key")
		}
		log.Info(
			"captured ssh host key",
			"machineRuntimeInstance", *machineRuntimeInstance.Name,
			"id", *machineRuntimeInstance.ID,
		)
	}

	// verify the connection is usable
	if err := machine.Ping(sshClient); err != nil {
		// always retry, same reasoning as the GetClient path above;
		// return an ErrWithEvent so the wrapper substitutes the specific
		// reason for the generic FailedCreate event
		note := fmt.Sprintf("failed to ping machine runtime instance: %s", err)
		return 30, &tp_errors.ErrWithEvent{
			Message: note,
			Event: v0.Event{
				Type:   util.Ptr(event.TypeWarning),
				Reason: util.Ptr("SSHPingFailed"),
				Note:   util.Ptr(note),
			},
		}
	}

	// log successful reachability
	log.Info(
		"machine runtime instance is reachable via ssh",
		"machineRuntimeInstance", *machineRuntimeInstance.Name,
		"id", *machineRuntimeInstance.ID,
	)

	return 0, nil
}

// v0MachineRuntimeInstanceUpdated performs reconciliation when a v0 MachineRuntimeInstance
// has been updated.
func v0MachineRuntimeInstanceUpdated(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MachineRuntimeInstanceDeleted performs reconciliation when a v0 MachineRuntimeInstance
// has been deleted.
func v0MachineRuntimeInstanceDeleted(
	r *controller.Reconciler,
	machineRuntimeInstance *v0.MachineRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
