// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package kubernetesworkload

import (
	"errors"
	"fmt"

	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	client "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	kube "github.com/threeport/threeport/pkg/kube/v0"
	"gorm.io/datatypes"
)

// v0KubernetesWorkloadDefinitionCreated performs reconciliation when a v0 kubernetes workload definition
// has been created.
func v0KubernetesWorkloadDefinitionCreated(
	r *controller.Reconciler,
	workloadDefinition *v0.KubernetesWorkloadDefinition,
	log *logr.Logger,
) (int64, error) {
	// parse YAMLDocument and get kube objects in JSON
	jsonObjects, err := kube.GetJsonResourcesFromYamlDoc(*workloadDefinition.YAMLDocument)
	if err != nil {
		return 0, fmt.Errorf("failed to get JSON kube objects from YAML document: %w", err)
	}

	// create kubernetes workload resource definition objects
	var workloadResourceDefinitions []v0.KubernetesWorkloadResourceDefinition
	for _, jsonContent := range jsonObjects {
		// unmarshal the json into the type used by API
		var jsonDefinition datatypes.JSON
		if err := jsonDefinition.UnmarshalJSON(jsonContent); err != nil {
			return 0, fmt.Errorf("failed to unmarshal json to datatypes.JSON: %w", err)
		}

		// build the kubernetes workload resource definition and marshal to json
		workloadResourceDefinition := v0.KubernetesWorkloadResourceDefinition{
			JSONDefinition:                 &jsonDefinition,
			KubernetesWorkloadDefinitionID: workloadDefinition.ID,
		}
		workloadResourceDefinitions = append(workloadResourceDefinitions, workloadResourceDefinition)
	}

	// create kubernetes workload resource definitions in API
	createdWRDs, err := client.CreateKubernetesWorkloadResourceDefinitions(
		r.APIClient,
		r.APIServer,
		&workloadResourceDefinitions,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to create kubernetes workload resource definitions in API: %w", err)
	}

	for _, wrd := range *createdWRDs {
		log.V(1).Info(
			"kubernetes workload resource definition created",
			"kubernetesWorkloadResourceDefinitionID", wrd.ID,
		)
	}

	return 0, nil
}

// v0KubernetesWorkloadDefinitionUpdated performs reconciliation when a v0 kubernetes workload definition
// has been updated.
func v0KubernetesWorkloadDefinitionUpdated(
	r *controller.Reconciler,
	workloadDefinition *v0.KubernetesWorkloadDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0KubernetesWorkloadDefinitionDeleted performs reconciliation when a v0 kubernetes workload definition
// has been deleted.
func v0KubernetesWorkloadDefinitionDeleted(
	r *controller.Reconciler,
	workloadDefinition *v0.KubernetesWorkloadDefinition,
	log *logr.Logger,
) (int64, error) {
	// check that deletion is scheduled - if not there's a problem
	if workloadDefinition.DeletionScheduled == nil {
		return 0, errors.New("deletion notification receieved but not scheduled")
	}

	// check to see if reconciled - it should not be, but if so we should do no
	// more
	if workloadDefinition.DeletionConfirmed != nil {
		return 0, nil
	}

	// get related kubernetes workload resource definitions
	workloadResourceDefinitions, err := client.GetKubernetesWorkloadResourceDefinitionsByKubernetesWorkloadDefinitionID(
		r.APIClient,
		r.APIServer,
		*workloadDefinition.ID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to get kubernetes workload resource definitions by kubernetes workload definition ID: %w", err)
	}

	// delete each related kubernetes workload resource definition
	for _, wrd := range *workloadResourceDefinitions {
		_, err := client.DeleteKubernetesWorkloadResourceDefinition(r.APIClient, r.APIServer, *wrd.ID)
		if err != nil {
			return 0, fmt.Errorf("failed to delete kubernetes workload resource definition with ID %d: %w", wrd.ID, err)
		}
		log.V(1).Info(
			"kubernetes workload resource definition deleted",
			"kubernetesWorkloadResourceDefinitionID", wrd.ID,
		)
	}

	return 0, nil
}
