// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package migrations

import (
	"context"
	"database/sql"
	"fmt"

	goose "github.com/pressly/goose/v3"
	gorm "gorm.io/gorm"
)

// gcpGceMachineRuntimeInstanceDroppedColumns maps each removed column on
// v0_gcp_gce_machine_runtime_instances to the type it is restored with on the
// way down. The columns are addressed as raw names rather than through the
// model migrator because the Go fields no longer exist, so the naming strategy
// has nothing to derive the names from.
var gcpGceMachineRuntimeInstanceDroppedColumns = []struct{ column, columnType string }{
	{"network_id", "STRING"},
	{"ssh_source_ranges", "JSONB"},
}

// init registers the migration with goose at startup.
func init() {
	goose.AddMigrationNoTxContext(Up000006, Down000006)
}

// Up000006 drops the network_id and ssh_source_ranges columns from
// v0_gcp_gce_machine_runtime_instances. The Go fields were removed from the
// model once network placement and firewall ingress moved to the machine
// runtime instance, but gorm AutoMigrate never emits DROP COLUMN, so the
// columns persist on upgraded databases with NULL on every row inserted since
// the removal. Every step is guarded by the hasColumn check, so the migration
// is a no-op on a fresh database where the initial migration built the table
// without the columns.
func Up000006(ctx context.Context, db *sql.DB) error {
	gormDb, err := getGormDbFromContext(ctx)
	if err != nil {
		return err
	}

	if err := dropGcpGceMachineRuntimeInstanceColumns(gormDb); err != nil {
		return err
	}

	return nil
}

// dropGcpGceMachineRuntimeInstanceColumns drops each removed column from
// v0_gcp_gce_machine_runtime_instances when it is still present, and returns
// nil for the columns already gone. The hasColumn guard keeps a fresh database
// untouched, where the initial migration built the table without the columns.
func dropGcpGceMachineRuntimeInstanceColumns(gormDb *gorm.DB) error {
	for _, c := range gcpGceMachineRuntimeInstanceDroppedColumns {
		if !hasColumn(gormDb, "v0_gcp_gce_machine_runtime_instances", c.column) {
			continue
		}
		if err := gormDb.Exec(fmt.Sprintf(
			"ALTER TABLE v0_gcp_gce_machine_runtime_instances DROP COLUMN %s", c.column,
		)).Error; err != nil {
			return fmt.Errorf("failed to drop v0_gcp_gce_machine_runtime_instances.%s: %w", c.column, err)
		}
	}
	return nil
}

// Down000006 re-adds network_id and ssh_source_ranges to
// v0_gcp_gce_machine_runtime_instances, matching the shapes the removed Go
// fields mapped to: a nullable string for the network identifier and a
// nullable JSONB blob for the list of source ranges. The rows the up migration
// discarded are not restored; the column values are not preserved across the
// drop.
func Down000006(ctx context.Context, db *sql.DB) error {
	gormDb, err := getGormDbFromContext(ctx)
	if err != nil {
		return err
	}

	for _, c := range gcpGceMachineRuntimeInstanceDroppedColumns {
		if hasColumn(gormDb, "v0_gcp_gce_machine_runtime_instances", c.column) {
			continue
		}
		if err := gormDb.Exec(fmt.Sprintf(
			"ALTER TABLE v0_gcp_gce_machine_runtime_instances ADD COLUMN %s %s", c.column, c.columnType,
		)).Error; err != nil {
			return fmt.Errorf("failed to add v0_gcp_gce_machine_runtime_instances.%s: %w", c.column, err)
		}
	}

	return nil
}
