// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package migrations

import (
	"context"
	"database/sql"
	"fmt"

	goose "github.com/pressly/goose/v3"
	gorm "gorm.io/gorm"

	v0 "github.com/threeport/threeport/pkg/api/v0"
)

// workloadTableRenames maps each workload table to its kubernetes workload name.
var workloadTableRenames = []struct{ from, to string }{
	{"v0_workload_definitions", "v0_kubernetes_workload_definitions"},
	{"v0_workload_instances", "v0_kubernetes_workload_instances"},
	{"v0_workload_resource_definitions", "v0_kubernetes_workload_resource_definitions"},
	{"v0_workload_resource_instances", "v0_kubernetes_workload_resource_instances"},
}

// workloadColumnRenames maps each workload foreign-key column to its kubernetes
// workload name, on the renamed tables and on the tables that reference them.
var workloadColumnRenames = []struct{ table, from, to string }{
	{"v0_kubernetes_workload_instances", "workload_definition_id", "kubernetes_workload_definition_id"},
	{"v0_kubernetes_workload_resource_definitions", "workload_definition_id", "kubernetes_workload_definition_id"},
	{"v0_kubernetes_workload_resource_instances", "workload_instance_id", "kubernetes_workload_instance_id"},
	{"v0_gateway_definitions", "workload_definition_id", "kubernetes_workload_definition_id"},
	{"v0_gateway_instances", "workload_instance_id", "kubernetes_workload_instance_id"},
	{"v0_domain_name_instances", "workload_instance_id", "kubernetes_workload_instance_id"},
	{"v0_secret_instances", "workload_instance_id", "kubernetes_workload_instance_id"},
}

// init registers the migration with goose at startup.
func init() {
	goose.AddMigrationNoTxContext(Up000002, Down000002)
}

// Up000002 renames the workload tables and their foreign-key columns to their
// kubernetes workload names, drops the removed workload event table, then runs
// AutoMigrate to add the tables and columns introduced since the initial schema.
// The renames run before AutoMigrate so AutoMigrate adopts the existing rows
// rather than creating empty kubernetes workload tables. HasTable and HasColumn
// guards make every step a no-op on a fresh database and keep the SQL portable.
func Up000002(ctx context.Context, db *sql.DB) error {
	gormDb, err := getGormDbFromContext(ctx)
	if err != nil {
		return err
	}

	if err := renameWorkloadSchema(gormDb); err != nil {
		return err
	}

	// add the tables and columns introduced since the initial schema
	if err := gormDb.AutoMigrate(dbInterfaces000002()...); err != nil {
		return fmt.Errorf("could not run gorm AutoMigrate: %w", err)
	}

	return nil
}

// renameWorkloadSchema renames the workload tables and their foreign-key columns
// to their kubernetes workload names and drops the removed workload event table.
// The renames preserve their rows in place; the HasTable and hasColumn guards
// keep each step a no-op on a fresh database and keep the SQL portable.
func renameWorkloadSchema(gormDb *gorm.DB) error {
	// rename the workload tables, preserving their rows in place
	for _, r := range workloadTableRenames {
		if !gormDb.Migrator().HasTable(r.from) {
			continue
		}
		if err := gormDb.Exec(fmt.Sprintf(
			"ALTER TABLE %s RENAME TO %s", r.from, r.to,
		)).Error; err != nil {
			return fmt.Errorf("failed to rename table %s: %w", r.from, err)
		}
	}

	// rename the workload foreign-key columns so AutoMigrate does not add the
	// new column alongside an orphaned old one. Rename only when the old column
	// is present, so a fresh database, where the initial migration already
	// created the new columns, is left untouched.
	for _, c := range workloadColumnRenames {
		if !hasColumn(gormDb, c.table, c.from) {
			continue
		}
		if err := gormDb.Exec(fmt.Sprintf(
			"ALTER TABLE %s RENAME COLUMN %s TO %s", c.table, c.from, c.to,
		)).Error; err != nil {
			return fmt.Errorf("failed to rename column %s on %s: %w", c.from, c.table, err)
		}
	}

	// drop the removed workload event table; nothing references it and there is
	// no successor table to copy its rows into
	if err := gormDb.Exec("DROP TABLE IF EXISTS v0_workload_events").Error; err != nil {
		return fmt.Errorf("failed to drop v0_workload_events: %w", err)
	}

	return nil
}

// hasColumn reports whether the table has the named column. It checks the table's
// actual columns rather than its create statement, so it is reliable on both the
// deployed database and an in-memory test database. The HasTable short-circuit
// keeps it quiet when the table itself is absent.
func hasColumn(gormDb *gorm.DB, table, column string) bool {
	if !gormDb.Migrator().HasTable(table) {
		return false
	}
	columnTypes, err := gormDb.Migrator().ColumnTypes(table)
	if err != nil {
		return false
	}
	for _, columnType := range columnTypes {
		if columnType.Name() == column {
			return true
		}
	}
	return false
}

// Down000002 reverses the table and column renames and drops the tables this
// migration added. The workload event table is not recreated: its model no
// longer exists and its rows were not preserved.
func Down000002(ctx context.Context, db *sql.DB) error {
	gormDb, err := getGormDbFromContext(ctx)
	if err != nil {
		return err
	}

	// reverse the column renames
	for _, c := range workloadColumnRenames {
		if !hasColumn(gormDb, c.table, c.to) {
			continue
		}
		if err := gormDb.Exec(fmt.Sprintf(
			"ALTER TABLE %s RENAME COLUMN %s TO %s", c.table, c.to, c.from,
		)).Error; err != nil {
			return fmt.Errorf("failed to rename column %s on %s: %w", c.to, c.table, err)
		}
	}

	// reverse the table renames
	for _, r := range workloadTableRenames {
		if !gormDb.Migrator().HasTable(r.to) {
			continue
		}
		if err := gormDb.Exec(fmt.Sprintf(
			"ALTER TABLE %s RENAME TO %s", r.to, r.from,
		)).Error; err != nil {
			return fmt.Errorf("failed to rename table %s: %w", r.to, err)
		}
	}

	// drop the tables this migration added
	for _, table := range []interface{}{
		&v0.GcpGceMachineRuntimeDefinition{},
		&v0.GcpGceMachineRuntimeInstance{},
	} {
		if !gormDb.Migrator().HasTable(table) {
			continue
		}
		if err := gormDb.Migrator().DropTable(table); err != nil {
			return fmt.Errorf("could not drop table with gorm db: %w", err)
		}
	}

	return nil
}

// dbInterfaces000002 returns the full set of models AutoMigrate reconciles after
// the workload tables are renamed. It mirrors the model set the application
// registers, so AutoMigrate adds anything the renamed schema is still missing.
func dbInterfaces000002() []interface{} {
	return []interface{}{
		&v0.AttachedObjectReference{},
		&v0.AwsProvider{},
		&v0.AwsEksKubernetesRuntimeDefinition{},
		&v0.AwsEksKubernetesRuntimeInstance{},
		&v0.GcpProvider{},
		&v0.GcpGkeKubernetesRuntimeDefinition{},
		&v0.GcpGkeKubernetesRuntimeInstance{},
		&v0.GcpGceMachineRuntimeDefinition{},
		&v0.GcpGceMachineRuntimeInstance{},
		&v0.KubernetesRuntimeDefinition{},
		&v0.KubernetesRuntimeInstance{},
		&v0.ControlPlaneDefinition{},
		&v0.ControlPlaneInstance{},
		&v0.ControlPlaneComponent{},
		&v0.Definition{},
		&v0.DomainNameDefinition{},
		&v0.DomainNameInstance{},
		&v0.Event{},
		&v0.GatewayDefinition{},
		&v0.GatewayHttpPort{},
		&v0.GatewayInstance{},
		&v0.GatewayTcpPort{},
		&v0.HelmWorkloadDefinition{},
		&v0.HelmWorkloadInstance{},
		&v0.Instance{},
		&v0.LogBackend{},
		&v0.LogStorageDefinition{},
		&v0.LogStorageInstance{},
		&v0.LoggingDefinition{},
		&v0.LoggingInstance{},
		&v0.MachineRuntimeDefinition{},
		&v0.MachineRuntimeInstance{},
		&v0.MachineWorkloadDefinition{},
		&v0.MachineWorkloadInstance{},
		&v0.MetricsDefinition{},
		&v0.MetricsInstance{},
		&v0.ModuleApi{},
		&v0.ModuleApiRoute{},
		&v0.ModuleController{},
		&v0.ModuleObject{},
		&v0.ObservabilityDashboardDefinition{},
		&v0.ObservabilityDashboardInstance{},
		&v0.ObservabilityStackDefinition{},
		&v0.ObservabilityStackInstance{},
		&v0.OciProvider{},
		&v0.OciOkeKubernetesRuntimeDefinition{},
		&v0.OciOkeKubernetesRuntimeInstance{},
		&v0.Profile{},
		&v0.SecretDefinition{},
		&v0.SecretInstance{},
		&v0.TerraformDefinition{},
		&v0.TerraformInstance{},
		&v0.Tier{},
		&v0.KubernetesWorkloadDefinition{},
		&v0.KubernetesWorkloadInstance{},
		&v0.KubernetesWorkloadResourceDefinition{},
		&v0.KubernetesWorkloadResourceInstance{},
	}
}
