// boilerplate generated by 'threeport-sdk gen' - do not edit

package main

import (
	v0 "github.com/threeport/threeport/pkg/api/v0"
	migrationtest "github.com/threeport/threeport/pkg/migrationtest/v0"
	"testing"
)

// persistedModels returns one instance of every model the API persists.
func persistedModels() []interface{} {
	return []interface{}{
		&v0.AttachedObjectReference{},
		&v0.AwsEksKubernetesRuntimeDefinition{},
		&v0.AwsEksKubernetesRuntimeInstance{},
		&v0.AwsProvider{},
		&v0.ControlPlaneComponent{},
		&v0.KubernetesRuntimeDefinition{},
		&v0.KubernetesRuntimeInstance{},
		&v0.Definition{},
		&v0.DomainNameDefinition{},
		&v0.DomainNameInstance{},
		&v0.Event{},
		&v0.GatewayDefinition{},
		&v0.GatewayHttpPort{},
		&v0.GatewayInstance{},
		&v0.GatewayTcpPort{},
		&v0.GcpGkeKubernetesRuntimeDefinition{},
		&v0.GcpGkeKubernetesRuntimeInstance{},
		&v0.GcpProvider{},
		&v0.HelmWorkloadDefinition{},
		&v0.HelmWorkloadInstance{},
		&v0.Instance{},
		&v0.ControlPlaneDefinition{},
		&v0.ControlPlaneInstance{},
		&v0.KubernetesWorkloadDefinition{},
		&v0.KubernetesWorkloadInstance{},
		&v0.KubernetesWorkloadResourceDefinition{},
		&v0.KubernetesWorkloadResourceInstance{},
		&v0.LogBackend{},
		&v0.LogStorageDefinition{},
		&v0.LogStorageInstance{},
		&v0.LoggingDefinition{},
		&v0.LoggingInstance{},
		&v0.MachineRuntimeDefinition{},
		&v0.MachineRuntimeInstance{},
		&v0.MachineWorkloadDefinition{},
		&v0.MachineWorkloadInstance{},
		&v0.MetricsDefinition{},
		&v0.MetricsInstance{},
		&v0.ModuleApi{},
		&v0.ModuleApiRoute{},
		&v0.ModuleController{},
		&v0.ModuleObject{},
		&v0.ObservabilityDashboardDefinition{},
		&v0.ObservabilityDashboardInstance{},
		&v0.ObservabilityStackDefinition{},
		&v0.ObservabilityStackInstance{},
		&v0.OciOkeKubernetesRuntimeDefinition{},
		&v0.OciOkeKubernetesRuntimeInstance{},
		&v0.OciProvider{},
		&v0.Profile{},
		&v0.SecretDefinition{},
		&v0.SecretInstance{},
		&v0.TerraformDefinition{},
		&v0.TerraformInstance{},
		&v0.Tier{},
	}
}

// TestMigrationsCoverEveryPersistedModel asserts the schema the migration
// chain builds matches the columns every persisted model declares, reporting
// both fields left without a column and columns left without a field.
func TestMigrationsCoverEveryPersistedModel(t *testing.T) {
	migrationtest.AssertMigrationsCoverModels(t, "threeport_goose_db_version", persistedModels())
}
