// boilerplate generated by 'threeport-sdk gen' - do not edit

package util

import (
	"fmt"
	nats "github.com/nats-io/nats.go"
	aws_notif "github.com/threeport/threeport/internal/aws/notif"
	controlplane_notif "github.com/threeport/threeport/internal/control-plane/notif"
	gateway_notif "github.com/threeport/threeport/internal/gateway/notif"
	notif1 "github.com/threeport/threeport/internal/gcp/notif"
	helmworkload_notif "github.com/threeport/threeport/internal/helm-workload/notif"
	kubernetesruntime_notif "github.com/threeport/threeport/internal/kubernetes-runtime/notif"
	kubernetesworkload_notif "github.com/threeport/threeport/internal/kubernetes-workload/notif"
	notif2 "github.com/threeport/threeport/internal/machine-runtime/notif"
	notif3 "github.com/threeport/threeport/internal/machine-workload/notif"
	observability_notif "github.com/threeport/threeport/internal/observability/notif"
	notif "github.com/threeport/threeport/internal/oci/notif"
	secret_notif "github.com/threeport/threeport/internal/secret/notif"
	terraform_notif "github.com/threeport/threeport/internal/terraform/notif"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
)

// Initialize the NATS Jet stream context with controller streams
func InitJetStream(nc *nats.Conn) (*nats.JetStreamContext, error) {
	js, err := nc.JetStream(nats.PublishAsyncMaxPending(256))
	if err != nil {
		return nil, fmt.Errorf("failed to create jetstream context: %w", err)
	}

	// add controller streams idempotently so a rest-api restart succeeds
	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     secret_notif.SecretStreamName,
		Subjects: secret_notif.GetSecretSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", secret_notif.SecretStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     aws_notif.AwsStreamName,
		Subjects: aws_notif.GetAwsSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", aws_notif.AwsStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     notif.OciStreamName,
		Subjects: notif.GetOciSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", notif.OciStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     notif1.GcpStreamName,
		Subjects: notif1.GetGcpSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", notif1.GcpStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     controlplane_notif.ControlPlaneStreamName,
		Subjects: controlplane_notif.GetControlPlaneSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", controlplane_notif.ControlPlaneStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     gateway_notif.GatewayStreamName,
		Subjects: gateway_notif.GetGatewaySubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", gateway_notif.GatewayStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     helmworkload_notif.HelmWorkloadStreamName,
		Subjects: helmworkload_notif.GetHelmWorkloadSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", helmworkload_notif.HelmWorkloadStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     notif2.MachineRuntimeStreamName,
		Subjects: notif2.GetMachineRuntimeSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", notif2.MachineRuntimeStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     notif3.MachineWorkloadStreamName,
		Subjects: notif3.GetMachineWorkloadSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", notif3.MachineWorkloadStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     kubernetesruntime_notif.KubernetesRuntimeStreamName,
		Subjects: kubernetesruntime_notif.GetKubernetesRuntimeSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", kubernetesruntime_notif.KubernetesRuntimeStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     observability_notif.ObservabilityStreamName,
		Subjects: observability_notif.GetObservabilitySubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", observability_notif.ObservabilityStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     terraform_notif.TerraformStreamName,
		Subjects: terraform_notif.GetTerraformSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", terraform_notif.TerraformStreamName, err)
	}

	err = notifications.EnsureStream(js, &nats.StreamConfig{
		Name:     kubernetesworkload_notif.KubernetesWorkloadStreamName,
		Subjects: kubernetesworkload_notif.GetKubernetesWorkloadSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not ensure stream %s: %w", kubernetesworkload_notif.KubernetesWorkloadStreamName, err)
	}

	return &js, nil
}
