// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package oci

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/fsnotify/fsnotify"
	logr "github.com/go-logr/logr"
	"github.com/oracle/oci-go-sdk/v65/common"
	ociidentity "github.com/oracle/oci-go-sdk/v65/identity"
	"gorm.io/datatypes"

	notif "github.com/threeport/threeport/internal/oci/notif"
	"github.com/threeport/threeport/internal/provider"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	client "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	encryption "github.com/threeport/threeport/pkg/encryption/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
)

const staleOkeAckDurationSeconds = 240

// activeOkeOperations tracks in-progress goroutines per instance ID to prevent
// duplicate create/delete operations from being spawned simultaneously.
var activeOkeOperations sync.Map

// pulumiSemaphore limits concurrent Pulumi operations to prevent OOM from
// too many simultaneous infrastructure deployments.
var pulumiSemaphore = make(chan struct{}, 5)

// v0OciOkeKubernetesRuntimeInstanceCreated performs reconciliation when a v0 OciOkeKubernetesRuntimeInstance
// has been created.
func v0OciOkeKubernetesRuntimeInstanceCreated(
	r *controller.Reconciler,
	ociOkeKubernetesRuntimeInstance *v0.OciOkeKubernetesRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	// add log metadata
	reconLog := log.WithValues(
		"ociOkeKubernetesRuntimeInstanceID", *ociOkeKubernetesRuntimeInstance.ID,
		"ociOkeKubernetesRuntimeInstanceName", *ociOkeKubernetesRuntimeInstance.Name,
	)

	// fetch latest state from API
	ociOkeKubernetesRuntimeInstance, err := client.GetOciOkeKubernetesRuntimeInstanceByID(
		r.APIClient,
		r.APIServer,
		*ociOkeKubernetesRuntimeInstance.ID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to get latest version of OCI OKE kubernetes runtime instance: %w", err)
	}

	// check if already reconciled
	if ociOkeKubernetesRuntimeInstance.CreationConfirmed != nil {
		return 0, nil
	}

	// check if previously acknowledged
	if ociOkeKubernetesRuntimeInstance.CreationAcknowledged != nil && !*ociOkeKubernetesRuntimeInstance.CreationFailed {
		// check if creation is complete by looking for ClusterOCID
		latestInstance, err := client.GetOciOkeKubernetesRuntimeInstanceByID(
			r.APIClient,
			r.APIServer,
			*ociOkeKubernetesRuntimeInstance.ID,
		)
		if err != nil {
			return 0, fmt.Errorf("failed to check OKE cluster creation status: %w", err)
		}

		if latestInstance.ClusterOCID != nil && *latestInstance.ClusterOCID != "" {
			// creation complete — get connection info and confirm
			ociOkeKubernetesRuntimeDefinition, err := client.GetOciOkeKubernetesRuntimeDefinitionByID(
				r.APIClient,
				r.APIServer,
				*latestInstance.OciOkeKubernetesRuntimeDefinitionID,
			)
			if err != nil {
				return 0, fmt.Errorf("failed to retrieve cluster definition by ID: %w", err)
			}

			infraOKE, err := buildOkeInfra(r, latestInstance, ociOkeKubernetesRuntimeDefinition, &reconLog)
			if err != nil {
				return 0, fmt.Errorf("failed to build OKE infra object: %w", err)
			}

			// get kubernetes cluster connection info
			kubeConnectionInfo, err := infraOKE.GetConnection()
			if err != nil {
				return 0, fmt.Errorf("failed to get Kubernetes API connection info: %w", err)
			}

			// get kubernetes runtime instance to update kube connection info
			kubernetesRuntimeInstance, err := client.GetKubernetesRuntimeInstanceByID(
				r.APIClient,
				r.APIServer,
				*latestInstance.KubernetesRuntimeInstanceID,
			)
			if err != nil {
				return 0, fmt.Errorf("failed to get kubernetes runtime instance to update kube connection info: %w", err)
			}

			// update kube connection info
			kubeRuntimeReconciled := false
			kubernetesRuntimeInstance.APIEndpoint = &kubeConnectionInfo.APIEndpoint
			kubernetesRuntimeInstance.CACertificate = &kubeConnectionInfo.CACertificate
			kubernetesRuntimeInstance.ConnectionToken = &kubeConnectionInfo.Token
			kubernetesRuntimeInstance.ConnectionTokenExpiration = &kubeConnectionInfo.TokenExpiration
			kubernetesRuntimeInstance.Reconciled = &kubeRuntimeReconciled
			_, err = client.UpdateKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				kubernetesRuntimeInstance,
			)
			if err != nil {
				return 0, fmt.Errorf("failed to update kubernetes runtime instance with kube connection info: %w", err)
			}

			// confirm creation and set reconciled to true
			creationReconciled := true
			creationTimestamp := time.Now().UTC()
			confirmedInstance := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: latestInstance.ID,
				},
				Reconciliation: v0.Reconciliation{
					Reconciled:        &creationReconciled,
					CreationConfirmed: &creationTimestamp,
				},
			}
			_, err = client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&confirmedInstance,
			)
			if err != nil {
				return 0, fmt.Errorf("failed to confirm creation of OKE cluster infra resources: %w", err)
			}

			reconLog.Info("OKE cluster creation confirmed")
			return 0, nil
		}

		// not complete yet — check if acknowledgement is stale
		if !checkStaleOkeAck(*ociOkeKubernetesRuntimeInstance.CreationAcknowledged) {
			return 120, nil
		}
	}

	// one of the following is true:
	// 1. creation has not been acknowledged — new create request
	// 2. creation has previously failed — time to retry
	// 3. the last acknowledgement is stale — creation was interrupted

	// acknowledge creation and set creation failure to false
	creationAckTimestamp := time.Now().UTC()
	creationFailed := false
	ociOkeKubernetesRuntimeInstance.CreationAcknowledged = &creationAckTimestamp
	ociOkeKubernetesRuntimeInstance.CreationFailed = &creationFailed
	_, err = client.UpdateOciOkeKubernetesRuntimeInstance(
		r.APIClient,
		r.APIServer,
		ociOkeKubernetesRuntimeInstance,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to set creation acknowledged timestamp: %w", err)
	}

	// get cluster definition
	ociOkeKubernetesRuntimeDefinition, err := client.GetOciOkeKubernetesRuntimeDefinitionByID(
		r.APIClient,
		r.APIServer,
		*ociOkeKubernetesRuntimeInstance.OciOkeKubernetesRuntimeDefinitionID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to retrieve cluster definition by ID: %w", err)
	}

	// build the infra object
	infraOKE, err := buildOkeInfra(r, ociOkeKubernetesRuntimeInstance, ociOkeKubernetesRuntimeDefinition, &reconLog)
	if err != nil {
		return 0, fmt.Errorf("failed to build OKE infra object: %w", err)
	}

	// guard against duplicate goroutines for the same instance (unified key
	// prevents concurrent create/delete on the same Pulumi workspace)
	operationKey := fmt.Sprintf("oke-%d", *ociOkeKubernetesRuntimeInstance.ID)
	if _, loaded := activeOkeOperations.LoadOrStore(operationKey, true); loaded {
		reconLog.Info("operation already active for this instance, skipping create")
		return 120, nil
	}

	// check if deletion was scheduled while we were preparing to create —
	// if so, release the guard and let the delete handler proceed
	latestForDeleteCheck, err := client.GetOciOkeKubernetesRuntimeInstanceByID(
		r.APIClient,
		r.APIServer,
		*ociOkeKubernetesRuntimeInstance.ID,
	)
	if err != nil {
		activeOkeOperations.Delete(operationKey)
		return 0, fmt.Errorf("failed to check deletion status before create: %w", err)
	}
	if latestForDeleteCheck.DeletionScheduled != nil {
		activeOkeOperations.Delete(operationKey)
		reconLog.Info("deletion scheduled, aborting create to let delete handler proceed")
		return 0, nil
	}

	// acquire Pulumi concurrency semaphore
	select {
	case pulumiSemaphore <- struct{}{}:
		// acquired slot
	default:
		activeOkeOperations.Delete(operationKey)
		reconLog.Info("Pulumi worker pool full, requeuing")
		return 30, nil
	}

	// launch creation in background goroutine
	go func() {
		defer activeOkeOperations.Delete(operationKey)
		defer func() { <-pulumiSemaphore }()
		createOkeInfra(r, infraOKE, ociOkeKubernetesRuntimeInstance, &reconLog)
	}()

	return 120, nil
}

// v0OciOkeKubernetesRuntimeInstanceUpdated performs reconciliation when a v0 OciOkeKubernetesRuntimeInstance
// has been updated.
func v0OciOkeKubernetesRuntimeInstanceUpdated(
	r *controller.Reconciler,
	ociOkeKubernetesRuntimeInstance *v0.OciOkeKubernetesRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0OciOkeKubernetesRuntimeInstanceDeleted performs reconciliation when a v0 OciOkeKubernetesRuntimeInstance
// has been deleted.
func v0OciOkeKubernetesRuntimeInstanceDeleted(
	r *controller.Reconciler,
	ociOkeKubernetesRuntimeInstance *v0.OciOkeKubernetesRuntimeInstance,
	log *logr.Logger,
) (int64, error) {
	// add log metadata
	reconLog := log.WithValues(
		"ociOkeKubernetesRuntimeInstanceID", *ociOkeKubernetesRuntimeInstance.ID,
		"ociOkeKubernetesRuntimeInstanceName", *ociOkeKubernetesRuntimeInstance.Name,
	)

	// check that deletion is scheduled
	if ociOkeKubernetesRuntimeInstance.DeletionScheduled == nil {
		return 0, errors.New("deletion notification received but not scheduled")
	}

	// check if already confirmed
	if ociOkeKubernetesRuntimeInstance.DeletionConfirmed != nil {
		return 0, nil
	}

	// check if previously acknowledged
	if ociOkeKubernetesRuntimeInstance.DeletionAcknowledged != nil {
		// check if Pulumi destroy is complete (ResourceInventory cleared)
		latestInstance, err := client.GetOciOkeKubernetesRuntimeInstanceByID(
			r.APIClient,
			r.APIServer,
			*ociOkeKubernetesRuntimeInstance.ID,
		)
		if err != nil {
			return 0, fmt.Errorf("failed to check OKE cluster deletion status: %w", err)
		}

		inventoryCleared := latestInstance.ResourceInventory == nil ||
			len(*latestInstance.ResourceInventory) == 0 ||
			string(*latestInstance.ResourceInventory) == "{}" ||
			string(*latestInstance.ResourceInventory) == "null"
		if inventoryCleared {
			// update DeletionAcknowledged to prevent this branch from going stale
			// while compartment cleanup runs
			refreshTimestamp := time.Now().UTC()
			refreshUpdate := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: latestInstance.ID,
				},
				Reconciliation: v0.Reconciliation{
					DeletionAcknowledged: &refreshTimestamp,
				},
			}
			_, _ = client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&refreshUpdate,
			)
			// resources destroyed — clean up compartment and confirm
			ociOkeKubernetesRuntimeDefinition, err := client.GetOciOkeKubernetesRuntimeDefinitionByID(
				r.APIClient,
				r.APIServer,
				*latestInstance.OciOkeKubernetesRuntimeDefinitionID,
			)
			if err != nil {
				return 0, fmt.Errorf("failed to retrieve cluster definition for deletion cleanup: %w", err)
			}

			infraOKE, err := buildOkeInfra(r, latestInstance, ociOkeKubernetesRuntimeDefinition, &reconLog)
			if err != nil {
				return 0, fmt.Errorf("failed to build OKE infra object for deletion cleanup: %w", err)
			}

			// delete compartment (no IAM resources were created by controller)
			if err := infraOKE.DeleteCompartment(); err != nil {
				reconLog.Error(err, "failed to delete OCI compartment")
			}

			// delete Pulumi stack state
			if err := infraOKE.DeletePulumiStackState(); err != nil {
				reconLog.Error(err, "failed to delete Pulumi stack state")
			}

			// confirm deletion
			deletionTimestamp := time.Now().UTC()
			confirmedInstance := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: latestInstance.ID,
				},
				Reconciliation: v0.Reconciliation{
					DeletionConfirmed: &deletionTimestamp,
				},
			}
			_, err = client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&confirmedInstance,
			)
			if err != nil {
				return 0, fmt.Errorf("failed to confirm deletion of OKE cluster: %w", err)
			}

			reconLog.Info("OKE cluster deletion confirmed")
			return 0, nil
		}

		// resources not yet destroyed — check if deletion acknowledgement is stale
		// (indicates pod died during delete goroutine)
		if checkStaleOkeAck(*ociOkeKubernetesRuntimeInstance.DeletionAcknowledged) {
			reconLog.Info("deletion acknowledgement is stale, re-launching delete goroutine")
			// fall through to re-launch delete goroutine below
		} else {
			return 60, nil
		}
	}

	// acknowledge deletion scheduled (or re-acknowledge after stale detection)
	timestamp := time.Now().UTC()
	ociOkeKubernetesRuntimeInstance.DeletionAcknowledged = &timestamp
	_, err := client.UpdateOciOkeKubernetesRuntimeInstance(
		r.APIClient,
		r.APIServer,
		ociOkeKubernetesRuntimeInstance,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to set deletion acknowledged timestamp: %w", err)
	}

	// get cluster definition
	ociOkeKubernetesRuntimeDefinition, err := client.GetOciOkeKubernetesRuntimeDefinitionByID(
		r.APIClient,
		r.APIServer,
		*ociOkeKubernetesRuntimeInstance.OciOkeKubernetesRuntimeDefinitionID,
	)
	if err != nil {
		return 0, fmt.Errorf("failed to retrieve cluster definition for deletion: %w", err)
	}

	// build infra object
	infraOKE, err := buildOkeInfra(r, ociOkeKubernetesRuntimeInstance, ociOkeKubernetesRuntimeDefinition, &reconLog)
	if err != nil {
		return 0, fmt.Errorf("failed to build OKE infra object for deletion: %w", err)
	}

	// guard against duplicate goroutines for the same instance (unified key
	// prevents concurrent create/delete on the same Pulumi workspace)
	operationKey := fmt.Sprintf("oke-%d", *ociOkeKubernetesRuntimeInstance.ID)
	if _, loaded := activeOkeOperations.LoadOrStore(operationKey, true); loaded {
		reconLog.Info("operation already active for this instance, skipping delete")
		return 60, nil
	}

	// restore Pulumi state from ResourceInventory
	if ociOkeKubernetesRuntimeInstance.ResourceInventory != nil {
		if err := infraOKE.SetStackState(ociOkeKubernetesRuntimeInstance.ResourceInventory); err != nil {
			activeOkeOperations.Delete(operationKey)
			return 0, fmt.Errorf("failed to restore Pulumi stack state: %w", err)
		}
	}

	// acquire Pulumi concurrency semaphore
	select {
	case pulumiSemaphore <- struct{}{}:
		// acquired slot
	default:
		activeOkeOperations.Delete(operationKey)
		reconLog.Info("Pulumi worker pool full, requeuing")
		return 30, nil
	}

	// launch deletion in background goroutine
	go func() {
		defer activeOkeOperations.Delete(operationKey)
		defer func() { <-pulumiSemaphore }()
		deleteOkeInfra(r, infraOKE, ociOkeKubernetesRuntimeInstance, &reconLog)
	}()

	return 300, nil
}

// buildOkeInfra constructs a KubernetesRuntimeInfraOKE from API objects.
func buildOkeInfra(
	r *controller.Reconciler,
	instance *v0.OciOkeKubernetesRuntimeInstance,
	definition *v0.OciOkeKubernetesRuntimeDefinition,
	log *logr.Logger,
) (*provider.KubernetesRuntimeInfraOKE, error) {
	// get OCI provider
	ociProvider, err := client.GetOciProviderByID(
		r.APIClient,
		r.APIServer,
		*instance.OciProviderID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve OCI provider by ID: %w", err)
	}

	// decrypt private key
	decryptedPrivateKey, err := encryption.Decrypt(r.EncryptionKey, *ociProvider.PrivateKey)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt OCI provider private key: %w", err)
	}

	// construct OCI config provider from provider credentials
	configProvider := common.NewRawConfigurationProvider(
		*ociProvider.CompartmentOCID,
		*ociProvider.UserOCID,
		*ociProvider.DefaultRegion,
		*ociProvider.KeyFingerprint,
		decryptedPrivateKey,
		nil,
	)

	// use instance region if set, otherwise fall back to provider default region
	region := *ociProvider.DefaultRegion
	if instance.Region != nil && *instance.Region != "" {
		region = *instance.Region
	}

	infraOKE := &provider.KubernetesRuntimeInfraOKE{
		RuntimeInstanceName:    *instance.Name,
		Region:                 region,
		TenancyOCID:            *ociProvider.CompartmentOCID,
		ConfigProvider:         configProvider,
		WorkerNodeShape:        *definition.WorkerNodeShape,
		WorkerNodeInitialCount: *definition.WorkerNodeInitialCount,
		Version:                provider.DefaultOKEKubernetesVersion,
		ServiceUserOCID:        *ociProvider.UserOCID,
		Fingerprint:            *ociProvider.KeyFingerprint,
		PrivateKeyPEM:          decryptedPrivateKey,
		Logger:                 log,
	}

	// resolve the compartment OCID by looking up the compartment named after
	// the runtime instance under the tenancy
	identityClient, err := ociidentity.NewIdentityClientWithConfigurationProvider(configProvider)
	if err != nil {
		return nil, fmt.Errorf("failed to create identity client: %w", err)
	}
	identityClient.SetRegion(region)

	listRequest := ociidentity.ListCompartmentsRequest{
		CompartmentId: ociProvider.CompartmentOCID,
		Name:          instance.Name,
	}
	listResponse, err := identityClient.ListCompartments(context.Background(), listRequest)
	if err != nil {
		return nil, fmt.Errorf("failed to list compartments to resolve compartment OCID: %w", err)
	}
	if len(listResponse.Items) > 0 {
		infraOKE.CompartmentOCID = *listResponse.Items[0].Id
	} else {
		// fall back to tenancy OCID (compartment may not exist yet for new creates)
		infraOKE.CompartmentOCID = *ociProvider.CompartmentOCID
	}

	return infraOKE, nil
}

// createOkeInfra creates the OKE cluster infrastructure in a background goroutine.
func createOkeInfra(
	r *controller.Reconciler,
	infraOKE *provider.KubernetesRuntimeInfraOKE,
	instance *v0.OciOkeKubernetesRuntimeInstance,
	log *logr.Logger,
) {
	// refresh the creation acknowledgement until this function returns
	quitAck := make(chan bool, 1)
	go refreshOkeAcknowledgement(r, instance, quitAck, log)
	defer func() { quitAck <- true }()

	// restore Pulumi state from ResourceInventory if available (retry after
	// failure or pod restart so Pulumi knows about previously created resources)
	if instance.ResourceInventory != nil &&
		len(*instance.ResourceInventory) > 0 &&
		string(*instance.ResourceInventory) != "{}" &&
		string(*instance.ResourceInventory) != "null" {
		if err := infraOKE.SetStackState(instance.ResourceInventory); err != nil {
			log.Error(err, "failed to restore Pulumi stack state for retry")
			persistOkeCreateFailure(r, *instance.ID, log)
			return
		}
		log.Info("restored Pulumi state from database for creation retry")

		// refresh stack to sync state with cloud reality and clear stale
		// pending operations from interrupted runs
		if err := infraOKE.RefreshStack(); err != nil {
			log.Error(err, "failed to refresh Pulumi stack state")
			persistOkeCreateFailure(r, *instance.ID, log)
			return
		}
		log.Info("refreshed Pulumi stack state against cloud reality")
	}

	// start state streaming via fsnotify
	quitStream := make(chan bool, 1)
	streamStopped := false
	go streamOkeState(r, infraOKE, instance, quitStream, log)
	defer func() {
		if !streamStopped {
			quitStream <- true
		}
	}()

	// create infrastructure (compartment + Pulumi, no IAM)
	_, err := infraOKE.CreateInfra()
	if err != nil {
		log.Error(err, "failed to create OKE cluster infra")

		// stop the stream watcher before capturing final state
		quitStream <- true
		streamStopped = true

		// capture Pulumi state even on failure so retries can restore it
		// and avoid creating duplicate cloud resources
		stateJSON, stateErr := infraOKE.GetStackState()
		if stateErr != nil {
			log.Error(stateErr, "failed to get Pulumi stack state after failed creation")
		} else if stateJSON != nil {
			stateUpdate := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: instance.ID,
				},
				ResourceInventory: stateJSON,
			}
			if _, updateErr := client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&stateUpdate,
			); updateErr != nil {
				log.Error(updateErr, "failed to save partial Pulumi state after failed creation")
			}
		}

		persistOkeCreateFailure(r, *instance.ID, log)
		return
	}

	// capture final Pulumi state
	stateJSON, err := infraOKE.GetStackState()
	if err != nil {
		log.Error(err, "failed to get Pulumi stack state after creation")
		persistOkeCreateFailure(r, *instance.ID, log)
		return
	}

	// get cluster OCID
	clusterOCID, err := infraOKE.GetClusterOCID(infraOKE.RuntimeInstanceName)
	if err != nil {
		log.Error(err, "failed to get OKE cluster OCID")
		persistOkeCreateFailure(r, *instance.ID, log)
		return
	}

	// update instance with final state and cluster OCID
	updatedInstance := v0.OciOkeKubernetesRuntimeInstance{
		Common: v0.Common{
			ID: instance.ID,
		},
		ResourceInventory: stateJSON,
		ClusterOCID:       &clusterOCID,
	}
	_, err = client.UpdateOciOkeKubernetesRuntimeInstance(
		r.APIClient,
		r.APIServer,
		&updatedInstance,
	)
	if err != nil {
		log.Error(err, "failed to update OKE instance with resource inventory and cluster OCID")
	}

	// publish NATS notification to trigger immediate re-reconciliation
	notifPayload, notifErr := instance.NotificationPayload(
		notifications.NotificationOperationCreated,
		false,
		time.Now().Unix(),
	)
	if notifErr != nil {
		log.Error(notifErr, "failed to create notification payload after OKE creation")
	} else if _, notifErr = r.JetStreamContext.Publish(
		notif.OciOkeKubernetesRuntimeInstanceCreateSubject,
		*notifPayload,
	); notifErr != nil {
		log.Error(notifErr, "failed to publish completion notification after OKE creation")
	}
}

// deleteOkeInfra deletes the OKE cluster infrastructure in a background goroutine.
func deleteOkeInfra(
	r *controller.Reconciler,
	infraOKE *provider.KubernetesRuntimeInfraOKE,
	instance *v0.OciOkeKubernetesRuntimeInstance,
	log *logr.Logger,
) {
	// refresh the deletion acknowledgement until this function returns
	quitAck := make(chan bool, 1)
	go refreshOkeDeletionAcknowledgement(r, instance, quitAck, log)
	defer func() { quitAck <- true }()

	// destroy Pulumi stack (VCN, subnets, cluster, node pool)
	if err := infraOKE.Delete(); err != nil {
		log.Error(err, "failed to delete OKE cluster infra, will retry on next reconciliation")

		// capture updated Pulumi state so retries know which resources remain
		stateJSON, stateErr := infraOKE.GetStackState()
		if stateErr != nil {
			log.Error(stateErr, "failed to get Pulumi stack state after failed deletion")
		} else if stateJSON != nil {
			stateUpdate := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: instance.ID,
				},
				ResourceInventory: stateJSON,
			}
			if _, updateErr := client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&stateUpdate,
			); updateErr != nil {
				log.Error(updateErr, "failed to save Pulumi state after failed deletion")
			}
		}
		return
	}

	// clear ResourceInventory to signal deletion complete
	emptyInventory := datatypes.JSON([]byte("{}"))
	clearedInstance := v0.OciOkeKubernetesRuntimeInstance{
		Common: v0.Common{
			ID: instance.ID,
		},
		ResourceInventory: &emptyInventory,
	}
	_, err := client.UpdateOciOkeKubernetesRuntimeInstance(
		r.APIClient,
		r.APIServer,
		&clearedInstance,
	)
	if err != nil {
		log.Error(err, "failed to clear resource inventory after deletion")
	}

	// publish NATS notification to trigger immediate re-reconciliation
	notifPayload, notifErr := instance.NotificationPayload(
		notifications.NotificationOperationDeleted,
		false,
		time.Now().Unix(),
	)
	if notifErr != nil {
		log.Error(notifErr, "failed to create notification payload after OKE deletion")
	} else if _, notifErr = r.JetStreamContext.Publish(
		notif.OciOkeKubernetesRuntimeInstanceDeleteSubject,
		*notifPayload,
	); notifErr != nil {
		log.Error(notifErr, "failed to publish completion notification after OKE deletion")
	}
}

// streamOkeState watches the Pulumi state file via fsnotify and pushes changes
// to the API as ResourceInventory updates.
func streamOkeState(
	r *controller.Reconciler,
	infraOKE *provider.KubernetesRuntimeInfraOKE,
	instance *v0.OciOkeKubernetesRuntimeInstance,
	quit chan bool,
	log *logr.Logger,
) {
	// get state file path and pre-create directory
	stateFilePath, err := infraOKE.GetStateFilePath()
	if err != nil {
		log.Error(err, "failed to get state file path for streaming")
		return
	}
	stateDir := filepath.Dir(stateFilePath)
	if err := os.MkdirAll(stateDir, 0755); err != nil {
		log.Error(err, "failed to create state directory for watcher")
		return
	}

	// create fsnotify watcher
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Error(err, "failed to create fsnotify watcher")
		return
	}
	defer watcher.Close()

	// watch the directory containing the state file
	if err := watcher.Add(stateDir); err != nil {
		log.Error(err, "failed to add directory to watcher")
		return
	}

	stateFileName := filepath.Base(stateFilePath)

	for {
		select {
		case <-quit:
			return

		case event, ok := <-watcher.Events:
			if !ok {
				return
			}
			// only react to write/create events for the state file
			if filepath.Base(event.Name) != stateFileName {
				continue
			}
			if !event.Has(fsnotify.Write) && !event.Has(fsnotify.Create) {
				continue
			}

			// read and upload state immediately
			state, err := infraOKE.ReadStateFile()
			if err != nil {
				log.Error(err, "failed to read state file during streaming")
				continue
			}
			if state == nil {
				continue
			}

			// push state to API
			stateUpdate := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: instance.ID,
				},
				ResourceInventory: state,
			}
			if _, err := client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&stateUpdate,
			); err != nil {
				log.Error(err, "failed to update resource inventory during state streaming")
			}

		case err, ok := <-watcher.Errors:
			if !ok {
				return
			}
			log.Error(err, "fsnotify watcher error")
		}
	}
}

// refreshOkeAcknowledgement refreshes the creation acknowledged timestamp every
// 60 seconds until told to quit.
func refreshOkeAcknowledgement(
	r *controller.Reconciler,
	instance *v0.OciOkeKubernetesRuntimeInstance,
	quitChan chan bool,
	log *logr.Logger,
) {
	for {
		select {
		case <-quitChan:
			return
		case <-time.After(60 * time.Second):
			// refresh the acknowledgement timestamp
			refreshAckTimestamp := time.Now().UTC()
			ackUpdate := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: instance.ID,
				},
				Reconciliation: v0.Reconciliation{
					CreationAcknowledged: &refreshAckTimestamp,
				},
			}
			if _, err := client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&ackUpdate,
			); err != nil {
				log.Error(err, "failed to refresh creation acknowledged timestamp")
			}
		}
	}
}

// refreshOkeDeletionAcknowledgement refreshes the deletion acknowledged timestamp
// every 60 seconds until told to quit, preventing stale detection from re-launching
// the delete goroutine while it is still running.
func refreshOkeDeletionAcknowledgement(
	r *controller.Reconciler,
	instance *v0.OciOkeKubernetesRuntimeInstance,
	quitChan chan bool,
	log *logr.Logger,
) {
	for {
		select {
		case <-quitChan:
			return
		case <-time.After(60 * time.Second):
			refreshAckTimestamp := time.Now().UTC()
			ackUpdate := v0.OciOkeKubernetesRuntimeInstance{
				Common: v0.Common{
					ID: instance.ID,
				},
				Reconciliation: v0.Reconciliation{
					DeletionAcknowledged: &refreshAckTimestamp,
				},
			}
			if _, err := client.UpdateOciOkeKubernetesRuntimeInstance(
				r.APIClient,
				r.APIServer,
				&ackUpdate,
			); err != nil {
				log.Error(err, "failed to refresh deletion acknowledged timestamp")
			}
		}
	}
}

// persistOkeCreateFailure calls the threeport API to set CreationFailed to true.
// If the call to the API fails, it is retried every 10 seconds up to 30 times
// (5 minutes). After exhausting retries, the goroutine returns and stale ack
// detection will recover the operation.
func persistOkeCreateFailure(
	r *controller.Reconciler,
	instanceID uint,
	log *logr.Logger,
) {
	const maxRetries = 30
	for attempt := 0; attempt < maxRetries; attempt++ {
		creationFailed := true
		failedInstance := v0.OciOkeKubernetesRuntimeInstance{
			Common: v0.Common{
				ID: &instanceID,
			},
			Reconciliation: v0.Reconciliation{
				CreationFailed: &creationFailed,
			},
		}
		_, err := client.UpdateOciOkeKubernetesRuntimeInstance(
			r.APIClient,
			r.APIServer,
			&failedInstance,
		)
		if err != nil {
			log.Error(err, "failed to persist failure of OKE cluster infra resource creation - retrying in 10 sec",
				"attempt", attempt+1, "maxRetries", maxRetries)
			time.Sleep(time.Second * 10)
			continue
		}

		return
	}
	log.Error(
		fmt.Errorf("exhausted %d retries", maxRetries),
		"failed to persist OKE creation failure, stale ack detection will recover",
	)
}

// checkStaleOkeAck checks if the creation acknowledged timestamp has gone stale,
// indicating the creation process was interrupted.
func checkStaleOkeAck(creationAcknowledged time.Time) bool {
	duration := time.Now().UTC().Sub(creationAcknowledged)
	return duration.Seconds() > staleOkeAckDurationSeconds
}
