// boilerplate generated by 'threeport-sdk gen' - do not edit

package notif

const (
	GcpStreamName = "gcpStream"

	GcpGkeKubernetesRuntimeInstanceSubject       = "gcpGkeKubernetesRuntimeInstance.*"
	GcpGkeKubernetesRuntimeInstanceCreateSubject = "gcpGkeKubernetesRuntimeInstance.create"
	GcpGkeKubernetesRuntimeInstanceUpdateSubject = "gcpGkeKubernetesRuntimeInstance.update"
	GcpGkeKubernetesRuntimeInstanceDeleteSubject = "gcpGkeKubernetesRuntimeInstance.delete"

	GcpGceMachineRuntimeInstanceSubject       = "gcpGceMachineRuntimeInstance.*"
	GcpGceMachineRuntimeInstanceCreateSubject = "gcpGceMachineRuntimeInstance.create"
	GcpGceMachineRuntimeInstanceUpdateSubject = "gcpGceMachineRuntimeInstance.update"
	GcpGceMachineRuntimeInstanceDeleteSubject = "gcpGceMachineRuntimeInstance.delete"

	GcpNetworkSubject       = "gcpNetwork.*"
	GcpNetworkCreateSubject = "gcpNetwork.create"
	GcpNetworkUpdateSubject = "gcpNetwork.update"
	GcpNetworkDeleteSubject = "gcpNetwork.delete"
)

// GetGcpGkeKubernetesRuntimeInstanceSubjects returns the NATS subjects
// for gcp gke kubernetes runtime instances.
func GetGcpGkeKubernetesRuntimeInstanceSubjects() []string {
	return []string{
		GcpGkeKubernetesRuntimeInstanceCreateSubject,
		GcpGkeKubernetesRuntimeInstanceUpdateSubject,
		GcpGkeKubernetesRuntimeInstanceDeleteSubject,
	}
}

// GetGcpGceMachineRuntimeInstanceSubjects returns the NATS subjects
// for gcp gce machine runtime instances.
func GetGcpGceMachineRuntimeInstanceSubjects() []string {
	return []string{
		GcpGceMachineRuntimeInstanceCreateSubject,
		GcpGceMachineRuntimeInstanceUpdateSubject,
		GcpGceMachineRuntimeInstanceDeleteSubject,
	}
}

// GetGcpNetworkSubjects returns the NATS subjects
// for gcp networks.
func GetGcpNetworkSubjects() []string {
	return []string{
		GcpNetworkCreateSubject,
		GcpNetworkUpdateSubject,
		GcpNetworkDeleteSubject,
	}
}

// GetGcpSubjects returns the NATS subjects
// for all gcp objects.
func GetGcpSubjects() []string {
	var gcpSubjects []string

	gcpSubjects = append(gcpSubjects, GetGcpGkeKubernetesRuntimeInstanceSubjects()...)
	gcpSubjects = append(gcpSubjects, GetGcpGceMachineRuntimeInstanceSubjects()...)
	gcpSubjects = append(gcpSubjects, GetGcpNetworkSubjects()...)

	return gcpSubjects
}
