// generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "github.com/threeport/threeport/pkg/api-server/v0/handlers"
	v0 "github.com/threeport/threeport/pkg/api/v0"
)

// MachineRuntimeDefinitionRoutes sets up all routes for the MachineRuntimeDefinition handlers.
func MachineRuntimeDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathMachineRuntimeDefinitionVersions, h.GetMachineRuntimeDefinitionVersions)

	e.POST(v0.PathMachineRuntimeDefinitions, h.AddMachineRuntimeDefinition)
	e.GET(v0.PathMachineRuntimeDefinitions, h.GetMachineRuntimeDefinitions)
	e.GET(v0.PathMachineRuntimeDefinitions+"/:id", h.GetMachineRuntimeDefinition)
	e.PATCH(v0.PathMachineRuntimeDefinitions+"/:id", h.UpdateMachineRuntimeDefinition)
	e.PUT(v0.PathMachineRuntimeDefinitions+"/:id", h.ReplaceMachineRuntimeDefinition)
	e.DELETE(v0.PathMachineRuntimeDefinitions+"/:id", h.DeleteMachineRuntimeDefinition)
}

// MachineRuntimeInstanceRoutes sets up all routes for the MachineRuntimeInstance handlers.
func MachineRuntimeInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathMachineRuntimeInstanceVersions, h.GetMachineRuntimeInstanceVersions)

	e.POST(v0.PathMachineRuntimeInstances, h.AddMachineRuntimeInstance)
	e.GET(v0.PathMachineRuntimeInstances, h.GetMachineRuntimeInstances)
	e.GET(v0.PathMachineRuntimeInstances+"/:id", h.GetMachineRuntimeInstance)
	e.PATCH(v0.PathMachineRuntimeInstances+"/:id", h.UpdateMachineRuntimeInstance)
	e.PUT(v0.PathMachineRuntimeInstances+"/:id", h.ReplaceMachineRuntimeInstance)
	e.DELETE(v0.PathMachineRuntimeInstances+"/:id", h.DeleteMachineRuntimeInstance)
}
