// boilerplate generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "github.com/threeport/threeport/pkg/api-server/v0/handlers"
	v0 "github.com/threeport/threeport/pkg/api/v0"
)

// MachineWorkloadDefinitionRoutes sets up all routes for the MachineWorkloadDefinition handlers.
func MachineWorkloadDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathMachineWorkloadDefinitionVersions, h.GetMachineWorkloadDefinitionVersions)

	e.POST(v0.PathMachineWorkloadDefinitions, h.AddMachineWorkloadDefinition)
	e.GET(v0.PathMachineWorkloadDefinitions, h.GetMachineWorkloadDefinitions)
	e.GET(v0.PathMachineWorkloadDefinitions+"/:id", h.GetMachineWorkloadDefinition)
	e.PATCH(v0.PathMachineWorkloadDefinitions+"/:id", h.UpdateMachineWorkloadDefinition)
	e.PUT(v0.PathMachineWorkloadDefinitions+"/:id", h.ReplaceMachineWorkloadDefinition)
	e.DELETE(v0.PathMachineWorkloadDefinitions+"/:id", h.DeleteMachineWorkloadDefinition)
}

// MachineWorkloadInstanceRoutes sets up all routes for the MachineWorkloadInstance handlers.
func MachineWorkloadInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathMachineWorkloadInstanceVersions, h.GetMachineWorkloadInstanceVersions)

	e.POST(v0.PathMachineWorkloadInstances, h.AddMachineWorkloadInstance)
	e.GET(v0.PathMachineWorkloadInstances, h.GetMachineWorkloadInstances)
	e.GET(v0.PathMachineWorkloadInstances+"/:id", h.GetMachineWorkloadInstance)
	e.PATCH(v0.PathMachineWorkloadInstances+"/:id", h.UpdateMachineWorkloadInstance)
	e.PUT(v0.PathMachineWorkloadInstances+"/:id", h.ReplaceMachineWorkloadInstance)
	e.DELETE(v0.PathMachineWorkloadInstances+"/:id", h.DeleteMachineWorkloadInstance)
}
