// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	"os"
	"strings"
	"text/tabwriter"

	strcase "github.com/iancoleman/strcase"

	apilib "github.com/threeport/threeport/pkg/api/lib/v0"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

const (
	eventMessageTableMax = 80
	eventNameTableMax    = 40
)

// outputEventsTable produces the tabular output for the events list. Each
// element of events is a server-side aggregated bucket: Count reflects
// the number of raw rows collapsed into the bucket, EventTime is the
// oldest observation, and LastObservedTime is the newest.
func outputEventsTable(events *[]v0.Event) error {
	// configure a tabwriter so the columns align regardless of the
	// width of any individual cell's content
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "OBJECT KIND\t NAME\t REASON\t COUNT\t FIRST SEEN\t LAST SEEN\t MESSAGE")

	// track whether any note got truncated so we can hint about -o yaml
	// at the bottom of the output
	anyTruncated := false
	for _, e := range *events {
		// derive the human-readable cell values per event
		objectKind := formatEventObjectKind(&e)
		objectName := formatEventObjectName(&e)
		reason := util.DerefString(e.Reason)
		count := ""
		if e.Count != nil {
			count = fmt.Sprintf("%d", *e.Count)
		}
		firstSeen := util.GetAgeFormatted(e.EventTime)
		lastSeen := util.GetAgeFormatted(e.LastObservedTime)

		// collapse whitespace runs in the note so multi-line script
		// output renders on one row
		rawNote := util.DerefString(e.Note)
		message := strings.Join(strings.Fields(rawNote), " ")

		// truncate over-long notes so a single noisy event doesn't
		// wreck the table layout
		if len(message) > eventMessageTableMax {
			message = util.TruncateString(message, eventMessageTableMax)
			anyTruncated = true
		}

		// emit one tab-separated row through the writer; column
		// alignment is finalized at Flush() below
		fmt.Fprintln(
			writer,
			objectKind, "\t",
			objectName, "\t",
			reason, "\t",
			count, "\t",
			firstSeen, "\t",
			lastSeen, "\t",
			message,
		)
	}
	writer.Flush()

	// nudge the reader toward -o yaml when at least one note was
	// shortened so they can see the full content
	if anyTruncated {
		fmt.Println("(use -o yaml to see full note)")
	}
	return nil
}

// formatEventObjectKind renders the OBJECT KIND cell as the kebab-case form
// of the event's ObjectType. For an event with
// ObjectType="example.com/v0.RouterInstance" the result is "router-instance".
// Falls back to the raw fully qualified type on parse failure, and empty
// when ObjectType is nil.
func formatEventObjectKind(e *v0.Event) string {
	// no recorded subject - nothing to render
	rawType := util.DerefString(e.ObjectType)
	if rawType == "" {
		return ""
	}

	// parse the fully qualified type into its parts; malformed values are surfaced
	// raw so the user can still grep for them
	_, _, typeName, ok := apilib.ParseQualifiedType(rawType)
	if !ok {
		return rawType
	}

	// CamelCase -> kebab so the kind cell matches the --for and
	// --object-kind flag shape. "RouterInstance" -> "router-instance"
	return strcase.ToKebab(typeName)
}

// formatEventObjectName renders the NAME cell for an event. Prefers
// ObjectName when resolved (the common case after the events-join handler
// enriches the row); falls back to the numeric ObjectID so the user still
// has something to grep. Truncates the result to eventNameTableMax with an
// ellipsis so a long name doesn't wreck the table layout.
func formatEventObjectName(e *v0.Event) string {
	// prefer name when resolved
	if name := util.DerefString(e.ObjectName); name != "" {
		if len(name) > eventNameTableMax {
			return util.TruncateString(name, eventNameTableMax)
		}
		return name
	}

	// name wasn't resolved (lookup failed, deleted subject); fall back to
	// id so the user still has something to grep
	if e.ObjectID != nil {
		return fmt.Sprintf("%d", *e.ObjectID)
	}

	// neither name nor id present
	return ""
}
