// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	"os"
	"text/tabwriter"

	config_v0 "github.com/threeport/threeport/pkg/config/v0"
)

// outputGetv0WorkloadsCmd produces the tabular output for the
// 'get workloads' command.
func outputGetv0WorkloadsCmd(
	workloads *[]config_v0.KubernetesWorkloadConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t WORKLOAD DEFINITION\t WORKLOAD INSTANCE\t KUBERNETES RUNTIME INSTANCE\t STATUS\t AGE")
	for _, workload := range *workloads {
		kubernetesRuntimeInstanceName := ""
		if workload.Workload.KubernetesRuntimeInstance != nil &&
			workload.Workload.KubernetesRuntimeInstance.Name != nil {
			kubernetesRuntimeInstanceName = *workload.Workload.KubernetesRuntimeInstance.Name
		}
		status := ""
		if workload.Workload.Status != nil {
			status = *workload.Workload.Status
		}
		age := ""
		if workload.Workload.Age != nil {
			age = *workload.Workload.Age
		}
		fmt.Fprintln(
			writer,
			*workload.Workload.Name, "\t",
			*workload.Workload.Name, "\t",
			*workload.Workload.Name, "\t",
			kubernetesRuntimeInstanceName, "\t",
			status, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0WorkloadDefinitionsCmd produces the tabular output for the
// `get workload-definitions` command.
func outputGetv0WorkloadDefinitionsCmd(
	workloadDefinitions *[]config_v0.KubernetesWorkloadDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, workloadDefinition := range *workloadDefinitions {
		age := ""
		if workloadDefinition.KubernetesWorkloadDefinition.Age != nil {
			age = *workloadDefinition.KubernetesWorkloadDefinition.Age
		}
		fmt.Fprintln(
			writer,
			*workloadDefinition.KubernetesWorkloadDefinition.Name, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0WorkloadInstancesCmd produces the tabular output for the
// `get workload-instances` command.
func outputGetv0WorkloadInstancesCmd(
	workloadInstances *[]config_v0.KubernetesWorkloadInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t WORKLOAD DEFINITION\t KUBERNETES RUNTIME INSTANCE\t STATUS\t AGE")
	for _, workloadInstance := range *workloadInstances {
		workloadDefinitionName := ""
		if workloadInstance.KubernetesWorkloadInstance.KubernetesWorkloadDefinition != nil &&
			workloadInstance.KubernetesWorkloadInstance.KubernetesWorkloadDefinition.Name != nil {
			workloadDefinitionName = *workloadInstance.KubernetesWorkloadInstance.KubernetesWorkloadDefinition.Name
		}
		kubernetesRuntimeInstanceName := ""
		if workloadInstance.KubernetesWorkloadInstance.KubernetesRuntimeInstance != nil &&
			workloadInstance.KubernetesWorkloadInstance.KubernetesRuntimeInstance.Name != nil {
			kubernetesRuntimeInstanceName = *workloadInstance.KubernetesWorkloadInstance.KubernetesRuntimeInstance.Name
		}
		status := ""
		if workloadInstance.KubernetesWorkloadInstance.Status != nil {
			status = *workloadInstance.KubernetesWorkloadInstance.Status
		}
		age := ""
		if workloadInstance.KubernetesWorkloadInstance.Age != nil {
			age = *workloadInstance.KubernetesWorkloadInstance.Age
		}
		fmt.Fprintln(
			writer,
			*workloadInstance.KubernetesWorkloadInstance.Name, "\t",
			workloadDefinitionName, "\t",
			kubernetesRuntimeInstanceName, "\t",
			status, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}
