// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	config_v0 "github.com/threeport/threeport/pkg/config/v0"
	"os"
	"text/tabwriter"
)

// outputGetv0MachineWorkloadsCmd produces the tabular output for the
// 'get machine-workloads' command.
func outputGetv0MachineWorkloadsCmd(
	machineWorkloads *[]config_v0.MachineWorkloadConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the MachineWorkloadValues object in pkg/config/v0/machine_workload.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineWorkload := range *machineWorkloads {
		fmt.Fprintln(
			writer,
			*machineWorkload.MachineWorkload.Name, "\t",
			*machineWorkload.MachineWorkload.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0MachineWorkloadDefinitionsCmd produces the tabular output for the
// `get machine-workload-definitions` command.
func outputGetv0MachineWorkloadDefinitionsCmd(
	machineWorkloadDefinitions *[]config_v0.MachineWorkloadDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the MachineWorkloadDefinitionValues object in pkg/config/v0/machine_workload_definition.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineWorkloadDefinition := range *machineWorkloadDefinitions {
		fmt.Fprintln(
			writer,
			*machineWorkloadDefinition.MachineWorkloadDefinition.Name, "\t",
			*machineWorkloadDefinition.MachineWorkloadDefinition.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0MachineWorkloadInstancesCmd produces the tabular output for the
// `get machine-workload-instances` command.
func outputGetv0MachineWorkloadInstancesCmd(
	machineWorkloadInstances *[]config_v0.MachineWorkloadInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the MachineWorkloadInstanceValues object in pkg/config/v0/machine_workload_instance.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineWorkloadInstance := range *machineWorkloadInstances {
		fmt.Fprintln(
			writer,
			*machineWorkloadInstance.MachineWorkloadInstance.Name, "\t",
			*machineWorkloadInstance.MachineWorkloadInstance.Age,
		)
	}
	writer.Flush()

	return nil
}
