// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	config_v0 "github.com/threeport/threeport/pkg/config/v0"
	"os"
	"text/tabwriter"
)

// outputGetv0MachineRuntimesCmd produces the tabular output for the
// 'get machine-runtimes' command.
func outputGetv0MachineRuntimesCmd(
	machineRuntimes *[]config_v0.MachineRuntimeConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the MachineRuntimeValues object in pkg/config/v0/machine_runtime.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineRuntime := range *machineRuntimes {
		fmt.Fprintln(
			writer,
			*machineRuntime.MachineRuntime.Name, "\t",
			*machineRuntime.MachineRuntime.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0MachineRuntimeDefinitionsCmd produces the tabular output for the
// `get machine-runtime-definitions` command.
func outputGetv0MachineRuntimeDefinitionsCmd(
	machineRuntimeDefinitions *[]config_v0.MachineRuntimeDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the MachineRuntimeDefinitionValues object in pkg/config/v0/machine_runtime_definition.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineRuntimeDefinition := range *machineRuntimeDefinitions {
		fmt.Fprintln(
			writer,
			*machineRuntimeDefinition.MachineRuntimeDefinition.Name, "\t",
			*machineRuntimeDefinition.MachineRuntimeDefinition.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0MachineRuntimeInstancesCmd produces the tabular output for the
// `get machine-runtime-instances` command.
func outputGetv0MachineRuntimeInstancesCmd(
	machineRuntimeInstances *[]config_v0.MachineRuntimeInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the MachineRuntimeInstanceValues object in pkg/config/v0/machine_runtime_instance.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineRuntimeInstance := range *machineRuntimeInstances {
		fmt.Fprintln(
			writer,
			*machineRuntimeInstance.MachineRuntimeInstance.Name, "\t",
			*machineRuntimeInstance.MachineRuntimeInstance.Age,
		)
	}
	writer.Flush()

	return nil
}
