// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	"os"
	"text/tabwriter"

	config_v0 "github.com/threeport/threeport/pkg/config/v0"
)

// outputGetv0MachineRuntimesCmd produces the tabular output for the
// 'get machine-runtimes' command.
func outputGetv0MachineRuntimesCmd(
	machineRuntimes *[]config_v0.MachineRuntimeConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t MACHINE RUNTIME DEFINITION\t MACHINE RUNTIME INSTANCE\t HOSTNAME\t AGE")
	for _, machineRuntime := range *machineRuntimes {
		hostname := ""
		if machineRuntime.MachineRuntime.Hostname != nil {
			hostname = *machineRuntime.MachineRuntime.Hostname
		}
		age := ""
		if machineRuntime.MachineRuntime.Age != nil {
			age = *machineRuntime.MachineRuntime.Age
		}
		fmt.Fprintln(
			writer,
			*machineRuntime.MachineRuntime.Name, "\t",
			*machineRuntime.MachineRuntime.Name, "\t",
			*machineRuntime.MachineRuntime.Name, "\t",
			hostname, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0MachineRuntimeDefinitionsCmd produces the tabular output for the
// `get machine-runtime-definitions` command.
func outputGetv0MachineRuntimeDefinitionsCmd(
	machineRuntimeDefinitions *[]config_v0.MachineRuntimeDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, machineRuntimeDefinition := range *machineRuntimeDefinitions {
		age := ""
		if machineRuntimeDefinition.MachineRuntimeDefinition.Age != nil {
			age = *machineRuntimeDefinition.MachineRuntimeDefinition.Age
		}
		fmt.Fprintln(
			writer,
			*machineRuntimeDefinition.MachineRuntimeDefinition.Name, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0MachineRuntimeInstancesCmd produces the tabular output for the
// `get machine-runtime-instances` command.
func outputGetv0MachineRuntimeInstancesCmd(
	machineRuntimeInstances *[]config_v0.MachineRuntimeInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t MACHINE RUNTIME DEFINITION\t HOSTNAME\t AGE")
	for _, machineRuntimeInstance := range *machineRuntimeInstances {
		machineRuntimeDefinitionName := ""
		if machineRuntimeInstance.MachineRuntimeInstance.MachineRuntimeDefinition != nil &&
			machineRuntimeInstance.MachineRuntimeInstance.MachineRuntimeDefinition.Name != nil {
			machineRuntimeDefinitionName = *machineRuntimeInstance.MachineRuntimeInstance.MachineRuntimeDefinition.Name
		}
		hostname := ""
		if machineRuntimeInstance.MachineRuntimeInstance.Hostname != nil {
			hostname = *machineRuntimeInstance.MachineRuntimeInstance.Hostname
		}
		age := ""
		if machineRuntimeInstance.MachineRuntimeInstance.Age != nil {
			age = *machineRuntimeInstance.MachineRuntimeInstance.Age
		}
		fmt.Fprintln(
			writer,
			*machineRuntimeInstance.MachineRuntimeInstance.Name, "\t",
			machineRuntimeDefinitionName, "\t",
			hostname, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}
