// boilerplate generated by 'threeport-sdk gen' - do not edit

package versions

import (
	apiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	apiserver_v0 "github.com/threeport/threeport/pkg/api-server/v0"
	api_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	"reflect"
)

// AddAttachedObjectReferenceVersions adds field validation info and adds it
// to the REST API versions.
func AddAttachedObjectReferenceVersions() {
	apiserver_v0.AttachedObjectReferenceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.AttachedObjectReference)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.AttachedObjectReferenceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeAttachedObjectReference),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.AttachedObjectReferenceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}
