// boilerplate generated by 'threeport-sdk gen' - do not edit

package versions

import (
	apiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	apiserver_v0 "github.com/threeport/threeport/pkg/api-server/v0"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	sdk "github.com/threeport/threeport/pkg/sdk/v0"
	"reflect"
)

// AddGcpGkeKubernetesRuntimeDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddGcpGkeKubernetesRuntimeDefinitionVersions() {
	apiserver_v0.GcpGkeKubernetesRuntimeDefinitionTaggedFields[sdk.ValidateTag] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              sdk.ValidateTag,
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		sdk.ValidateTag,
		reflect.ValueOf(new(api_v0.GcpGkeKubernetesRuntimeDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.GcpGkeKubernetesRuntimeDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeGcpGkeKubernetesRuntimeDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.GcpGkeKubernetesRuntimeDefinitionTaggedFields[sdk.ValidateTag]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddGcpGkeKubernetesRuntimeInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddGcpGkeKubernetesRuntimeInstanceVersions() {
	apiserver_v0.GcpGkeKubernetesRuntimeInstanceTaggedFields[sdk.ValidateTag] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              sdk.ValidateTag,
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		sdk.ValidateTag,
		reflect.ValueOf(new(api_v0.GcpGkeKubernetesRuntimeInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.GcpGkeKubernetesRuntimeInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeGcpGkeKubernetesRuntimeInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.GcpGkeKubernetesRuntimeInstanceTaggedFields[sdk.ValidateTag]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddGcpProviderVersions adds field validation info and adds it
// to the REST API versions.
func AddGcpProviderVersions() {
	apiserver_v0.GcpProviderTaggedFields[sdk.ValidateTag] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              sdk.ValidateTag,
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		sdk.ValidateTag,
		reflect.ValueOf(new(api_v0.GcpProvider)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.GcpProviderTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeGcpProvider),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.GcpProviderTaggedFields[sdk.ValidateTag]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}
