// boilerplate generated by 'threeport-sdk gen' - do not edit

package versions

import (
	apiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	apiserver_v0 "github.com/threeport/threeport/pkg/api-server/v0"
	api_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	"reflect"
)

// AddLogBackendVersions adds field validation info and adds it
// to the REST API versions.
func AddLogBackendVersions() {
	apiserver_v0.LogBackendTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.LogBackend)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.LogBackendTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeLogBackend),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.LogBackendTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddLogStorageDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddLogStorageDefinitionVersions() {
	apiserver_v0.LogStorageDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.LogStorageDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.LogStorageDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeLogStorageDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.LogStorageDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddLogStorageInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddLogStorageInstanceVersions() {
	apiserver_v0.LogStorageInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.LogStorageInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.LogStorageInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeLogStorageInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.LogStorageInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}
