package main

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	yaml "gopkg.in/yaml.v3"
)

const (
	docsDir            = "docs"
	mkdocsConfigPath   = "docs/mkdocs.yml"
	agentsFilePath     = "AGENTS.md"
	tptctlBinaryPath   = "./bin/tptctl"
	makefilePath       = "Makefile"
	magefilesSourceDir = "magefiles"

	// The column body text wraps at. A line may run past it only inside a fence
	// or in a table row, neither of which can be wrapped without changing what
	// the reader sees.
	formatColumnLimit = 80

	// The lines the documentation map is written between. They stay in the
	// agent instructions across regenerations and everything they enclose is
	// replaced, so the map travels with the instructions rather than sitting in
	// a file only some tools know how to follow.
	agentsIndexBeginMarker = "<!-- begin boilerplate generated by 'mage dev:generateAgentsIndex' - do not edit -->"
	agentsIndexEndMarker   = "<!-- end boilerplate generated by 'mage dev:generateAgentsIndex' - do not edit -->"
)

// Commands the documentation names that have no counterpart in this
// repository. The SDK tutorial walks a reader through generating their own
// module, which brings its own build target and attaches its own plugin to the
// command line tool under a name only that reader's build knows about.
var (
	allowedTptctlCommands = []string{"wordpress"}
	allowedMageTargets    = []string{"build:plugin"}
)

// Fence languages whose contents are commands a reader is meant to type. A Go
// or YAML block can hold the same words in a comment without any of them being
// runnable, so those blocks are skipped.
var runnableFenceLanguages = []string{"", "bash", "sh", "shell"}

// The trees the format rules cover. They are the corpus the rules were measured
// from, and they are the whole of it. The published site under docs/docs is
// deliberately excluded: it is written to the documentation theme's
// conventions, which use admonition blocks, bold, and lines run to the width of
// the rendered page, so these rules report hundreds of findings there that are
// not defects. Widening this list is not a fix for that.
var formatDirs = []string{"docs/dev", "docs/design"}

var (
	fenceMarker    = regexp.MustCompile("^\\s*```")
	tptctlCall     = regexp.MustCompile(`^\s*\$?\s*tptctl ([a-z][a-z0-9-]*)(?: ([a-z][a-z0-9-]*))?`)
	makeCall       = regexp.MustCompile(`^\s*\$?\s*make ([a-zA-Z0-9][a-zA-Z0-9_-]*)`)
	mageCall       = regexp.MustCompile(`^\s*\$?\s*mage ([a-zA-Z0-9][a-zA-Z0-9:]*)`)
	makefileTarget = regexp.MustCompile(`^([a-zA-Z0-9][a-zA-Z0-9_-]*):`)
	sampleUrl      = regexp.MustCompile(`https://raw\.githubusercontent\.com/threeport/threeport/[^/]+/(samples/[^\s)"']+)`)
)

var (
	heading      = regexp.MustCompile(`^#{1,6}\s`)
	deepHeading  = regexp.MustCompile(`^#{4,}\s`)
	tableRow     = regexp.MustCompile(`^\s*\|`)
	listMarker   = regexp.MustCompile(`^\s*([-+])\s+(.*)$`)
	itemPrefix   = regexp.MustCompile(`^\s*(?:[*+-]\s+|\d+\.\s+)?`)
	checkboxItem = regexp.MustCompile(`^\[[ xX]?\]`)
	shellPrompt  = regexp.MustCompile(`^\s*\$ `)
	inlineLink   = regexp.MustCompile(`\[([^\]]*)\]\(`)

	// The number that opens an ordered list item, which puts a period, a
	// space, and a capital letter at the head of a line without any sentence
	// having ended there.
	orderedMarker = regexp.MustCompile(`^\s*\d+\.\s`)
	sentenceBreak = regexp.MustCompile("[A-Za-z0-9)\"'`]\\. [A-Z]")
)

// The characters the format rules ban outright, each with the name it is
// reported under. Written as escapes so the rule and the source that carries
// it cannot disagree about which character is meant.
var bannedCharacters = []struct {
	character rune
	name      string
}{
	{'\u2014', "em dash"},
	{'\u2013', "en dash"},
	{'\u2192', "rightwards arrow"},
	{'\u21d2', "rightwards double arrow"},
}

// Link text that names nothing, so a reader scanning for a destination learns
// only that a link exists.
var uninformativeLinkText = []string{"here", "this", "click here"}

// Docs runs every documentation check. The three it calls stay separately
// callable because each needs a different thing present: the link check needs
// the documentation toolchain, the command check needs the command line binary
// built, and the format check needs neither. Reach for one of those while
// editing, and for this before pushing.
func (Test) Docs() error {
	test := Test{}
	if err := test.DocsLinks(); err != nil {
		return err
	}

	if err := test.DocsCommands(); err != nil {
		return err
	}

	return test.DocsFormat()
}

// DocsLinks checks the documentation site for links that resolve to nothing,
// anchors that are absent from the page they point at, and pages stranded
// outside the navigation. Which of those count as failures is set by the
// validation block in the site configuration. Requires the documentation
// toolchain from docs/requirements.txt.
func (Test) DocsLinks() error {
	siteDir, err := os.MkdirTemp("", "threeport-docs")
	if err != nil {
		return fmt.Errorf("failed to create a directory for the rendered site: %w", err)
	}
	defer os.RemoveAll(siteDir)

	buildSite := exec.Command("mkdocs", "build", "--strict", "--site-dir", siteDir)
	buildSite.Dir = docsDir

	output, err := buildSite.CombinedOutput()
	if err != nil {
		return fmt.Errorf(
			"failed to build the documentation site: '%s': %w\ninstall the toolchain with: pip install -r docs/requirements.txt",
			output,
			err,
		)
	}

	fmt.Println("docs link check ran successfully")

	return nil
}

// DocsCommands checks that every command the documentation tells a reader to
// run exists, comparing what the fenced shell blocks contain against the
// command line tool's own subcommands, the Makefile's targets, and the mage
// targets declared in this directory. Requires the tptctl binary from
// build:tptctl.
func (Test) DocsCommands() error {
	if _, err := os.Stat(tptctlBinaryPath); err != nil {
		return fmt.Errorf(
			"failed to find %s: %w\nbuild it first with: mage build:tptctl",
			tptctlBinaryPath,
			err,
		)
	}

	lines, err := collectRunnableLines(docsDir)
	if err != nil {
		return fmt.Errorf("failed to read the documentation: %w", err)
	}

	problems := checkTptctlCalls(lines)

	makeTargets, err := readMakefileTargets(makefilePath)
	if err != nil {
		return fmt.Errorf("failed to read the Makefile targets: %w", err)
	}
	problems = append(problems, checkTargets(lines, makeCall, "make", makeTargets, nil)...)

	mageTargets, err := readMageTargets(magefilesSourceDir)
	if err != nil {
		return fmt.Errorf("failed to read the mage targets: %w", err)
	}
	problems = append(problems, checkTargets(lines, mageCall, "mage", mageTargets, allowedMageTargets)...)

	problems = append(problems, checkSampleFiles(lines, ".")...)

	if len(problems) > 0 {
		sort.Strings(problems)

		return fmt.Errorf(
			"docs command check failed, %d command(s) in the documentation do not exist:\n%s",
			len(problems),
			strings.Join(problems, "\n"),
		)
	}

	fmt.Println("docs command check ran successfully")

	return nil
}

// DocsFormat checks the contributor and design documentation against the
// conventions those two trees are written to: no dash or arrow characters,
// body text hard-wrapped at 80 columns, two spaces between sentences, no heading
// deeper than three levels, `*` list markers, fences that carry no shell
// prompt and never sit directly under a heading, and link text that names its
// destination. Link targets are not resolved; test:docsLinks does that for the
// published site.
func (Test) DocsFormat() error {
	problems := make([]formatProblem, 0)

	for _, dir := range formatDirs {
		found, err := checkFormatDir(dir)
		if err != nil {
			return fmt.Errorf("failed to check %s: %w", dir, err)
		}
		problems = append(problems, found...)
	}

	if len(problems) > 0 {
		sort.Slice(problems, func(first, second int) bool {
			left, right := problems[first], problems[second]
			if left.path != right.path {
				return left.path < right.path
			}
			if left.line != right.line {
				return left.line < right.line
			}
			if left.rule != right.rule {
				return left.rule < right.rule
			}

			return left.detail < right.detail
		})

		reported := make([]string, 0, len(problems))
		for _, problem := range problems {
			reported = append(reported, problem.String())
		}

		return fmt.Errorf(
			"docs format check failed, %d line(s) in the documentation break a formatting convention:\n%s",
			len(problems),
			strings.Join(reported, "\n"),
		)
	}

	fmt.Println("docs format check ran successfully")

	return nil
}

// formatProblem is one broken convention, at the line that breaks it.
type formatProblem struct {
	path   string
	line   int
	rule   string
	detail string
}

// String renders a problem for a reader who has to go and fix it, naming the
// file and line first so an editor can jump straight to it.
func (problem formatProblem) String() string {
	return fmt.Sprintf("%s:%d: %s: %s", problem.path, problem.line, problem.rule, problem.detail)
}

// checkFormatDir returns every broken convention in the markdown under the given
// directory.
func checkFormatDir(root string) ([]formatProblem, error) {
	problems := make([]formatProblem, 0)

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}

		markdown, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", path, err)
		}
		problems = append(problems, checkFormat(path, string(markdown))...)

		return nil
	})
	if err != nil {
		return nil, err
	}

	return problems, nil
}

// checkFormat returns every broken convention in one markdown file, in the order
// the lines appear. Which rules a line is held to depends on where it sits: a
// fenced block holds commands and output rather than prose, so only the rules
// about what a command may contain reach inside one, while the banned
// characters are rejected wherever they appear because a command carrying one
// is broken rather than merely styled differently.
func checkFormat(path, markdown string) []formatProblem {
	problems := make([]formatProblem, 0)
	insideFence := false
	previousNonBlank := ""

	for index, line := range strings.Split(markdown, "\n") {
		number := index + 1

		for column, character := range []rune(line) {
			for _, banned := range bannedCharacters {
				if character != banned.character {
					continue
				}

				problems = append(problems, formatProblem{
					path:   path,
					line:   number,
					rule:   "dash or arrow character",
					detail: fmt.Sprintf("%s (U+%04X) at column %d", banned.name, banned.character, column+1),
				})
			}
		}

		if fenceMarker.MatchString(line) {
			if !insideFence && heading.MatchString(previousNonBlank) {
				problems = append(problems, formatProblem{
					path:   path,
					line:   number,
					rule:   "fence lead-in",
					detail: fmt.Sprintf("fence opens directly under %q", strings.TrimSpace(previousNonBlank)),
				})
			}
			insideFence = !insideFence
			previousNonBlank = line

			continue
		}

		if insideFence {
			if shellPrompt.MatchString(line) {
				problems = append(problems, formatProblem{
					path:   path,
					line:   number,
					rule:   "prompt character",
					detail: "command carries a $ prompt",
				})
			}
		} else {
			problems = append(problems, checkFormatLine(path, number, line)...)
		}

		if strings.TrimSpace(line) != "" {
			previousNonBlank = line
		}
	}

	return problems
}

// checkFormatLine returns every broken convention on one line of prose, meaning
// a line outside any fenced block.
func checkFormatLine(path string, number int, line string) []formatProblem {
	problems := make([]formatProblem, 0)
	report := func(rule, detail string) {
		problems = append(problems, formatProblem{path: path, line: number, rule: rule, detail: detail})
	}

	// A table row is exempt from the column limit because splitting one across
	// two lines stops it being a row at all, and a line that is one indivisible
	// token is exempt because there is nowhere in it to break. Everything else
	// that runs long has a space in it and can be wrapped.
	if columns := utf8.RuneCountInString(line); columns > formatColumnLimit &&
		!tableRow.MatchString(line) && !indivisible(line) {
		report("line length", fmt.Sprintf("%d columns, wrap at %d", columns, formatColumnLimit))
	}

	if deepHeading.MatchString(line) {
		depth := len(line) - len(strings.TrimLeft(line, "#"))
		report("heading depth", fmt.Sprintf("%d levels deep, go no deeper than 3", depth))
	}

	if match := listMarker.FindStringSubmatch(line); match != nil && !checkboxItem.MatchString(match[2]) {
		report("bullet marker", fmt.Sprintf("list item opens with %s, use *", match[1]))
	}

	for _, match := range sentenceBreak.FindAllString(orderedMarker.ReplaceAllString(line, ""), -1) {
		report("sentence spacing", fmt.Sprintf("one space in %q, use two", match))
	}

	for _, match := range inlineLink.FindAllStringSubmatch(line, -1) {
		text := strings.TrimSpace(match[1])
		if containsFold(uninformativeLinkText, text) {
			report("link text", fmt.Sprintf("link text %q names no destination", text))
		}
	}

	return problems
}

// indivisible reports whether the line carries one token and nothing else,
// which is what a list item holding only a long link or path looks like. A
// break inside a link target stops it being a link, so a line with no
// whitespace left to wrap at has already been wrapped as far as it goes and
// runs past the column limit the way a table row does. A line that still has a
// space in it is not this: wrapping it moves the words that follow the link
// down a line and leaves the link itself intact.
func indivisible(line string) bool {
	content := strings.TrimSpace(itemPrefix.ReplaceAllString(line, ""))

	return content != "" && !strings.ContainsAny(content, " \t")
}

// GenerateAgentsIndex writes the documentation map into the agent
// instructions, deriving the published half from the site navigation so the map
// and the site can never disagree. The map is written between markers in the
// instructions themselves rather than into a file they link to, because the
// link syntax is one tool's extension and every other tool reading the
// instructions would get a bare file name and no map. The map stays at
// directory granularity because it is loaded on every request; anything finer
// belongs in a path-scoped rule, which costs nothing until a matching file is
// opened.
func (Dev) GenerateAgentsIndex() error {
	// Trees with no navigation of their own, described here because nothing in
	// the repository states their purpose in one line.
	unpublished := [][]string{
		{"Contributor docs", "docs/dev/", "build, test, release, SDK, and style guide"},
		{"Design proposals", "docs/design/", "accepted designs not yet folded into the site"},
	}

	navigation, err := readSiteNavigation(mkdocsConfigPath)
	if err != nil {
		return fmt.Errorf("failed to read the site navigation: %w", err)
	}

	index := []string{
		"",
		"# Documentation map",
		"",
		"Which directory covers which topic. Read the pages under a directory before",
		"changing behavior it describes, and update them in the same change.",
		"",
		"| Topic | Where |",
		"|---|---|",
	}

	for _, section := range navigation {
		locations := make([]string, 0, len(section.Locations))
		for _, location := range section.Locations {
			locations = append(locations, fmt.Sprintf("`%s`", location))
		}
		index = append(index, fmt.Sprintf("| %s | %s |", section.Title, strings.Join(locations, ", ")))
	}

	for _, tree := range unpublished {
		index = append(index, fmt.Sprintf("| %s | `%s`, %s |", tree[0], tree[1], tree[2]))
	}

	index = append(index, "")

	if err := spliceAgentsIndex(agentsFilePath, strings.Join(index, "\n")); err != nil {
		return err
	}

	fmt.Printf("documentation map written to %s\n", agentsFilePath)

	return nil
}

// spliceAgentsIndex replaces whatever sits between the two markers in the named
// file with the given block, leaving the marker lines themselves in place.
// Both markers have to be present, appear once, and be the right way round; a
// file that has lost one is reported rather than left alone, because a map that
// quietly stops being rewritten goes stale without anyone noticing.
func spliceAgentsIndex(path, block string) error {
	contents, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", path, err)
	}

	lines := strings.Split(string(contents), "\n")
	begin, end := -1, -1
	for number, line := range lines {
		switch strings.TrimSpace(line) {
		case agentsIndexBeginMarker:
			if begin >= 0 {
				return fmt.Errorf("%s carries more than one line reading %s", path, agentsIndexBeginMarker)
			}
			begin = number
		case agentsIndexEndMarker:
			if end >= 0 {
				return fmt.Errorf("%s carries more than one line reading %s", path, agentsIndexEndMarker)
			}
			end = number
		}
	}

	switch {
	case begin < 0:
		return fmt.Errorf("%s has no line reading %s, so there is nowhere to write the documentation map", path, agentsIndexBeginMarker)
	case end < 0:
		return fmt.Errorf("%s has no line reading %s, so there is nowhere to write the documentation map", path, agentsIndexEndMarker)
	case end < begin:
		return fmt.Errorf("%s carries the end marker above the begin marker, so the documentation map has no body to replace", path)
	}

	spliced := make([]string, 0, len(lines))
	spliced = append(spliced, lines[:begin+1]...)
	spliced = append(spliced, strings.Split(block, "\n")...)
	spliced = append(spliced, lines[end:]...)

	if err := os.WriteFile(path, []byte(strings.Join(spliced, "\n")), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}

	return nil
}

// navigationSection is one top-level entry in the documentation site's
// navigation, reduced to the directories its pages live in.
type navigationSection struct {
	Title     string
	Locations []string
}

// readSiteNavigation returns the site's top-level navigation sections, each
// carrying the directories its pages live in, in the order the site lists
// them. A page sitting directly in the documentation root has no directory of
// its own and is reported by file name instead.
func readSiteNavigation(configPath string) ([]navigationSection, error) {
	configBytes, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", configPath, err)
	}

	var config struct {
		Nav []yaml.Node `yaml:"nav"`
	}
	if err := yaml.Unmarshal(configBytes, &config); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", configPath, err)
	}

	sections := make([]navigationSection, 0, len(config.Nav))
	for _, entry := range config.Nav {
		// Every navigation entry is a single-key mapping of title to content.
		if entry.Kind != yaml.MappingNode || len(entry.Content) < 2 {
			continue
		}

		title := entry.Content[0].Value
		locations := make([]string, 0)
		for _, page := range collectPagePaths(entry.Content[1]) {
			location := filepath.Join(docsDir, docsDir, page)
			if directory := filepath.Dir(page); directory != "." {
				location = filepath.Join(docsDir, docsDir, directory) + "/"
			}
			if !contains(locations, location) {
				locations = append(locations, location)
			}
		}

		sections = append(sections, navigationSection{Title: title, Locations: locations})
	}

	return sections, nil
}

// collectPagePaths returns every page path under a navigation node, at any
// nesting depth.
func collectPagePaths(node *yaml.Node) []string {
	switch node.Kind {
	case yaml.ScalarNode:
		return []string{node.Value}
	case yaml.SequenceNode:
		paths := make([]string, 0)
		for _, child := range node.Content {
			paths = append(paths, collectPagePaths(child)...)
		}

		return paths
	case yaml.MappingNode:
		paths := make([]string, 0)
		// A mapping alternates key and value; only the values hold pages.
		for index := 1; index < len(node.Content); index += 2 {
			paths = append(paths, collectPagePaths(node.Content[index])...)
		}

		return paths
	}

	return nil
}

// collectRunnableLines returns every line inside a fenced code block whose
// language marks it as commands a reader is meant to type, across all markdown
// under the given directory.
func collectRunnableLines(root string) ([]string, error) {
	lines := make([]string, 0)

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}

		fileLines, err := readRunnableLines(path)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", path, err)
		}
		lines = append(lines, fileLines...)

		return nil
	})
	if err != nil {
		return nil, err
	}

	return lines, nil
}

// readRunnableLines returns the lines of one markdown file that sit inside a
// runnable fenced block. Being inside a fence is tracked separately from
// having chosen to read it, because a closing fence carries no language and
// would otherwise read as the start of a shell block.
func readRunnableLines(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	lines := make([]string, 0)
	insideFence := false
	reading := false

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()

		if fenceMarker.MatchString(line) {
			if insideFence {
				insideFence = false
				reading = false

				continue
			}

			insideFence = true
			language := strings.TrimSpace(fenceMarker.ReplaceAllString(line, ""))
			reading = contains(runnableFenceLanguages, language)

			continue
		}

		if reading {
			lines = append(lines, line)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return lines, nil
}

// checkTptctlCalls returns one message per documented command line tool
// invocation that the tool itself does not offer.
func checkTptctlCalls(lines []string) []string {
	problems := make([]string, 0)
	rootCommands := readTptctlSubcommands()
	seen := make(map[string]bool)

	for _, line := range lines {
		match := tptctlCall.FindStringSubmatch(line)
		if match == nil {
			continue
		}

		command, object := match[1], match[2]
		if contains(allowedTptctlCommands, command) {
			continue
		}

		invocation := strings.TrimSpace(command + " " + object)
		if seen[invocation] {
			continue
		}
		seen[invocation] = true

		if !contains(rootCommands, command) {
			problems = append(problems, fmt.Sprintf("tptctl %s: no such command", command))

			continue
		}

		if object == "" {
			continue
		}

		// A command that offers no subcommands is driven entirely by flags, so
		// a bare word after it is swallowed as a stray argument and the reader
		// never gets what the page promised.
		objectTypes := readTptctlSubcommands(command)
		if len(objectTypes) == 0 {
			problems = append(
				problems,
				fmt.Sprintf("tptctl %s %s: %s takes no subcommands", command, object, command),
			)

			continue
		}

		if !contains(objectTypes, object) {
			problems = append(problems, fmt.Sprintf("tptctl %s %s: no such object type", command, object))
		}
	}

	return problems
}

// readTptctlSubcommands returns the subcommand names the given command offers,
// and nothing when it takes no subcommands. Asking the binary rather than
// listing the commands here means a rename is caught the moment the tool
// changes, and this check never carries a second copy of the command tree.
func readTptctlSubcommands(command ...string) []string {
	output, err := exec.Command(tptctlBinaryPath, append(command, "--help")...).CombinedOutput()
	if err != nil {
		return nil
	}

	names := make([]string, 0)
	inCommandList := false
	for _, line := range strings.Split(string(output), "\n") {
		if strings.HasPrefix(line, "Available Commands:") {
			inCommandList = true

			continue
		}
		if !inCommandList {
			continue
		}
		if strings.TrimSpace(line) == "" {
			break
		}
		names = append(names, strings.Fields(line)[0])
	}

	return names
}

// checkTargets returns one message per documented build target that the build
// system does not declare. Target names are compared case-insensitively,
// because the documentation and the source disagree on casing without either
// being wrong.
func checkTargets(lines []string, call *regexp.Regexp, tool string, declared, allowed []string) []string {
	problems := make([]string, 0)
	seen := make(map[string]bool)

	for _, line := range lines {
		match := call.FindStringSubmatch(line)
		if match == nil {
			continue
		}

		target := match[1]
		lowered := strings.ToLower(target)
		if seen[lowered] {
			continue
		}
		seen[lowered] = true

		if containsFold(allowed, target) || containsFold(declared, target) {
			continue
		}

		problems = append(problems, fmt.Sprintf("%s %s: no such target", tool, target))
	}

	return problems
}

// checkSampleFiles returns one message per sample file the documentation tells
// a reader to download that this repository does not carry. The download URL
// names a branch, so a sample renamed here keeps resolving against whichever
// branch the URL happens to name until a reader follows the guide and finds
// the config no longer matches what the page describes. Checking the path
// against the tree catches the rename instead of waiting for the branches to
// converge, and needs no network.
func checkSampleFiles(lines []string, repoRoot string) []string {
	problems := make([]string, 0)
	seen := make(map[string]bool)

	for _, line := range lines {
		match := sampleUrl.FindStringSubmatch(line)
		if match == nil {
			continue
		}

		samplePath := match[1]
		if seen[samplePath] {
			continue
		}
		seen[samplePath] = true

		if _, err := os.Stat(filepath.Join(repoRoot, samplePath)); err != nil {
			problems = append(problems, fmt.Sprintf("%s: no such sample in this repository", samplePath))
		}
	}

	return problems
}

// readMakefileTargets returns the target names the Makefile declares.
func readMakefileTargets(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	targets := make([]string, 0)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		if match := makefileTarget.FindStringSubmatch(scanner.Text()); match != nil {
			targets = append(targets, match[1])
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return targets, nil
}

// readMageTargets returns the namespaced target names declared in the given
// directory, as mage exposes them. Reading the source rather than shelling out
// to the build tool keeps the check working when the tool is absent, and
// avoids a build system that has to run in order to describe itself.
func readMageTargets(sourceDir string) ([]string, error) {
	fileSet := token.NewFileSet()
	packages, err := parser.ParseDir(fileSet, sourceDir, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", sourceDir, err)
	}

	targets := make([]string, 0)
	for _, pkg := range packages {
		for _, file := range pkg.Files {
			for _, declaration := range file.Decls {
				function, isFunction := declaration.(*ast.FuncDecl)
				if !isFunction || function.Recv == nil || len(function.Recv.List) != 1 {
					continue
				}
				if !function.Name.IsExported() {
					continue
				}

				namespace, isIdentifier := function.Recv.List[0].Type.(*ast.Ident)
				if !isIdentifier {
					continue
				}

				targets = append(targets, fmt.Sprintf("%s:%s", namespace.Name, function.Name.Name))
			}
		}
	}

	return targets, nil
}

// contains reports whether the slice holds the value exactly.
func contains(values []string, value string) bool {
	for _, candidate := range values {
		if candidate == value {
			return true
		}
	}

	return false
}

// containsFold reports whether the slice holds the value, ignoring case.
func containsFold(values []string, value string) bool {
	for _, candidate := range values {
		if strings.EqualFold(candidate, value) {
			return true
		}
	}

	return false
}
