#!/usr/bin/env python3

"""Emit the documentation map that the agent instructions import.

The map answers one question: which directory covers a given topic. It stays at
directory granularity on purpose, because it is loaded on every request and a
per-page listing would cost far more than it returns. Anything finer belongs in
a path-scoped rule, which costs nothing until a matching file is opened.

The published half is read out of the navigation in mkdocs.yml so the map and
the site can never disagree. The unpublished trees are listed separately, since
they have no navigation to read.
"""

import os
import sys

import yaml

DOCS_DIR = os.path.dirname(os.path.abspath(__file__))
MKDOCS_CONFIG = os.path.join(DOCS_DIR, "mkdocs.yml")
OUTPUT = os.path.join(DOCS_DIR, "agents-index.md")

# Trees that carry no navigation of their own, described here because nothing
# in the repository states their purpose in one line.
UNPUBLISHED = [
    ("Contributor docs", "docs/dev/", "build, test, release, SDK, and style guide"),
    ("Design proposals", "docs/design/", "accepted designs not yet folded into the site"),
]


def leaf_paths(node):
    """Yield every page path under a navigation node, at any nesting depth."""
    if isinstance(node, str):
        yield node
    elif isinstance(node, list):
        for child in node:
            yield from leaf_paths(child)
    elif isinstance(node, dict):
        for child in node.values():
            yield from leaf_paths(child)


def directories_for(node):
    """Return the directories a navigation node's pages live in, in order.

    A page sitting directly in the documentation root has no directory of its
    own, so it is reported by file name instead.
    """
    seen = []
    for path in leaf_paths(node):
        directory = os.path.dirname(path)
        entry = f"docs/docs/{directory}/" if directory else f"docs/docs/{path}"
        if entry not in seen:
            seen.append(entry)
    return seen


def main():
    with open(MKDOCS_CONFIG, encoding="utf-8") as config_file:
        config = yaml.safe_load(config_file)

    nav = config.get("nav")
    if not nav:
        print(f"no nav found in {MKDOCS_CONFIG}", file=sys.stderr)
        return 1

    lines = [
        "<!-- generated by 'mage dev:generateAgentsIndex' - do not edit -->",
        "",
        "# Documentation map",
        "",
        "Which directory covers which topic. Read the pages under a directory before",
        "changing behavior it describes, and update them in the same change.",
        "",
        "| Topic | Where |",
        "|---|---|",
    ]

    for section in nav:
        for title, node in section.items():
            where = ", ".join(f"`{directory}`" for directory in directories_for(node))
            lines.append(f"| {title} | {where} |")

    for title, directory, note in UNPUBLISHED:
        lines.append(f"| {title} | `{directory}`, {note} |")

    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as output_file:
        output_file.write("\n".join(lines))

    print(f"documentation map written to {os.path.relpath(OUTPUT, os.getcwd())}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
