// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// GcpGceMachineRuntimeDefinitionConfig is a config abstraction for the GcpGceMachineRuntimeDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type GcpGceMachineRuntimeDefinitionConfig struct {
	GcpGceMachineRuntimeDefinition GcpGceMachineRuntimeDefinitionValues
}

// GcpGceMachineRuntimeDefinitionValues contains all the attributes needed to manage
// the GcpGceMachineRuntimeDefinition API object.
type GcpGceMachineRuntimeDefinitionValues struct {
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeDefinition
	Name *string `json:",omitempty"`
	Age  *string `json:",omitempty"`
}

// Get gets gcp gce machine runtime definitions from the Threeport API.
func (g *GcpGceMachineRuntimeDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GcpGceMachineRuntimeDefinitionConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeDefinition
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeDefinition

	// get API objects
	// get all gcp gce machine runtime definitions
	gcpGceMachineRuntimeDefinitions, err := client_v0.GetGcpGceMachineRuntimeDefinitions(apiClient, apiEndpoint)
	if err != nil {
		return nil, fmt.Errorf("failed to get gcp gce machine runtime definitions from Threeport API: %w", err)
	}

	// assemble config objects from API objects
	var gcpGceMachineRuntimeDefinitionConfigs []GcpGceMachineRuntimeDefinitionConfig
	for _, gcpGceMachineRuntimeDefinition := range *gcpGceMachineRuntimeDefinitions {
		// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeDefinition
		gcpGceMachineRuntimeDefinitionConfig := GcpGceMachineRuntimeDefinitionConfig{
			GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
				Age: util.Ptr(util.GetAgeFormatted(gcpGceMachineRuntimeDefinition.CreatedAt))},
		}
		gcpGceMachineRuntimeDefinitionConfigs = append(gcpGceMachineRuntimeDefinitionConfigs, gcpGceMachineRuntimeDefinitionConfig)
	}

	return &gcpGceMachineRuntimeDefinitionConfigs, nil
}

// Create creates a gcp gce machine runtime definition in the Threeport API.
func (g *GcpGceMachineRuntimeDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*GcpGceMachineRuntimeDefinitionConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeDefinition
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeDefinition

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for gcp gce machine runtime definition: %w", err)
	}

	// construct gcp gce machine runtime definition object
	// TODO: add API object fields as needed for GcpGceMachineRuntimeDefinition
	gcpGceMachineRuntimeDefinition := api_v0.GcpGceMachineRuntimeDefinition{}

	// create gcp gce machine runtime definition
	createdGcpGceMachineRuntimeDefinition, err := client_v0.CreateGcpGceMachineRuntimeDefinition(
		apiClient,
		apiEndpoint,
		&gcpGceMachineRuntimeDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create gcp gce machine runtime definition in threeport API: %w", err)
	}

	// construct gcp gce machine runtime definition config
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeDefinition
	createdGcpGceMachineRuntimeDefinitionConfig := &GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
			Age: util.Ptr(util.GetAgeFormatted(createdGcpGceMachineRuntimeDefinition.CreatedAt)),
		},
	}

	return createdGcpGceMachineRuntimeDefinitionConfig, nil
}

// Replace updates the entire gcp gce machine runtime definition object in the Threeport API.
// This is a full replacement of all fields in the gcp gce machine runtime definition object.
func (g *GcpGceMachineRuntimeDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	// NOTE: GcpGceMachineRuntimeDefinition has no name field,
	name string, // TODO: replace name with another parameter that can uniquely identify a gcp gce machine runtime definition,
) (*GcpGceMachineRuntimeDefinitionConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeDefinition
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeDefinition

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("invalid gcp gce machine runtime definition config: %w", err)
	}

	// get existing gcp gce machine runtime definition
	existingGcpGceMachineRuntimeDefinitions, err := client_v0.GetGcpGceMachineRuntimeDefinitionsByQueryString(
		apiClient,
		apiEndpoint,
		fmt.Sprintf("name=%s", name), // TODO: replace name with another parameter that can uniquely identify a gcp gce machine runtime definition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gcp gce machine runtime definition with name %s: %w", name, err)
	}
	// TODO: add check for zero or multiple gcp gce machine runtime definitions found

	// construct updated gcp gce machine runtime definition object
	// TODO: add API object fields as needed for GcpGceMachineRuntimeDefinition
	updatedGcpGceMachineRuntimeDefinition := &api_v0.GcpGceMachineRuntimeDefinition{
		Common: api_v0.Common{
			ID: (*existingGcpGceMachineRuntimeDefinitions)[0].ID,
		},
	}

	// replace gcp gce machine runtime definition
	replacedGcpGceMachineRuntimeDefinition, err := client_v0.ReplaceGcpGceMachineRuntimeDefinition(
		apiClient,
		apiEndpoint,
		updatedGcpGceMachineRuntimeDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace gcp gce machine runtime definition in threeport API: %w", err)
	}

	// construct updated gcp gce machine runtime definition config
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeDefinition
	updatedGcpGceMachineRuntimeDefinitionConfig := &GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
			Age: util.Ptr(util.GetAgeFormatted(replacedGcpGceMachineRuntimeDefinition.CreatedAt)),
		},
	}

	return updatedGcpGceMachineRuntimeDefinitionConfig, nil
}

// Delete deletes a gcp gce machine runtime definition from the Threeport API.
func (g *GcpGceMachineRuntimeDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*GcpGceMachineRuntimeDefinitionConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeDefinition
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeDefinition

	// get gcp gce machine runtime definition
	gcpGceMachineRuntimeDefinition, err := client_v0.GetGcpGceMachineRuntimeDefinitionsByQueryString(
		apiClient,
		apiEndpoint,
		fmt.Sprintf("name=%s", "value"), // TODO: replace name with another parameter that can uniquely identify a gcp gce machine runtime definition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gcp gce machine runtime definition: %w", err)
	}
	// TODO: add check for zero or multiple gcp gce machine runtime definitions found

	// delete gcp gce machine runtime definition
	_, err = client_v0.DeleteGcpGceMachineRuntimeDefinition(
		apiClient,
		apiEndpoint,
		*(*gcpGceMachineRuntimeDefinition)[0].ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete gcp gce machine runtime definition from Threeport API: %w", err)
	}

	// construct deleted gcp gce machine runtime definition config
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeDefinition
	deletedGcpGceMachineRuntimeDefinitionConfig := &GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{},
	}

	return deletedGcpGceMachineRuntimeDefinitionConfig, nil
}

// Validate validates inputs to create gcp gce machine runtime definitions.
func (g *GcpGceMachineRuntimeDefinitionConfig) Validate() error {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeDefinition
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeDefinition
	multiError := util.MultiError{}

	// TODO: add additional validation as needed

	return multiError.Error()
}
