// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// GcpGceMachineRuntimeInstanceConfig is a config abstraction for the GcpGceMachineRuntimeInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type GcpGceMachineRuntimeInstanceConfig struct {
	GcpGceMachineRuntimeInstance GcpGceMachineRuntimeInstanceValues
}

// GcpGceMachineRuntimeInstanceValues contains all the attributes needed to manage
// the GcpGceMachineRuntimeInstance API object.
type GcpGceMachineRuntimeInstanceValues struct {
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeInstance
	Name                           *string                               `json:",omitempty"`
	GcpGceMachineRuntimeDefinition *GcpGceMachineRuntimeDefinitionValues `json:",omitempty"`
	Age                            *string                               `json:",omitempty"`
}

// Get gets gcp gce machine runtime instances from the Threeport API.
func (g *GcpGceMachineRuntimeInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GcpGceMachineRuntimeInstanceConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeInstance
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeInstance

	// get API objects
	// get all gcp gce machine runtime instances
	gcpGceMachineRuntimeInstances, err := client_v0.GetGcpGceMachineRuntimeInstances(apiClient, apiEndpoint)
	if err != nil {
		return nil, fmt.Errorf("failed to get gcp gce machine runtime instances from Threeport API: %w", err)
	}

	// assemble config objects from API objects
	var gcpGceMachineRuntimeInstanceConfigs []GcpGceMachineRuntimeInstanceConfig
	for _, gcpGceMachineRuntimeInstance := range *gcpGceMachineRuntimeInstances {
		// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeInstance
		gcpGceMachineRuntimeInstanceConfig := GcpGceMachineRuntimeInstanceConfig{
			GcpGceMachineRuntimeInstance: GcpGceMachineRuntimeInstanceValues{
				Age: util.Ptr(util.GetAgeFormatted(gcpGceMachineRuntimeInstance.CreatedAt))},
		}
		gcpGceMachineRuntimeInstanceConfigs = append(gcpGceMachineRuntimeInstanceConfigs, gcpGceMachineRuntimeInstanceConfig)
	}

	return &gcpGceMachineRuntimeInstanceConfigs, nil
}

// Create creates a gcp gce machine runtime instance in the Threeport API.
func (g *GcpGceMachineRuntimeInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*GcpGceMachineRuntimeInstanceConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeInstance
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeInstance

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for gcp gce machine runtime instance: %w", err)
	}

	// construct gcp gce machine runtime instance object
	// TODO: add API object fields as needed for GcpGceMachineRuntimeInstance
	gcpGceMachineRuntimeInstance := api_v0.GcpGceMachineRuntimeInstance{}

	// create gcp gce machine runtime instance
	createdGcpGceMachineRuntimeInstance, err := client_v0.CreateGcpGceMachineRuntimeInstance(
		apiClient,
		apiEndpoint,
		&gcpGceMachineRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create gcp gce machine runtime instance in threeport API: %w", err)
	}

	// construct gcp gce machine runtime instance config
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeInstance
	createdGcpGceMachineRuntimeInstanceConfig := &GcpGceMachineRuntimeInstanceConfig{
		GcpGceMachineRuntimeInstance: GcpGceMachineRuntimeInstanceValues{
			Age: util.Ptr(util.GetAgeFormatted(createdGcpGceMachineRuntimeInstance.CreatedAt)),
		},
	}

	return createdGcpGceMachineRuntimeInstanceConfig, nil
}

// Replace updates the entire gcp gce machine runtime instance object in the Threeport API.
// This is a full replacement of all fields in the gcp gce machine runtime instance object.
func (g *GcpGceMachineRuntimeInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	// NOTE: GcpGceMachineRuntimeInstance has no name field,
	name string, // TODO: replace name with another parameter that can uniquely identify a gcp gce machine runtime instance,
) (*GcpGceMachineRuntimeInstanceConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeInstance
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeInstance

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("invalid gcp gce machine runtime instance config: %w", err)
	}

	// get existing gcp gce machine runtime instance
	existingGcpGceMachineRuntimeInstances, err := client_v0.GetGcpGceMachineRuntimeInstancesByQueryString(
		apiClient,
		apiEndpoint,
		fmt.Sprintf("name=%s", name), // TODO: replace name with another parameter that can uniquely identify a gcp gce machine runtime instance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gcp gce machine runtime instance with name %s: %w", name, err)
	}
	// TODO: add check for zero or multiple gcp gce machine runtime instances found

	// construct updated gcp gce machine runtime instance object
	// TODO: add API object fields as needed for GcpGceMachineRuntimeInstance
	updatedGcpGceMachineRuntimeInstance := &api_v0.GcpGceMachineRuntimeInstance{
		Common: api_v0.Common{
			ID: (*existingGcpGceMachineRuntimeInstances)[0].ID,
		},
	}

	// replace gcp gce machine runtime instance
	replacedGcpGceMachineRuntimeInstance, err := client_v0.ReplaceGcpGceMachineRuntimeInstance(
		apiClient,
		apiEndpoint,
		updatedGcpGceMachineRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace gcp gce machine runtime instance in threeport API: %w", err)
	}

	// construct updated gcp gce machine runtime instance config
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeInstance
	updatedGcpGceMachineRuntimeInstanceConfig := &GcpGceMachineRuntimeInstanceConfig{
		GcpGceMachineRuntimeInstance: GcpGceMachineRuntimeInstanceValues{
			Age: util.Ptr(util.GetAgeFormatted(replacedGcpGceMachineRuntimeInstance.CreatedAt)),
		},
	}

	return updatedGcpGceMachineRuntimeInstanceConfig, nil
}

// Delete deletes a gcp gce machine runtime instance from the Threeport API.
func (g *GcpGceMachineRuntimeInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*GcpGceMachineRuntimeInstanceConfig, error) {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeInstance
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeInstance

	// get gcp gce machine runtime instance
	gcpGceMachineRuntimeInstance, err := client_v0.GetGcpGceMachineRuntimeInstancesByQueryString(
		apiClient,
		apiEndpoint,
		fmt.Sprintf("name=%s", "value"), // TODO: replace name with another parameter that can uniquely identify a gcp gce machine runtime instance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gcp gce machine runtime instance: %w", err)
	}
	// TODO: add check for zero or multiple gcp gce machine runtime instances found

	// delete gcp gce machine runtime instance
	_, err = client_v0.DeleteGcpGceMachineRuntimeInstance(
		apiClient,
		apiEndpoint,
		*(*gcpGceMachineRuntimeInstance)[0].ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete gcp gce machine runtime instance from Threeport API: %w", err)
	}

	// construct deleted gcp gce machine runtime instance config
	// TODO: add config abstraction fields needed for user to manage a GcpGceMachineRuntimeInstance
	deletedGcpGceMachineRuntimeInstanceConfig := &GcpGceMachineRuntimeInstanceConfig{
		GcpGceMachineRuntimeInstance: GcpGceMachineRuntimeInstanceValues{},
	}

	return deletedGcpGceMachineRuntimeInstanceConfig, nil
}

// Validate validates inputs to create gcp gce machine runtime instances.
func (g *GcpGceMachineRuntimeInstanceConfig) Validate() error {
	// TODO: use the config abstraction values once the GcpGceMachineRuntimeInstance
	// fields are filled in above; for now the scaffold leaves this unreferenced.
	_ = g.GcpGceMachineRuntimeInstance
	multiError := util.MultiError{}

	// TODO: add additional validation as needed

	return multiError.Error()
}
