// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"errors"
	"fmt"
	"net/http"

	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// GcpGceMachineRuntimeDefinitionConfig is a config abstraction for the GcpGceMachineRuntimeDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type GcpGceMachineRuntimeDefinitionConfig struct {
	GcpGceMachineRuntimeDefinition GcpGceMachineRuntimeDefinitionValues
}

// GcpGceMachineRuntimeDefinitionValues contains all the attributes needed to manage
// the GcpGceMachineRuntimeDefinition API object.
type GcpGceMachineRuntimeDefinitionValues struct {
	Name        *string `json:",omitempty"`
	MachineType *string `json:",omitempty"`
	ImageID     *string `json:",omitempty"`
	Age         *string `json:",omitempty"`
}

// Get gets gcp gce machine runtime definitions from the Threeport API.
// If the name is set in the GcpGceMachineRuntimeDefinitionValues, it will return the gcp gce machine runtime definition with that name.
// If the name is not set, it will return all gcp gce machine runtime definitions.
func (g *GcpGceMachineRuntimeDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GcpGceMachineRuntimeDefinitionConfig, error) {
	gcpGceMachineRuntimeDefinitionValues := g.GcpGceMachineRuntimeDefinition

	// get API objects
	var gcpGceMachineRuntimeDefinitions *[]api_v0.GcpGceMachineRuntimeDefinition
	switch {
	// if name is provided, get gcp gce machine runtime definition by name
	case gcpGceMachineRuntimeDefinitionValues.Name != nil:
		gcpGceMachineRuntimeDefinition, err := client_v0.GetGcpGceMachineRuntimeDefinitionByName(apiClient, apiEndpoint, *gcpGceMachineRuntimeDefinitionValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get gcp gce machine runtime definition with name %s: %w", *gcpGceMachineRuntimeDefinitionValues.Name, err)
		}
		gcpGceMachineRuntimeDefinitions = &[]api_v0.GcpGceMachineRuntimeDefinition{*gcpGceMachineRuntimeDefinition}
	// get all gcp gce machine runtime definitions
	default:
		allGcpGceMachineRuntimeDefinitions, err := client_v0.GetGcpGceMachineRuntimeDefinitions(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get gcp gce machine runtime definitions from Threeport API: %w", err)
		}
		gcpGceMachineRuntimeDefinitions = allGcpGceMachineRuntimeDefinitions
	}

	// assemble config objects from API objects
	var gcpGceMachineRuntimeDefinitionConfigs []GcpGceMachineRuntimeDefinitionConfig
	for _, gcpGceMachineRuntimeDefinition := range *gcpGceMachineRuntimeDefinitions {
		gcpGceMachineRuntimeDefinitionConfig := GcpGceMachineRuntimeDefinitionConfig{
			GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
				Name:        gcpGceMachineRuntimeDefinition.Name,
				MachineType: gcpGceMachineRuntimeDefinition.MachineType,
				ImageID:     gcpGceMachineRuntimeDefinition.ImageID,
				Age:         util.Ptr(util.GetAgeFormatted(gcpGceMachineRuntimeDefinition.CreatedAt)),
			},
		}
		gcpGceMachineRuntimeDefinitionConfigs = append(gcpGceMachineRuntimeDefinitionConfigs, gcpGceMachineRuntimeDefinitionConfig)
	}

	return &gcpGceMachineRuntimeDefinitionConfigs, nil
}

// Create creates a gcp gce machine runtime definition in the Threeport API.
func (g *GcpGceMachineRuntimeDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*GcpGceMachineRuntimeDefinitionConfig, error) {
	gcpGceMachineRuntimeDefinitionValues := g.GcpGceMachineRuntimeDefinition

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for gcp gce machine runtime definition with name %s: %w", *gcpGceMachineRuntimeDefinitionValues.Name, err)
	}

	// construct machine runtime definition that the GCE definition marries; the
	// GCE provisioning template fields are duplicated onto it so generic machine
	// tooling can read them without a GCE-specific lookup.
	machineRuntimeDefinition := api_v0.MachineRuntimeDefinition{
		Definition: api_v0.Definition{
			Name: gcpGceMachineRuntimeDefinitionValues.Name,
		},
		InfraProvider: util.Ptr("gce"),
		MachineType:   gcpGceMachineRuntimeDefinitionValues.MachineType,
		ImageID:       gcpGceMachineRuntimeDefinitionValues.ImageID,
	}

	// create machine runtime definition
	createdMachineRuntimeDefinition, err := client_v0.CreateMachineRuntimeDefinition(apiClient, apiEndpoint, &machineRuntimeDefinition)
	if err != nil {
		return nil, fmt.Errorf("failed to create new machine runtime definition for GCP GCE definition: %w", err)
	}

	// construct GCP GCE machine runtime definition object
	gcpGceMachineRuntimeDefinition := api_v0.GcpGceMachineRuntimeDefinition{
		Definition: api_v0.Definition{
			Name: gcpGceMachineRuntimeDefinitionValues.Name,
		},
		MachineType:                gcpGceMachineRuntimeDefinitionValues.MachineType,
		ImageID:                    gcpGceMachineRuntimeDefinitionValues.ImageID,
		MachineRuntimeDefinitionID: createdMachineRuntimeDefinition.ID,
	}

	// create gcp gce machine runtime definition
	createdGcpGceMachineRuntimeDefinition, err := client_v0.CreateGcpGceMachineRuntimeDefinition(
		apiClient,
		apiEndpoint,
		&gcpGceMachineRuntimeDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create gcp gce machine runtime definition in threeport API: %w", err)
	}

	// construct gcp gce machine runtime definition config
	createdGcpGceMachineRuntimeDefinitionConfig := &GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
			Age:         util.Ptr(util.GetAgeFormatted(createdGcpGceMachineRuntimeDefinition.CreatedAt)),
			Name:        createdGcpGceMachineRuntimeDefinition.Name,
			MachineType: createdGcpGceMachineRuntimeDefinition.MachineType,
			ImageID:     createdGcpGceMachineRuntimeDefinition.ImageID,
		},
	}

	return createdGcpGceMachineRuntimeDefinitionConfig, nil
}

// Replace updates the entire gcp gce machine runtime definition object in the Threeport API.
// This is a full replacement of all fields in the gcp gce machine runtime definition object.
// This function takes a name parameter to identify the gcp gce machine runtime definition to replace.
// This allows a different name to be provided in the values object for name changes.
func (g *GcpGceMachineRuntimeDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*GcpGceMachineRuntimeDefinitionConfig, error) {
	gcpGceMachineRuntimeDefinitionValues := g.GcpGceMachineRuntimeDefinition

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("invalid gcp gce machine runtime definition config: %w", err)
	}

	// get existing gcp gce machine runtime definition by name
	existingGcpGceMachineRuntimeDefinition, err := client_v0.GetGcpGceMachineRuntimeDefinitionByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gcp gce machine runtime definition with name %s: %w", name, err)
	}

	// construct updated gcp gce machine runtime definition object
	updatedGcpGceMachineRuntimeDefinition := &api_v0.GcpGceMachineRuntimeDefinition{
		Common: api_v0.Common{
			ID: existingGcpGceMachineRuntimeDefinition.ID,
		},
		Definition: api_v0.Definition{
			Name: gcpGceMachineRuntimeDefinitionValues.Name,
		},
		MachineType:                gcpGceMachineRuntimeDefinitionValues.MachineType,
		ImageID:                    gcpGceMachineRuntimeDefinitionValues.ImageID,
		MachineRuntimeDefinitionID: existingGcpGceMachineRuntimeDefinition.MachineRuntimeDefinitionID,
	}

	// replace gcp gce machine runtime definition
	replacedGcpGceMachineRuntimeDefinition, err := client_v0.ReplaceGcpGceMachineRuntimeDefinition(
		apiClient,
		apiEndpoint,
		updatedGcpGceMachineRuntimeDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace gcp gce machine runtime definition in threeport API: %w", err)
	}

	// construct updated gcp gce machine runtime definition config
	updatedGcpGceMachineRuntimeDefinitionConfig := &GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
			Age:         util.Ptr(util.GetAgeFormatted(replacedGcpGceMachineRuntimeDefinition.CreatedAt)),
			Name:        replacedGcpGceMachineRuntimeDefinition.Name,
			MachineType: replacedGcpGceMachineRuntimeDefinition.MachineType,
			ImageID:     replacedGcpGceMachineRuntimeDefinition.ImageID,
		},
	}

	return updatedGcpGceMachineRuntimeDefinitionConfig, nil
}

// Delete deletes a gcp gce machine runtime definition from the Threeport API.
func (g *GcpGceMachineRuntimeDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*GcpGceMachineRuntimeDefinitionConfig, error) {
	gcpGceMachineRuntimeDefinitionValues := g.GcpGceMachineRuntimeDefinition

	// get gcp gce machine runtime definition by name
	gcpGceMachineRuntimeDefinition, err := client_v0.GetGcpGceMachineRuntimeDefinitionByName(
		apiClient,
		apiEndpoint,
		*gcpGceMachineRuntimeDefinitionValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gcp gce machine runtime definition with name %s: %w", *gcpGceMachineRuntimeDefinitionValues.Name, err)
	}

	// delete associated machine runtime definition
	if gcpGceMachineRuntimeDefinition.MachineRuntimeDefinitionID != nil {
		_, err = client_v0.DeleteMachineRuntimeDefinition(
			apiClient,
			apiEndpoint,
			*gcpGceMachineRuntimeDefinition.MachineRuntimeDefinitionID,
		)
		if err != nil && !errors.Is(err, client_lib.ErrObjectNotFound) {
			return nil, fmt.Errorf("failed to delete associated machine runtime definition: %w", err)
		}
	}

	// delete gcp gce machine runtime definition
	deletedGcpGceMachineRuntimeDefinition, err := client_v0.DeleteGcpGceMachineRuntimeDefinition(
		apiClient,
		apiEndpoint,
		*gcpGceMachineRuntimeDefinition.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete gcp gce machine runtime definition from Threeport API: %w", err)
	}

	// construct deleted gcp gce machine runtime definition config
	deletedGcpGceMachineRuntimeDefinitionConfig := &GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
			Name:        deletedGcpGceMachineRuntimeDefinition.Name,
			MachineType: deletedGcpGceMachineRuntimeDefinition.MachineType,
			ImageID:     deletedGcpGceMachineRuntimeDefinition.ImageID,
		},
	}

	return deletedGcpGceMachineRuntimeDefinitionConfig, nil
}

// Validate validates inputs to create gcp gce machine runtime definitions.
func (g *GcpGceMachineRuntimeDefinitionConfig) Validate() error {
	gcpGceMachineRuntimeDefinitionValues := g.GcpGceMachineRuntimeDefinition
	multiError := util.MultiError{}

	// ensure name is set
	if gcpGceMachineRuntimeDefinitionValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// ensure machine type is set
	if gcpGceMachineRuntimeDefinitionValues.MachineType == nil {
		multiError.AppendError(errors.New("missing required field in config: MachineType"))
	}

	// ensure image identifier is set
	if gcpGceMachineRuntimeDefinitionValues.ImageID == nil {
		multiError.AppendError(errors.New("missing required field in config: ImageID"))
	}

	return multiError.Error()
}
