// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	"net/http"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// GcpGceMachineRuntimeConfig is a container for a GcpGceMachineRuntime which is a config abstraction for
// the GcpGceMachineRuntimeDefinition and GcpGceMachineRuntimeInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type GcpGceMachineRuntimeConfig struct {
	GcpGceMachineRuntime GcpGceMachineRuntimeValues
}

// GcpGceMachineRuntimeValues contains all the attributes needed to manage the
// GcpGceMachineRuntimeDefinition and GcpGceMachineRuntimeInstance API objects
// together with a single operation.
type GcpGceMachineRuntimeValues struct {
	Name            *string `json:",omitempty"`
	GcpProviderName *string `json:",omitempty"`
	Region          *string `json:",omitempty"`
	Zone            *string `json:",omitempty"`
	NetworkID       *string `json:",omitempty"`
	SSHUser         *string `json:",omitempty"`
	MachineType     *string `json:",omitempty"`
	ImageID         *string `json:",omitempty"`
	Reconciled      *bool   `json:",omitempty"`
	Age             *string `json:",omitempty"`
}

// Get gets a gcp gce machine runtime definition and instance from the Threeport API.
func (g *GcpGceMachineRuntimeConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GcpGceMachineRuntimeConfig, error) {
	// get operations
	operations, gcpGceMachineRuntimeDefinitions, gcpGceMachineRuntimeInstances := g.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for gcp gce machine runtime defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	gcpGceMachineRuntimeConfigs := mapToGcpGceMachineRuntimeDefinedInstances(gcpGceMachineRuntimeDefinitions, gcpGceMachineRuntimeInstances)

	return gcpGceMachineRuntimeConfigs, nil
}

// Create creates a gcp gce machine runtime definition and instance in the Threeport API.
func (g *GcpGceMachineRuntimeConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GcpGceMachineRuntimeConfig, error) {
	// get operations
	operations, gcpGceMachineRuntimeDefinitions, gcpGceMachineRuntimeInstances := g.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for gcp gce machine runtime defined instance with name %s: %w",
			*g.GcpGceMachineRuntime.Name,
			err,
		)
	}

	// assemble the defined instances
	gcpGceMachineRuntimeConfigs := mapToGcpGceMachineRuntimeDefinedInstances(gcpGceMachineRuntimeDefinitions, gcpGceMachineRuntimeInstances)

	return gcpGceMachineRuntimeConfigs, nil
}

// Replace replaces a gcp gce machine runtime definition and instance in the Threeport API.
func (g *GcpGceMachineRuntimeConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]GcpGceMachineRuntimeConfig, error) {
	// get operations
	operations, gcpGceMachineRuntimeDefinitions, gcpGceMachineRuntimeInstances := g.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for gcp gce machine runtime defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	gcpGceMachineRuntimeConfigs := mapToGcpGceMachineRuntimeDefinedInstances(gcpGceMachineRuntimeDefinitions, gcpGceMachineRuntimeInstances)

	return gcpGceMachineRuntimeConfigs, nil
}

// Delete deletes a gcp gce machine runtime definition and instance from the Threeport API.
func (g *GcpGceMachineRuntimeConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GcpGceMachineRuntimeConfig, error) {
	// get operations
	operations, _, _ := g.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for gcp gce machine runtime defined instance with name %s: %w",
			*g.GcpGceMachineRuntime.Name,
			err,
		)
	}

	return nil, nil
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a gcp gce machine runtime defined instance.
func (g *GcpGceMachineRuntimeConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
) (*util.Operations, *[]GcpGceMachineRuntimeDefinitionConfig, *[]GcpGceMachineRuntimeInstanceConfig) {
	var err error
	var operatedGcpGceMachineRuntimeDefinitions []GcpGceMachineRuntimeDefinitionConfig
	var operatedGcpGceMachineRuntimeInstances []GcpGceMachineRuntimeInstanceConfig

	operations := util.Operations{}

	// add gcp gce machine runtime definition operation
	gcpGceMachineRuntimeDefinitionConfig := GcpGceMachineRuntimeDefinitionConfig{
		GcpGceMachineRuntimeDefinition: GcpGceMachineRuntimeDefinitionValues{
			Name:        g.GcpGceMachineRuntime.Name,
			MachineType: g.GcpGceMachineRuntime.MachineType,
			ImageID:     g.GcpGceMachineRuntime.ImageID,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			gcpGceMachineRuntimeDefinition, err := gcpGceMachineRuntimeDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create gcp gce machine runtime definition with name %s: %w", *g.GcpGceMachineRuntime.Name, err)
			}
			operatedGcpGceMachineRuntimeDefinitions = append(operatedGcpGceMachineRuntimeDefinitions, *gcpGceMachineRuntimeDefinition)
			return nil
		},
		Delete: func() error {
			_, err = gcpGceMachineRuntimeDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete gcp gce machine runtime definition with name %s: %w", *g.GcpGceMachineRuntime.Name, err)
			}
			return nil
		},
		Get: func() error {
			gcpGceMachineRuntimeDefinitions, err := gcpGceMachineRuntimeDefinitionConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get gcp gce machine runtime definitions: %w", err)
			}
			operatedGcpGceMachineRuntimeDefinitions = append(operatedGcpGceMachineRuntimeDefinitions, *gcpGceMachineRuntimeDefinitions...)
			return nil
		},
		Name: "gcp gce machine runtime definition",
		Replace: func(name string) error {
			gcpGceMachineRuntimeDefinition, err := gcpGceMachineRuntimeDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace gcp gce machine runtime definition with name %s: %w", name, err)
			}
			operatedGcpGceMachineRuntimeDefinitions = append(operatedGcpGceMachineRuntimeDefinitions, *gcpGceMachineRuntimeDefinition)
			return nil
		},
	})

	// add gcp gce machine runtime instance operation
	gcpGceMachineRuntimeInstanceConfig := GcpGceMachineRuntimeInstanceConfig{
		GcpGceMachineRuntimeInstance: GcpGceMachineRuntimeInstanceValues{
			Name:            g.GcpGceMachineRuntime.Name,
			GcpProviderName: g.GcpGceMachineRuntime.GcpProviderName,
			Region:          g.GcpGceMachineRuntime.Region,
			Zone:            g.GcpGceMachineRuntime.Zone,
			NetworkID:       g.GcpGceMachineRuntime.NetworkID,
			SSHUser:         g.GcpGceMachineRuntime.SSHUser,
			GcpGceMachineRuntimeDefinition: &GcpGceMachineRuntimeDefinitionValues{
				Name: g.GcpGceMachineRuntime.Name,
			},
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			gcpGceMachineRuntimeInstance, err := gcpGceMachineRuntimeInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create gcp gce machine runtime instance with name %s: %w", *g.GcpGceMachineRuntime.Name, err)
			}
			operatedGcpGceMachineRuntimeInstances = append(operatedGcpGceMachineRuntimeInstances, *gcpGceMachineRuntimeInstance)
			return nil
		},
		Delete: func() error {
			_, err = gcpGceMachineRuntimeInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete gcp gce machine runtime instance with name %s: %w", *g.GcpGceMachineRuntime.Name, err)
			}
			return nil
		},
		Get: func() error {
			gcpGceMachineRuntimeInstances, err := gcpGceMachineRuntimeInstanceConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get gcp gce machine runtime instances: %w", err)
			}
			operatedGcpGceMachineRuntimeInstances = append(operatedGcpGceMachineRuntimeInstances, *gcpGceMachineRuntimeInstances...)
			return nil
		},
		Name: "gcp gce machine runtime instance",
		Replace: func(name string) error {
			gcpGceMachineRuntimeInstance, err := gcpGceMachineRuntimeInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace gcp gce machine runtime instance with name %s: %w", name, err)
			}
			operatedGcpGceMachineRuntimeInstances = append(operatedGcpGceMachineRuntimeInstances, *gcpGceMachineRuntimeInstance)
			return nil
		},
	})

	return &operations, &operatedGcpGceMachineRuntimeDefinitions, &operatedGcpGceMachineRuntimeInstances
}

// mapToGcpGceMachineRuntimeDefinedInstances maps a slice of gcp gce machine runtime definition and instance configs
// to a slice of gcp gce machine runtime config objects
func mapToGcpGceMachineRuntimeDefinedInstances(
	gcpGceMachineRuntimeDefinitions *[]GcpGceMachineRuntimeDefinitionConfig,
	gcpGceMachineRuntimeInstances *[]GcpGceMachineRuntimeInstanceConfig,
) *[]GcpGceMachineRuntimeConfig {
	var gcpGceMachineRuntimeConfigs []GcpGceMachineRuntimeConfig
	for _, inst := range *gcpGceMachineRuntimeInstances {
		for _, def := range *gcpGceMachineRuntimeDefinitions {
			instName := *inst.GcpGceMachineRuntimeInstance.Name
			defName := *def.GcpGceMachineRuntimeDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && inst.GcpGceMachineRuntimeInstance.GcpGceMachineRuntimeDefinition != nil && *inst.GcpGceMachineRuntimeInstance.GcpGceMachineRuntimeDefinition.Name == *def.GcpGceMachineRuntimeDefinition.Name {
				gcpGceMachineRuntimeConfig := GcpGceMachineRuntimeConfig{
					GcpGceMachineRuntime: GcpGceMachineRuntimeValues{
						Name:            inst.GcpGceMachineRuntimeInstance.Name,
						GcpProviderName: inst.GcpGceMachineRuntimeInstance.GcpProviderName,
						Region:          inst.GcpGceMachineRuntimeInstance.Region,
						Zone:            inst.GcpGceMachineRuntimeInstance.Zone,
						NetworkID:       inst.GcpGceMachineRuntimeInstance.NetworkID,
						SSHUser:         inst.GcpGceMachineRuntimeInstance.SSHUser,
						MachineType:     def.GcpGceMachineRuntimeDefinition.MachineType,
						ImageID:         def.GcpGceMachineRuntimeDefinition.ImageID,
						Reconciled:      inst.GcpGceMachineRuntimeInstance.Reconciled,
						Age:             inst.GcpGceMachineRuntimeInstance.Age,
					},
				}
				gcpGceMachineRuntimeConfigs = append(gcpGceMachineRuntimeConfigs, gcpGceMachineRuntimeConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &gcpGceMachineRuntimeConfigs
}
