// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	"net/http"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// KubernetesWorkloadConfig is a config abstraction for the
// KubernetesWorkloadDefinition and KubernetesWorkloadInstance API objects.
// This abstraction allows users to manage definitions and instances together
// with single operations rather than separate operations for each API object.
type KubernetesWorkloadConfig struct {
	Workload KubernetesWorkloadValues `yaml:"Workload"`
}

// KubernetesWorkloadValues contains all the attributes needed to manage the
// KubernetesWorkloadDefinition and KubernetesWorkloadInstance API objects
// together with a single operation.
type KubernetesWorkloadValues struct {
	Name                      *string                          `json:",omitempty" yaml:"Name,omitempty"`
	YAMLDocument              *string                          `json:",omitempty" yaml:"YAMLDocument,omitempty"`
	WorkloadConfigPath        *string                          `json:",omitempty" yaml:"WorkloadConfigPath,omitempty"`
	KubernetesRuntimeInstance *KubernetesRuntimeInstanceValues `json:",omitempty" yaml:"KubernetesRuntimeInstance,omitempty"`
	DomainName                *DomainNameDefinitionValues      `json:",omitempty" yaml:"DomainName,omitempty"`
	Gateway                   *GatewayDefinitionValues         `json:",omitempty" yaml:"Gateway,omitempty"`
	Secret                    *SecretValues                    `json:",omitempty" yaml:"Secret,omitempty"`
	Status                    *string                          `json:",omitempty" yaml:"Status,omitempty"`
	Age                       *string                          `json:",omitempty" yaml:"Age,omitempty"`
}

// Get gets a kubernetes workload definition and instance from the Threeport API.
func (w *KubernetesWorkloadConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]KubernetesWorkloadConfig, error) {
	// get operations
	operations, workloadDefinitions, workloadInstances := w.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for workload defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	workloadConfigs := mapToWorkloadDefinedInstances(workloadDefinitions, workloadInstances)

	return workloadConfigs, nil
}

// Create creates a kubernetes workload definition and instance in the Threeport API.
func (w *KubernetesWorkloadConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]KubernetesWorkloadConfig, error) {
	workloadValues := w.Workload
	// get operations
	operations, workloadDefinitions, workloadInstances := w.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for workload defined instance with name %s: %w",
			*workloadValues.Name,
			err,
		)
	}

	// assemble the defined instances
	workloadConfigs := mapToWorkloadDefinedInstances(workloadDefinitions, workloadInstances)

	return workloadConfigs, nil
}

// Replace replaces a kubernetes workload definition and instance in the Threeport API.
func (w *KubernetesWorkloadConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]KubernetesWorkloadConfig, error) {
	// get operations
	operations, workloadDefinitions, workloadInstances := w.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for workload defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	workloadConfigs := mapToWorkloadDefinedInstances(workloadDefinitions, workloadInstances)

	return workloadConfigs, nil
}

// Delete deletes a kubernetes workload definition and instance from the Threeport API.
func (w *KubernetesWorkloadConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]KubernetesWorkloadConfig, error) {
	workloadValues := w.Workload
	// get operations
	operations, _, _ := w.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for workload defined instance with name %s: %w",
			*workloadValues.Name,
			err,
		)
	}

	return nil, nil
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a workload defined instance.
func (w *KubernetesWorkloadConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
) (*util.Operations, *[]KubernetesWorkloadDefinitionConfig, *[]KubernetesWorkloadInstanceConfig) {
	workloadValues := w.Workload
	var err error
	var operatedWorkloadDefinitions []KubernetesWorkloadDefinitionConfig
	var operatedWorkloadInstances []KubernetesWorkloadInstanceConfig

	operations := util.Operations{}

	// add kubernetes workload definition operation
	workloadDefinitionConfig := KubernetesWorkloadDefinitionConfig{
		KubernetesWorkloadDefinition: KubernetesWorkloadDefinitionValues{
			Name:               workloadValues.Name,
			YAMLDocument:       workloadValues.YAMLDocument,
			WorkloadConfigPath: workloadValues.WorkloadConfigPath,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			workloadDefinition, err := workloadDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create kubernetes workload definition with name %s: %w", *workloadValues.Name, err)
			}
			operatedWorkloadDefinitions = append(operatedWorkloadDefinitions, *workloadDefinition)
			return nil
		},
		Delete: func() error {
			_, err = workloadDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete kubernetes workload definition with name %s: %w", *workloadValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			workloadDefinitions, err := workloadDefinitionConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get workload definitions: %w", err)
			}
			operatedWorkloadDefinitions = append(operatedWorkloadDefinitions, *workloadDefinitions...)
			return nil
		},
		Name: "kubernetes workload definition",
		Replace: func(name string) error {
			workloadDefinition, err := workloadDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace kubernetes workload definition with name %s: %w", name, err)
			}
			operatedWorkloadDefinitions = append(operatedWorkloadDefinitions, *workloadDefinition)
			return nil
		},
	})

	// add kubernetes workload instance operation
	workloadInstanceConfig := KubernetesWorkloadInstanceConfig{
		KubernetesWorkloadInstance: KubernetesWorkloadInstanceValues{
			Name:                      workloadValues.Name,
			KubernetesRuntimeInstance: workloadValues.KubernetesRuntimeInstance,
			KubernetesWorkloadDefinition:        &workloadDefinitionConfig.KubernetesWorkloadDefinition,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			workloadInstance, err := workloadInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create kubernetes workload instance with name %s: %w", *workloadValues.Name, err)
			}
			operatedWorkloadInstances = append(operatedWorkloadInstances, *workloadInstance)
			return nil
		},
		Delete: func() error {
			_, err = workloadInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete kubernetes workload instance with name %s: %w", *workloadValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			workloadInstance, err := workloadInstanceConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get workload instances: %w", err)
			}
			operatedWorkloadInstances = append(operatedWorkloadInstances, *workloadInstance...)
			return nil
		},
		Name: "kubernetes workload instance",
		Replace: func(name string) error {
			workloadInstance, err := workloadInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace kubernetes workload definition with name %s: %w", name, err)
			}
			operatedWorkloadInstances = append(operatedWorkloadInstances, *workloadInstance)
			return nil
		},
	})

	// add domain name if provided
	var domainNameDefinitionConfig DomainNameDefinitionConfig
	if workloadValues.DomainName != nil {
		// add domain name definition operation
		domainNameDefinitionConfig = DomainNameDefinitionConfig{
			DomainNameDefinition: DomainNameDefinitionValues{
				Name:       workloadValues.DomainName.Name,
				Domain:     workloadValues.DomainName.Domain,
				Zone:       workloadValues.DomainName.Zone,
				AdminEmail: workloadValues.DomainName.AdminEmail,
			},
		}
		operations.AppendOperation(util.Operation{
			Name: "domain name definition",
			Create: func() error {
				_, err = domainNameDefinitionConfig.Create(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to create domain name definition with name %s: %w", *workloadValues.DomainName.Name, err)
				}
				return nil
			},
			Delete: func() error {
				_, err = domainNameDefinitionConfig.Delete(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to delete domain name definition with name %s: %w", *workloadValues.DomainName.Name, err)
				}
				return nil
			},
			Get: func() error {
				// Get operation for domain name definition would be handled by individual objects
				return nil
			},
			Replace: func(name string) error {
				_, err = domainNameDefinitionConfig.Replace(apiClient, apiEndpoint, name)
				if err != nil {
					return fmt.Errorf("failed to replace domain name definition with name %s: %w", name, err)
				}
				return nil
			},
		})

		// add domain name instance operation
		domainNameInstanceConfig := DomainNameInstanceConfig{
			DomainNameInstance: DomainNameInstanceValues{
				DomainNameDefinition:      &domainNameDefinitionConfig.DomainNameDefinition,
				KubernetesRuntimeInstance: workloadValues.KubernetesRuntimeInstance,
				KubernetesWorkloadInstance:          &workloadInstanceConfig.KubernetesWorkloadInstance,
			},
		}
		operations.AppendOperation(util.Operation{
			Name: "domain name instance",
			Create: func() error {
				_, err = domainNameInstanceConfig.Create(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to create domain name instance with name %s: %w", *workloadValues.DomainName.Name, err)
				}
				return nil
			},
			Delete: func() error {
				_, err = domainNameInstanceConfig.Delete(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to delete domain name instance with name %s: %w", *workloadValues.DomainName.Name, err)
				}
				return nil
			},
			Get: func() error {
				// Get operation for domain name instance would be handled by individual objects
				return nil
			},
			Replace: func(name string) error {
				_, err = domainNameInstanceConfig.Replace(apiClient, apiEndpoint, name)
				if err != nil {
					return fmt.Errorf("failed to replace domain name instance with name %s: %w", name, err)
				}
				return nil
			},
		})
	}

	// add gateway if provided
	if workloadValues.Gateway != nil {
		// add gateway definition operation
		gatewayDefinitionConfig := GatewayDefinitionConfig{
			GatewayDefinition: GatewayDefinitionValues{
				Name:                 workloadValues.Gateway.Name,
				HttpPorts:            workloadValues.Gateway.HttpPorts,
				TcpPorts:             workloadValues.Gateway.TcpPorts,
				ServiceName:          workloadValues.Gateway.ServiceName,
				SubDomain:            workloadValues.Gateway.SubDomain,
				DomainNameDefinition: &domainNameDefinitionConfig.DomainNameDefinition,
			},
		}

		operations.AppendOperation(util.Operation{
			Name: "gateway definition",
			Create: func() error {
				_, err = gatewayDefinitionConfig.Create(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to create gateway definition with name %s: %w", *workloadValues.Gateway.Name, err)
				}
				return nil
			},
			Delete: func() error {
				_, err = gatewayDefinitionConfig.Delete(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to delete gateway definition with name %s: %w", *workloadValues.Gateway.Name, err)
				}
				return nil
			},
			Get: func() error {
				// Get operation for gateway definition would be handled by individual objects
				return nil
			},
			Replace: func(name string) error {
				_, err = gatewayDefinitionConfig.Replace(apiClient, apiEndpoint, name)
				if err != nil {
					return fmt.Errorf("failed to replace gateway definition with name %s: %w", name, err)
				}
				return nil
			},
		})

		// add gateway instance operation
		gatewayInstanceConfig := GatewayInstanceConfig{
			GatewayInstance: GatewayInstanceValues{
				Name:                      workloadValues.Gateway.Name,
				GatewayDefinition:         &gatewayDefinitionConfig.GatewayDefinition,
				KubernetesRuntimeInstance: workloadValues.KubernetesRuntimeInstance,
				KubernetesWorkloadInstance:          &workloadInstanceConfig.KubernetesWorkloadInstance,
			},
		}
		operations.AppendOperation(util.Operation{
			Name: "gateway instance",
			Create: func() error {
				_, err = gatewayInstanceConfig.Create(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to create gateway instance with name %s: %w", *workloadValues.Gateway.Name, err)
				}
				return nil
			},
			Delete: func() error {
				_, err = gatewayInstanceConfig.Delete(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to delete gateway instance with name %s: %w", *workloadValues.Gateway.Name, err)
				}
				return nil
			},
			Get: func() error {
				// Get operation for gateway instance would be handled by individual objects
				return nil
			},
			Replace: func(name string) error {
				_, err = gatewayInstanceConfig.Replace(apiClient, apiEndpoint, name)
				if err != nil {
					return fmt.Errorf("failed to replace gateway instance with name %s: %w", name, err)
				}
				return nil
			},
		})
	}

	// add secret operation
	if workloadValues.Secret != nil {
		secretConfig := SecretConfig{
			Secret: SecretValues{
				Name:                      workloadValues.Secret.Name,
				AwsProviderName:           workloadValues.Secret.AwsProviderName,
				Data:                      workloadValues.Secret.Data,
				KubernetesRuntimeInstance: workloadValues.KubernetesRuntimeInstance,
				KubernetesWorkloadInstance:          &workloadInstanceConfig.KubernetesWorkloadInstance,
			},
		}
		operations.AppendOperation(util.Operation{
			Name: "secret",
			Create: func() error {
				_, err := secretConfig.Create(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to create secret defined instance with name %s: %w", *workloadValues.Secret.Name, err)
				}
				return nil
			},
			Delete: func() error {
				_, err := secretConfig.Delete(apiClient, apiEndpoint)
				if err != nil {
					return fmt.Errorf("failed to delete secret defined instance with name %s: %w", *workloadValues.Secret.Name, err)
				}
				return nil
			},
			Get: func() error {
				// Get operation for secret would be handled by individual objects
				return nil
			},
			Replace: func(name string) error {
				_, err := secretConfig.Replace(apiClient, apiEndpoint, name)
				if err != nil {
					return fmt.Errorf("failed to replace secret defined instance with name %s: %w", name, err)
				}
				return nil
			},
		})
	}

	return &operations, &operatedWorkloadDefinitions, &operatedWorkloadInstances
}

// mapToWorkloadDefinedInstances maps a slice of kubernetes workload definition and instance configs
// to a slice of workload config objects
func mapToWorkloadDefinedInstances(
	workloadDefinitions *[]KubernetesWorkloadDefinitionConfig,
	workloadInstances *[]KubernetesWorkloadInstanceConfig,
) *[]KubernetesWorkloadConfig {
	var workloadConfigs []KubernetesWorkloadConfig
	for _, inst := range *workloadInstances {
		for _, def := range *workloadDefinitions {
			instName := *inst.KubernetesWorkloadInstance.Name
			defName := *def.KubernetesWorkloadDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.KubernetesWorkloadInstance.KubernetesWorkloadDefinition.Name == *def.KubernetesWorkloadDefinition.Name {
				workloadConfig := KubernetesWorkloadConfig{
					Workload: KubernetesWorkloadValues{
						Name:                      inst.KubernetesWorkloadInstance.Name,
						YAMLDocument:              def.KubernetesWorkloadDefinition.YAMLDocument,
						WorkloadConfigPath:        def.KubernetesWorkloadDefinition.WorkloadConfigPath,
						KubernetesRuntimeInstance: inst.KubernetesWorkloadInstance.KubernetesRuntimeInstance,
						//DomainName:                inst.KubernetesWorkloadInstance.DomainName,
						//Gateway:                   inst.KubernetesWorkloadInstance.Gateway,
						//Secret:                    inst.KubernetesWorkloadInstance.Secret,
						Status: inst.KubernetesWorkloadInstance.Status,
						Age:    inst.KubernetesWorkloadInstance.Age,
					},
				}
				workloadConfigs = append(workloadConfigs, workloadConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &workloadConfigs
}
