// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	errors "errors"
	"fmt"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// MachineWorkloadInstanceConfig is a config abstraction for the MachineWorkloadInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type MachineWorkloadInstanceConfig struct {
	MachineWorkloadInstance MachineWorkloadInstanceValues `yaml:"MachineWorkloadInstance"`
}

// MachineWorkloadInstanceValues contains all the attributes needed to manage
// the MachineWorkloadInstance API object.
type MachineWorkloadInstanceValues struct {
	// TODO: add config abstraction fields needed for user to manage a MachineWorkloadInstance
	Name                      *string                          `json:"Name,omitempty" yaml:"Name,omitempty"`
	MachineWorkloadDefinition *MachineWorkloadDefinitionValues `json:"MachineWorkloadDefinition,omitempty" yaml:"MachineWorkloadDefinition,omitempty"`
	Age                       *string                          `json:"Age,omitempty" yaml:"Age,omitempty"`
}

// Get gets machine workload instances from the Threeport API.
// If the name is set in the MachineWorkloadInstanceValues, it will return the machine workload instance with that name.
// If the name is not set, it will return all machine workload instances.
func (m *MachineWorkloadInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]MachineWorkloadInstanceConfig, error) {
	machineWorkloadInstanceValues := m.MachineWorkloadInstance

	// get API objects
	var machineWorkloadInstances *[]api_v0.MachineWorkloadInstance
	switch {
	// if name is provided, get machine workload instance by name
	case machineWorkloadInstanceValues.Name != nil:
		machineWorkloadInstance, err := client_v0.GetMachineWorkloadInstanceByName(apiClient, apiEndpoint, *machineWorkloadInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get machine workload instance with name %s: %w", *machineWorkloadInstanceValues.Name, err)
		}
		machineWorkloadInstances = &[]api_v0.MachineWorkloadInstance{*machineWorkloadInstance}
	// get all machine workload instances
	default:
		allMachineWorkloadInstances, err := client_v0.GetMachineWorkloadInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get machine workload instances from Threeport API: %w", err)
		}
		machineWorkloadInstances = allMachineWorkloadInstances
	}

	// assemble config objects from API objects
	var machineWorkloadInstanceConfigs []MachineWorkloadInstanceConfig
	for _, machineWorkloadInstance := range *machineWorkloadInstances {
		// TODO: add config abstraction fields needed for user to manage a MachineWorkloadInstance
		machineWorkloadInstanceConfig := MachineWorkloadInstanceConfig{
			MachineWorkloadInstance: MachineWorkloadInstanceValues{
				Age:  util.Ptr(util.GetAgeFormatted(machineWorkloadInstance.CreatedAt)),
				Name: machineWorkloadInstance.Name,
			},
		}
		machineWorkloadInstanceConfigs = append(machineWorkloadInstanceConfigs, machineWorkloadInstanceConfig)
	}

	return &machineWorkloadInstanceConfigs, nil
}

// Create creates a machine workload instance in the Threeport API.
func (m *MachineWorkloadInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*MachineWorkloadInstanceConfig, error) {
	machineWorkloadInstanceValues := m.MachineWorkloadInstance

	// validate config
	if err := m.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for machine workload instance with name %s: %w", *machineWorkloadInstanceValues.Name, err)
	}

	// construct machine workload instance object
	// TODO: add API object fields as needed for MachineWorkloadInstance
	machineWorkloadInstance := api_v0.MachineWorkloadInstance{
		Instance: api_v0.Instance{
			Name: machineWorkloadInstanceValues.Name,
		},
	}

	// create machine workload instance
	createdMachineWorkloadInstance, err := client_v0.CreateMachineWorkloadInstance(
		apiClient,
		apiEndpoint,
		&machineWorkloadInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create machine workload instance in threeport API: %w", err)
	}

	// construct machine workload instance config
	// TODO: add config abstraction fields needed for user to manage a MachineWorkloadInstance
	createdMachineWorkloadInstanceConfig := &MachineWorkloadInstanceConfig{
		MachineWorkloadInstance: MachineWorkloadInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(createdMachineWorkloadInstance.CreatedAt)),
			Name: createdMachineWorkloadInstance.Name,
		},
	}

	return createdMachineWorkloadInstanceConfig, nil
}

// Replace updates the entire machine workload instance object in the Threeport API.
// This is a full replacement of all fields in the machine workload instance object.
// This function takes a name parameter to identify the machine workload instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (m *MachineWorkloadInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*MachineWorkloadInstanceConfig, error) {
	machineWorkloadInstanceValues := m.MachineWorkloadInstance

	// validate config
	if err := m.Validate(); err != nil {
		return nil, fmt.Errorf("invalid machine workload instance config: %w", err)
	}

	// get existing machine workload instance by name
	existingMachineWorkloadInstance, err := client_v0.GetMachineWorkloadInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find machine workload instance with name %s: %w", name, err)
	}

	// construct updated machine workload instance object
	// TODO: add API object fields as needed for MachineWorkloadInstance
	updatedMachineWorkloadInstance := &api_v0.MachineWorkloadInstance{
		Common: api_v0.Common{
			ID: existingMachineWorkloadInstance.ID,
		},
		Instance: api_v0.Instance{
			Name: machineWorkloadInstanceValues.Name,
		},
	}

	// replace machine workload instance
	replacedMachineWorkloadInstance, err := client_v0.ReplaceMachineWorkloadInstance(
		apiClient,
		apiEndpoint,
		updatedMachineWorkloadInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace machine workload instance in threeport API: %w", err)
	}

	// construct updated machine workload instance config
	// TODO: add config abstraction fields needed for user to manage a MachineWorkloadInstance
	updatedMachineWorkloadInstanceConfig := &MachineWorkloadInstanceConfig{
		MachineWorkloadInstance: MachineWorkloadInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(replacedMachineWorkloadInstance.CreatedAt)),
			Name: replacedMachineWorkloadInstance.Name,
		},
	}

	return updatedMachineWorkloadInstanceConfig, nil
}

// Delete deletes a machine workload instance from the Threeport API.
func (m *MachineWorkloadInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*MachineWorkloadInstanceConfig, error) {
	machineWorkloadInstanceValues := m.MachineWorkloadInstance

	// get machine workload instance by name
	machineWorkloadInstance, err := client_v0.GetMachineWorkloadInstanceByName(
		apiClient,
		apiEndpoint,
		*machineWorkloadInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find machine workload instance with name %s: %w", *machineWorkloadInstanceValues.Name, err)
	}

	// delete machine workload instance
	deletedMachineWorkloadInstance, err := client_v0.DeleteMachineWorkloadInstance(
		apiClient,
		apiEndpoint,
		*machineWorkloadInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete machine workload instance from Threeport API: %w", err)
	}

	// construct deleted machine workload instance config
	// TODO: add config abstraction fields needed for user to manage a MachineWorkloadInstance
	deletedMachineWorkloadInstanceConfig := &MachineWorkloadInstanceConfig{
		MachineWorkloadInstance: MachineWorkloadInstanceValues{
			Name: deletedMachineWorkloadInstance.Name,
		},
	}

	return deletedMachineWorkloadInstanceConfig, nil
}

// Validate validates inputs to create machine workload instances.
func (m *MachineWorkloadInstanceConfig) Validate() error {
	machineWorkloadInstanceValues := m.MachineWorkloadInstance
	multiError := util.MultiError{}

	// ensure name is set
	if machineWorkloadInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// TODO: add additional validation as needed

	return multiError.Error()
}
