// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// MachineRuntimeConfig is a container for a MachineRuntime which is a config abstraction for
// the MachineRuntimeDefinition and MachineRuntimeInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type MachineRuntimeConfig struct {
	MachineRuntime MachineRuntimeValues `yaml:"MachineRuntime"`
}

// MachineRuntimeValues contains all the attributes needed to manage the
// MachineRuntimeDefinition and MachineRuntimeInstance API objects
// together with a single operation.
type MachineRuntimeValues struct {
	// TODO: add fields needed for user to manage a MachineRuntimeDefinition and MachineRuntimeInstance together
	Name *string `json:"Name,omitempty" yaml:"Name,omitempty"`
	Age  *string `json:"Age,omitempty" yaml:"Age,omitempty"`
}

// Get gets a machine runtime definition and instance from the Threeport API.
func (m *MachineRuntimeConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]MachineRuntimeConfig, error) {
	// get operations
	operations, machineRuntimeDefinitions, machineRuntimeInstances := m.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for machine runtime defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	machineRuntimeConfigs := mapToMachineRuntimeDefinedInstances(machineRuntimeDefinitions, machineRuntimeInstances)

	return machineRuntimeConfigs, nil
}

// Create creates a machine runtime definition and instance in the Threeport API.
func (m *MachineRuntimeConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]MachineRuntimeConfig, error) {
	// get operations
	operations, machineRuntimeDefinitions, machineRuntimeInstances := m.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for machine runtime defined instance with name %s: %w",
			*m.MachineRuntime.Name,
			err,
		)
	}

	// assemble the defined instances
	machineRuntimeConfigs := mapToMachineRuntimeDefinedInstances(machineRuntimeDefinitions, machineRuntimeInstances)

	return machineRuntimeConfigs, nil
}

// Replace replaces a machine runtime definition and instance in the Threeport API.
func (m *MachineRuntimeConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]MachineRuntimeConfig, error) {
	// get operations
	operations, machineRuntimeDefinitions, machineRuntimeInstances := m.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for machine runtime defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	machineRuntimeConfigs := mapToMachineRuntimeDefinedInstances(machineRuntimeDefinitions, machineRuntimeInstances)

	return machineRuntimeConfigs, nil
}

// Delete deletes a machine runtime definition and instance from the Threeport API.
func (m *MachineRuntimeConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]MachineRuntimeConfig, error) {
	// get operations
	operations, _, _ := m.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for machine runtime defined instance with name %s: %w",
			*m.MachineRuntime.Name,
			err,
		)
	}

	return nil, nil
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a machine runtime defined instance.
func (m *MachineRuntimeConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
) (*util.Operations, *[]MachineRuntimeDefinitionConfig, *[]MachineRuntimeInstanceConfig) {
	var err error
	var operatedMachineRuntimeDefinitions []MachineRuntimeDefinitionConfig
	var operatedMachineRuntimeInstances []MachineRuntimeInstanceConfig

	operations := util.Operations{}

	// add machine runtime definition operation
	// TODO: add appropriate fields to definition values object
	machineRuntimeDefinitionValues := MachineRuntimeDefinitionValues{
		Name: m.MachineRuntime.Name,
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			machineRuntimeDefinition, err := machineRuntimeDefinitionValues.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create machine runtime definition with name %s: %w", *m.MachineRuntime.Name, err)
			}
			operatedMachineRuntimeDefinitions = append(operatedMachineRuntimeDefinitions, *machineRuntimeDefinition)
			return nil
		},
		Delete: func() error {
			_, err = machineRuntimeDefinitionValues.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete machine runtime definition with name %s: %w", *m.MachineRuntime.Name, err)
			}
			return nil
		},
		Get: func() error {
			machineRuntimeDefinitions, err := machineRuntimeDefinitionValues.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get machine runtime definitions: %w", err)
			}
			operatedMachineRuntimeDefinitions = append(operatedMachineRuntimeDefinitions, *machineRuntimeDefinitions...)
			return nil
		},
		Name: "machine runtime definition",
		Replace: func(name string) error {
			machineRuntimeDefinition, err := machineRuntimeDefinitionValues.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace machine runtime definition with name %s: %w", name, err)
			}
			operatedMachineRuntimeDefinitions = append(operatedMachineRuntimeDefinitions, *machineRuntimeDefinition)
			return nil
		},
	})

	// add machine runtime instance operation
	// TODO: add appropriate fields to instance values object
	machineRuntimeInstanceValues := MachineRuntimeInstanceValues{
		Age:  m.MachineRuntime.Age,
		Name: m.MachineRuntime.Name,
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			machineRuntimeInstance, err := machineRuntimeInstanceValues.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create machine runtime instance with name %s: %w", *m.MachineRuntime.Name, err)
			}
			operatedMachineRuntimeInstances = append(operatedMachineRuntimeInstances, *machineRuntimeInstance)
			return nil
		},
		Delete: func() error {
			_, err = machineRuntimeInstanceValues.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete machine runtime instance with name %s: %w", *m.MachineRuntime.Name, err)
			}
			return nil
		},
		Get: func() error {
			machineRuntimeInstances, err := machineRuntimeInstanceValues.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get machine runtime instances: %w", err)
			}
			operatedMachineRuntimeInstances = append(operatedMachineRuntimeInstances, *machineRuntimeInstances...)
			return nil
		},
		Name: "machine runtime instance",
		Replace: func(name string) error {
			machineRuntimeInstance, err := machineRuntimeInstanceValues.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace machine runtime instances with name %s: %w", name, err)
			}
			operatedMachineRuntimeInstances = append(operatedMachineRuntimeInstances, *machineRuntimeInstance)
			return nil
		},
	})

	return &operations, &operatedMachineRuntimeDefinitions, &operatedMachineRuntimeInstances
}

// mapToMachineRuntimeDefinedInstances maps a slice of machine runtime definition and instance configs
// to a slice of machine runtime config objects
func mapToMachineRuntimeDefinedInstances(
	machineRuntimeDefinitions *[]MachineRuntimeDefinitionConfig,
	machineRuntimeInstances *[]MachineRuntimeInstanceConfig,
) *[]MachineRuntimeConfig {
	var machineRuntimeConfigs []MachineRuntimeConfig
	for _, inst := range *machineRuntimeInstances {
		for _, def := range *machineRuntimeDefinitions {
			instName := *inst.MachineRuntimeInstance.Name
			defName := *def.MachineRuntimeDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.MachineRuntimeInstance.MachineRuntimeDefinition.Name == *def.MachineRuntimeDefinition.Name {
				// TODO: add fields needed for user to manage a MachineRuntimeDefinition and MachineRuntimeInstance together
				machineRuntimeConfig := MachineRuntimeConfig{
					MachineRuntime: MachineRuntimeValues{
						Age:  inst.MachineRuntimeInstance.Age,
						Name: inst.MachineRuntimeInstance.Name,
					},
				}
				machineRuntimeConfigs = append(machineRuntimeConfigs, machineRuntimeConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &machineRuntimeConfigs
}
